### ISSUE TITLE
Text isn't documented in the API

### ISSUE THREAD

**Issue by thequailman** [jorgebucaran/hyperapp#1001]
Hello, when playing around with Hyperapp, I couldn't find the API docs for `text()`, seems like the API link is missing too: https://github.com/jorgebucaran/hyperapp/blob/main/docs/reference.md#text

All text output needs to be wrapped in this function, right?

**Comment by zaceno** [comment]
@thequailman yeah that's right. Afaik the reference.md file is still a work in progress @jorgebucaran could tell you more. As far as I know there isn't a whole lot left. The `text()` function you mentioned is one thing. Another thing missing (which could be important to know depending on your use case) is that actions can return other actions. 

For example: 

```js
const HandleKey = (state, event) =>
      event.key === 'ArrowUp' ? [MoveUp, event.timestamp]  //MoveUp is another action 
    : event.key === 'ArrowDown' ? [MoveDown, event.timestamp]  //MoveDown is another action
    : state //by default, noop
```
