### ISSUE TITLE
How to deal with global event?

### ISSUE THREAD

**Issue by ndaidong** [jorgebucaran/hyperapp#1004]
Hi there,

I want to change app state once user presses ESC key. How to call action on that?
I can not find any tutorial relating to this popular use case.

Thanks,

**Comment by selfup** [comment]
In the subscription documentation there is a global event listener (window): https://github.com/jorgebucaran/hyperapp/blob/main/docs/reference.md#subscriptions

**Comment by ndaidong** [comment]
@selfup ah thank you, that's my mistake. I need to reload the document system here.

**Comment by selfup** [comment]
All good!
