### ISSUE TITLE
Subscriptions implementation question

### ISSUE THREAD

**Issue by icylace** [jorgebucaran/hyperapp#1017]
https://github.com/jorgebucaran/hyperapp/blob/1b7cb2f21f316a759a82d00a9ce713cfff6846e8/index.js#L53

Is the ` && newSub !== true` part actually necessary? What am I missing ?

**Comment by jorgebucaran** [comment]
That line is filtering out falsy and boolean types. `true` is not a valid subscription, and we want to skip it. This is like conditional rendering for subscriptions. This allows you to turn subscriptions on/off the same way you'd conditionally render a part of the view.

**Comment by icylace** [comment]
I understand that's the intent but when something like `state.showing && h("div", {}, state.thingy)` is used in a view that part of the view is only ever falsy or a VDOM. The actual value `true` doesn't come into play. Even if you were to use `true` directly it behaves the same as `false`, which is to say nothing gets rendered.

It seems you're making the subscriptions semantics follow view semantics that don't exist. A direct `true` value in the subscriptions list feels like an invalid use case and therefore should error out when `newSub[0]` is attempted a couple lines later.

**Comment by icylace** [comment]
Maybe the idea is a pure boolean value means "don't do the thing" ?

**Comment by jorgebucaran** [comment]
A `true` value can appear when you use `||` instead of `&&`.

```js
[state.shouldStop || sub]
```

That will evaluate to: `[true]` when `state.shouldStop` is `true`.

**Comment by jorgebucaran** [comment]
`true` can appear when you use `||` instead of `&&`.

```js
[state.shouldStop || sub]
```

That will evaluate to: `[true]` when `state.shouldStop` is `true`.

**Comment by icylace** [comment]
Ahh... Okay, I obviously had not considered that style of coding. Good to know, thanks !

**Comment by jorgebucaran** [comment]
This is true about views too, by the way:

```js
state.isHidden || h1(text(state.message))
```

**Comment by icylace** [comment]
Yes, of course 👍

**Comment by icylace** [comment]
Due to this conversation I realize there may be a bug in my types.  I think I know what it is and will gladly fix it 💯

**Comment by jorgebucaran** [comment]
We happen to be using the same trick right here:

https://github.com/jorgebucaran/hyperapp/blob/1332e88a06691fc923fcd24660a165afdc262f7e/index.js#L411-L414

**Comment by jorgebucaran** [comment]
Webhook Test 🙇

**Comment by jorgebucaran** [comment]
Webhook Test 🙇

**Comment by jorgebucaran** [comment]
We happen to be using the same trick right here:

https://github.com/jorgebucaran/hyperapp/blob/1332e88a06691fc923fcd24660a165afdc262f7e/index.js#L411-L414
