### ISSUE TITLE
Can't loop in hyperapp

### ISSUE THREAD

**Issue by C-NERD** [jorgebucaran/hyperapp#1025]
Hello guys I am trying to use hyperapp for a project and I can't seem to loop over an array, it's just gives errors.

**Comment by C-NERD** [comment]
Please tell me an alternative I can use

**Comment by jorgebucaran** [comment]
What did you try to do? What's your code? @C-NERD

**Comment by jorgebucaran** [comment]
What did you try to do? What's your code?

**Comment by jorgebucaran** [comment]
Here's how you can traverse an array creating an HTML list.

```js
import { h } from "hyperapp"

const listView = list => h("ul", {},
  list.map((item) => h("li", {}, text(item)))
)
```

If you go ahead and post your code we may be able to help you a bit more. 

This doesn't look like a bug report so I'm closing for now. 🖖✨

**Comment by C-NERD** [comment]
Thanks i really appreciate it.
