### ISSUE TITLE
hyperapp http requests

### ISSUE THREAD

**Issue by C-NERD** [jorgebucaran/hyperapp#1026]
Hi so i want to make a request to a backend but i found out that there is no code for hyperapp http then i tried using ajax i encountered a problem now i am using fetch api and i am having problem with the promise that accompanies the api. Is there a standard hyperapp way of overcoming this problem

**Comment by C-NERD** [comment]
`js
fetch('http://0.0.0.0:2000/https%3A%2F%2F0.0.0.0:10000%2Fquestions%2Fenglish%2F2006.json')
  .then(response => response.json())
  .then(data => info = data);
`

That's the code by the way

**Comment by jorgebucaran** [comment]
You can use [custom effects](https://github.com/jorgebucaran/hyperapp/blob/2935f30886715fc934d1cd869806c43b8ffcd5e5/docs/reference.md#effects) to encapsulate your `fetch` code _or_ check out [hyperapp-fx's Http effect](https://github.com/okwolf/hyperapp-fx/blob/master/api.md#fxexportshttpprops) for a simplistic approach that works well and can be used right now.

The official **@hyperapp/http** package is still in the works, but I hope to release a working alpha soon. There's also a discussion you can subscribe to (https://github.com/jorgebucaran/hyperapp/discussions/1027). 💁‍♂️

**Comment by C-NERD** [comment]
Thanks again

**Comment by C-NERD** [comment]
sorry for the disturbance but i tried the custom effects and the fx-Http but i was unable to achieve my goal. The goal is to call the effect and to use the response as my state(parameter) before the main code runs

```js
app({
145 ┊ ┊ init: ({data : info, count : 0}),
146 ┊ ┊ node: document.getElementById("app"),
147 ┊ ┊ view: ({data, count}) =>
148 ┊ ┊ ┊ ┊ h('main', {id : 'background'}, [
149 ┊ ┊ ┊ ┊ ┊ ┊ //data(info),
150 ┊ ┊ ┊ ┊ ┊ ┊ question(data[count], count + 1),
151 ┊ ┊ ┊ ┊ ┊ ┊ h('section', {id : 'panel'}, panel(data.length))
152 ┊ ┊ ┊ ┊ ])
153 })
```

**Comment by jorgebucaran** [comment]
@C-NERD I think it would be easier to help you if you [join our discord](https://discord.com/invite/5CtfCYEq8V). 👋
