### ISSUE TITLE
React ref equivalent in hyperapp v2?

### ISSUE THREAD

**Issue by aminroosta** [jorgebucaran/hyperapp#1029]
In `v1` there where undocumented lifecycle methods (`oncreate`, `onupdate`, and `onremove`) that could be used to get a reference to the dom node created.

That has been removed in `v2`.

How do I get a reference to a DOM node?

**Comment by jorgebucaran** [comment]
The answer really depends on what you want to use that DOM node for.

The easy way is with `document.getElementById()` inside a custom effect or outside your application's pure layer.

What are you trying to do?

**Comment by aminroosta** [comment]
There is a library called [split.js ](https://github.com/nathancahill/split/tree/master/packages/splitjs), I'm writing a wrapper for.

```ts
var split = Split(<HTMLElement|selector[]> elements, <options> options?)
```

Basically i need  to pass `$parent.children` the first time my component is created and clean it up once it's removed.

**Comment by aminroosta** [comment]
closing, since it's been discuss before in https://github.com/jorgebucaran/hyperapp/issues/717

**Comment by zaceno** [comment]
@aminroosta In case you're unclear on the details, have a look at [https://zaceno.github.io/codealong-hyperapp/#n10](#10 of my code-along video series) where I implement a custom effect for finding dom elements to call the `.focus()` method on them.
