### ISSUE TITLE
Support non ES Module bundle in NPM

### ISSUE THREAD

**Issue by jcubic** [jorgebucaran/hyperapp#1030]
I would like to use version 2.0 but I can't use ES Modules. I'm using Hyper app in different language (Scheme) I have interpreter and I would like to import the file the usual way but version 2.0 have only single file for modern browser (ES Modules) No other files are available:

https://unpkg.com/browse/hyperapp@2.0.12/

Because of this I can't update my examples to include app written in Scheme and HyperApp.

Here you can see example with Preact + LIPS (my Scheme interpreter) https://codepen.io/jcubic/pen/JjKbqWd?editors=1000
I can't create same example with HyperApp.

Any chance of supporting UMD?

**Comment by zaceno** [comment]
@jcubic perhaps you could use rollup in your build-system to generate the umd version for you?

**Comment by jorgebucaran** [comment]
Have you setup a build system?

**Comment by jorgebucaran** [comment]
ECMAScript modules are the official standard format to package JavaScript code for reuse, not UMD. 

What about adding ES module support to LIPS instead? (https://github.com/jcubic/lips/issues/125)

Now, you could always create your own UMD or IIFE bundle using Rollup or Webpack as suggested. You've got the source, you have the power! ✨🤘✨

**Comment by jcubic** [comment]
It's nice that you want to make your project modern but you're excluding lot of usage of the project if you don't support the UMD. I will need to add your project to crippled libraries that don't support browser and build the files myself (https://cdn.jsdelivr.net/gh/jcubic/static/js/). But I will not get auto update. And most of the time for my users your project will be useless because they will not update to latest version.

Just FYI not every browser use ES Modules you can use this approach to libraries that you know that you don't need to support weird browsers but for library it's important to support every browser. I guess you don't care.

**Comment by jcubic** [comment]
I guess I need to forget that your project ever existed and delete all examples. I will use Preact instead that care about the users.

**Comment by jorgebucaran** [comment]
I'm sorry that you are having a bad day. There's nothing preventing you from creating a UMD build for Hyperapp. We're not blocking you.

**Comment by jorgebucaran** [comment]
I'm sorry that you are having a bad day. 💔

There's nothing preventing you from creating a UMD build for Hyperapp.

**Comment by zaceno** [comment]
@jcubic You do what you need to do of course, but just some data to help you out:

- Hyperapp is not really trying to be a smaller, faster react. Not really competing with preact. The philosophical differences were less pronounced in v1 so it was easy to make that mistake. V2 is different and more strict with the principles. Just to say if you did get v2 working in your setup you might be in for another unpleasant surprise in how different it is and how much you’ll  need to refactor your examples anyway. If you see preact as a viable alternative, chances are you weren’t choosing Hyperapp for its philosophy/architecture anyway.
- The v2 source is written in es6 using spread/rest and fat arrow functions. In other words, it doesn’t work directly in older browsers anyway - it needs to be transpiled. If older browsers are your target, and you want to use v2, you’ll need to transpile anyway, and UMD builds are just a flag away.
- There has been some discussion about wether we should offer multiple builds for various scenarios: umd / esm, unminified & minified, transpiled to es5 or not, source-maps or not? The conclusion was its best to just offer the raw source as is and let each user process that to their liking. There are even CDNs that do some (all?) of those options for you with flags, so why should we cater to every possible combination?
- V2 is not yet officially released yet. It is still in “beta”. During beta, semver is not respected. That means there may still be breaking changes coming, but they will only bump the minor or patch version numbers. So “auto update” is still dangerous and you need to be following the goings on to know what chamged.

**Comment by jcubic** [comment]
I think I've created example using non module, it use dynamic imports to execute module outside of module.

https://codepen.io/jcubic/pen/wvogZVv?editors=1000

Just FYI if you're interested. It was base for example with HyperApp + LIPS but got error:

```
Cannot set property children of #<Element> which has only a getter
```
In line:
```
node[key] = newValue == null ? "" : newValue
```
and node is h1 element.

Any clue why I've got this error?

Anyway I think that the version v2 is of no use too me because I can't use JSX anymore it have breaking change the requirement to use hyperapp.text to render text.

**Comment by jorgebucaran** [comment]
JSX can be used alright, it's just not natively supported! We are considering an official `@hyperapp/jsx` package to make it smoother for JSX users (#1011). I advocate for an actual JavaScript-based alternative like `@hyperapp/html`, template literal function, or just the lovely `h()`.

**Comment by jcubic** [comment]
I can't use `type="module"` because that's reserved to `type="text/javascript"` that is default when it's missing. I can't use `type="module"`. I also don't use JSX I use SXML but under the hood is just calling h, but if `text` is required then you no longer can have strings as values because you need to use `text("hello")`, as I understand `h("div", {}, "hello")` will not work that is what JSX use after transpiling. I acually don't care about JSX but care if it works the same.

**Comment by jorgebucaran** [comment]
Hyperapp wants you to define your text nodes explicitly, so that would be:

```js
h("div", {}, text("hello"))
```

or

```scheme
(div (text "hello"))
```

Excerpt from (#1009):

> Text nodes are not strings. `"This is a string"` and `text("this is a text node")`. It may seem plain, but it isn't from a type perspective. Text nodes and strings are different types. Because it's now up to you to specify text nodes we don't have to worry about it, which allowed us to simplify `h` quite a bit.

**Comment by jcubic** [comment]
So it's not compatible with JSX transpilers like babel then. You have something extra on top of default behavior. So you can't use same code to compile HyperApp and Preact. They are not compatible so I can't use same code for both Preact and HyperApp.

I think that with version 2.0 you will loose lot of users because of this compatibility issue.

**Comment by zaceno** [comment]
@jcubic I'm not quite following what you're doing with SXML and your Scheme-set-up, but I do think you're misunderstanding something: It is perfectly possible to use JSX with hyperapp. The only difference now from before is that you can't use Hyperapp's built-in `h` function as the pragma anymore.

When you use Babel or whatever to transform jsx to javascript, you need to tell it what "pragma" to use. Then babel will transform the JSX into calls to that pragma function. If you don't provide a pragma it will assume `React.createElement` so even if you are using Preact, you need to provide a custom pragma (Preact's `h` function)

It used to be you could provide hyperapp's `h` as pragma, but that no longer works as you correctly pointed out. However, you can import a third-party pragma from 'hyperapp-jsx-pragma'  instead, and all is well again (demo here: video number 3: https://zaceno.github.io/codealong-hyperapp/#n3 ) – So no one is prevented from using JSX to define their hyperapp views. (Someday that package might be moved to `@hyperapp/jsx`)

That said: Hyperapp views and Preact views _are_ funcamentally incompatible, even if they are written in JSX. Views written for Preact will not work in Hyperapp and vice versa. And this has _always_ been so (not just since v2). 

 Preact has `onClick=` (like React) where hyperapp has `onclick=`.  Preact has `className=` (like React) where Hyperapp has `class=` . Preact supports fragments `<>...</>`   (like React), while Hyperapp does not. And so on... As I said before: Hyperapp is not trying to be a better Preact, and expecting compatibility with Preact in any sense is a mistake.

**Comment by jorgebucaran** [comment]
You are comparing apples and oranges. Hyperapp is not a React-like framework. Hyperapp is not a smaller-sized React. 

Hyperapp does not compete in the same space as Preact. React components are usually not compatible with Hyperapp views. JSX support is not a goal either.

Have you heard about Elm? Hyperapp is largely inspired by it. Try to compare Hyperapp with Elm.

Now, you don't need to compile anything to start using Hyperapp. But if you do, the build step will be essentially the same as whatever you use with Preact or React. 👌

**Comment by jcubic** [comment]
Thanks for clarification. Note that by compatible I mean that I can use babel to transform JSX into library h function code.'
If you're interested what SXML is it's basically S-Expression (lisp syntax) version of JSX that probably was invetented long before jSX. Example:

```
(render (sxml (div (@ (id "foo"))
                   (p "Hello World")
                   (Button1 (@ (name "me")))
                   (Button2 (@ (name "me")))))
        document.body)
```

The version v1 allowed to use just hyperapp.h and I could use this syntax but under the hood it would be just be:
```
h("p", {}, [h("div", ...)])
```

Maybe I will be able to use `hyperapp-jsx-pragma` it use to be simple to use hyperapp the same as it's simple to use Preact. I'm comparing those two because they are both small and allow to create UI. The same I would compare Vue.js and React, they are both UI frameworks and if Vue.js would support JSX it would most likely be the same as with Preact I could compare the too and be upset if suddenly Vue.js break JSX standard (the fundamentals of `h` function).

**Comment by zaceno** [comment]
@jcubic You should be able to use hyperapp-jsx-pragma the same way you used the old hyperapp.h – that's basically why it exists :)

**Comment by fsrc** [comment]
I have had similar problems using HyperApp with LiveScript and browserify. I just downloaded the single hyperapp.js removed the ES exports and and put regular exports at the bottom of the file.

@jcubic I have kept an eye on your LIPS for some time and considered pairing it with HyperApp. But lacking any Lisp-experience it was far to risky for my current project. Now I'm diving into ClojureScript instead to learn the Lisp-ways. 

I love HyperApp architecture but I just can't stand using vanilla Javascript for so many reasons. Paired with LIPS with macrosupport would really wrap everything up beautifully! Please don't become discouraged but try to find a solution to this. There is a need for HyperApp paired with a great language.

**Comment by jorgebucaran** [comment]
Not HyperApp, but Hyperapp.
