### ISSUE TITLE
@hyperapp/navigation can't handle external links

### ISSUE THREAD

**Issue by shish** [jorgebucaran/hyperapp#1033]
`history.pushState({}, "", url)` is a security error if `url` has a different origin than the current document.

I'm not sure what the "correct" solution is here, but my feeling is that the nicest thing to do would be to detect links to an external domain and fall back to the browser's default onclick handler instead of trying to handle the click for ourselves (ie don't call `event.preventDefault()`, don't call `dispatch()`)

**Comment by jorgebucaran** [comment]
I've decided to focus on shipping Hyperapp and creating quality examples to show people how easy it is to DIY these things, instead of crafting scoped packages, so I'm not going to publish **@hyperapp/navigation** any time soon. Closing.
