### ISSUE TITLE
TypeError: can't access property 0, newSubs is null, when setting the state to undefined.

### ISSUE THREAD

**Issue by teehemkay** [jorgebucaran/hyperapp#1072]
Setting the state to undefined (per the [Stopping your app](https://github.com/jorgebucaran/hyperapp/blob/main/docs/architecture/actions.md#stopping-your-app) section in the docs) triggers a type error.

The issue seems to come from the following line:
https://github.com/jorgebucaran/hyperapp/blob/d6e07044d2fb829bc187b55102c2f76c854e6bb6/index.js#L382

When the `subscriptions` function is replaced with the `id` identify function and the state is `undefined`, the `subscriptions` function [will thus return](https://github.com/jorgebucaran/hyperapp/blob/d6e07044d2fb829bc187b55102c2f76c854e6bb6/index.js#L383) `undefined` instead of returning an [array as expected](https://github.com/jorgebucaran/hyperapp/blob/d6e07044d2fb829bc187b55102c2f76c854e6bb6/index.js#L50) by the `patchSubs` function.

**Comment by teehemkay** [comment]
Upon further investigation, I don't think my assumptions above are correct: normally, `patchSubs` should catch the `undefined` `subscriptions` array and replace it with an `EMPTY_ARRAY` at call time.:

https://github.com/jorgebucaran/hyperapp/blob/d6e07044d2fb829bc187b55102c2f76c854e6bb6/index.js#L43

I'll keep digging and report back ASAP.

**Comment by teehemkay** [comment]
OK, the issue was not with `hyper app` but rather with my code:  the state was set to `null` _instead of_`undefined` resulting in the default `EMPTY_ARR` not being used at call time.

Sorry for the erroneous issue report.

**Comment by jorgebucaran** [comment]
Thanks for clearing that up.

**Comment by teehemkay** [comment]
BTW, thank you so much for hyperapp. It's such exquisitely designed and the code is a joy to read.
