### ISSUE TITLE
prevent rerender node

### ISSUE THREAD

**Issue by noveogroup-amorgunov** [jorgebucaran/hyperapp#1074]
Hey! I want prevent rerender of component (in my case I use div contenteditable and when I rerender component, selection cursor move to first letter.

I patched "patch" function like:

```js
var patch = (parent, node, oldVNode, newVNode, listener, isSvg) => {
+    if (newVNode.props && newVNode.props.shouldUpdate && !newVNode.props.shouldUpdate(oldVNode.props, newVNode.props)) {
    } else if (oldVNode === newVNode) {
    // ...
}
```

and use it:

```ls
<div
    shouldUpdate={shouldUpdate}
    innerHTML={r}
    contenteditable="true">
</div>
```

and it works. But I want to find more elegant way without patching library

**Comment by jorgebucaran** [comment]
Maybe [`memo()`](https://github.com/jorgebucaran/hyperapp/blob/main/docs/api/memo.md) is what you are looking for?

**Comment by noveogroup-amorgunov** [comment]
It's work, thank you
