### ISSUE TITLE
Injected classes gets removed when using object/array to define class props

### ISSUE THREAD

**Issue by MrFluFFy** [jorgebucaran/hyperapp#1078]
There is an issue where if you use the object/array method to define your class prop it "overriders/patches away" other injected classes on state updates, which could come from consumers of the developed app.  ie. maybe there is an app loaded in as a microservice and someone would like to enhance some css and do this by injecting directly into the dom.

Here is a jsfiddle which shows the issue:
Description: modifying the class prop value by an "external" source adding the class `green`  
This is done on 3 components with object/array/string defining the class prop, a state update will cause a patching of the components were object/array is used and thus the externally added class is lost, while using a string will not cause the diff.
https://jsfiddle.net/azhvnyeg/2/

From discord (https://discord.com/channels/804672552348680192/804672553095528470/927872567518298152):

> zaceno — Idag 14:38
> @MrFluFFy OK I understand what you're asking now, and think I can explain what's going on.
> 
> Since you dispatch an action and change the state each time one of your buttons is focused, then after you add something to the classList,  hyperapp will diff the DOM. And if hyperapp detects that one of the button's class attributes has changed, it will reapply it, thereby removing the class you added using the event handler.
> 
> As your example shows, hyperapp thinks that your button's class prop has changed when you use the array- or object- method of defining a class prop. But not when you use a string. That is, simply because and inline-defined object will have a different reference each time hyperapp diffs the vdom. A plain string (being a primitive value) is seen as the same - hence no change detected – hence hyperapp doesn't fiddle with the classes.

**Comment by zaceno** [comment]
I guess this could be fixed by resolving the class attributes before diffing (in h, for instance) - that should have no downside.

Even though this is only a problem when external scripts fiddle with the DOM hyperapp expects control over, which one could argue is out of scope for hyperapp to consider, I think this fix would improve performance somewhat and so I endorse it.
