### ISSUE TITLE
Confusing doc for actions -> wrapped actions

### ISSUE THREAD

**Issue by kofifus** [jorgebucaran/hyperapp#1081]
in https://github.com/jorgebucaran/hyperapp/blob/main/docs/architecture/actions.md#wrapped-actions

```
const AddByValue = (state, event) => [AddBy, +event.target.value]
```

I am confused about the `+` before `event.target.value`, is it a typo ? or is it a hack to coerce into number ? perhaps a clearer way is better ?

**Comment by jorgebucaran** [comment]
It's totally a hack to coerce into a number. 💯

**Comment by kofifus** [comment]
OK it was a new for me .. may confuse others as well ..

**Comment by jorgebucaran** [comment]
I agree that the docs can be a little playful.

**Comment by zaceno** [comment]
I wouldn't say it's a "hack" exactly. It's the standard way to cast a string to a number. Or at least it's how I always do it and how I've always seen it done. How else would you do it?

**Comment by jorgebucaran** [comment]
There's also `parseInt` and `parseFloat`. I'll probably use `+` for brevity.
