### ISSUE TITLE
Unlikely Use Case bug in HTML and SVG Packages

### ISSUE THREAD

**Issue by frenetic43** [jorgebucaran/hyperapp#1114]
Both the SVG and HTML Packages define a tag function as such:
```ts
const tag = (tag) => (
  props = EMPTY_OBJ,
  children = props.tag != null || Array.isArray(props) ? props : EMPTY_ARR
) => h(tag, props === children ? EMPTY_OBJ : props, children)
```

I took notice of it, just because it didn't occur to me that you could use ternary logic or reference other parameters in a default parameter value. So I started playing around with it and found:

1. An actual bug in the SVG package.
    ```ts
    const tag = (tag) => (
      props,  // Missing default ` = EMPTY_OBJ`
      children = props.tag != null || Array.isArray(props) ? props : EMPTY_ARR
    ) => h(tag, props === children ? EMPTY_OBJ : props, children)
    ```
    Result:
    ```ts
    const example = tag('svg');

    // When called with No arguments
    const vnode = example();

    // Results in undefined props sent to 'h' call
    h(tag, undefined, EMPTY_ARR)

    // But still works if there is at least one parameter
    const vnode = example({});  // Works fine
    const vnode = example([]);  // Works fine
    ```

    Arguably, it's pretty unlikely that SVG elements would be created without attributes or children, but still...

1. Unlikely Use Case bug in both HTML and SVG packages

    Specifically the line `props === children`

    ```ts
    const example = tag('svg');

    // When called with Two Arrays
    const vnode = example([ 'Array 1' ], [ 'Array 2' ]);

    // Results in both arrays being sent to `h` call
    // Because these are not the same arrays,
    // and `children` did not copy the `props` value
    h(tag, [ 'Array 1' ], [ 'Array 2' ])
    ```

    Again, an unlikely use-case-scenario, however if it was changed to `Array.isArray(props) ? EMPTY_OBJ : props` then it would just silently ignore the first array, but still work. Or merge the arrays or something like that.

1. Just a question regarding the line: `children = props.tag != null`.
    What is the purpose of checking `props.tag != null`?
    Near as I can tell it doesn't serve any purpose except possibly setting the children parameter to boolean true if an attribute of 'tag' is given;

    ```ts
      const example = tag('svg');

      // When called with tag Attribute and children array omitted
      const vnode = example({ tag: 'value' });

      // Results in children being set as true? in `h` call.
      h(tag, { tag: 'zep' }, true)
    ```

    Again, an unlikely scenario, but I'm assuming the 'tag' attribute was chosen because it was unlikely? As a check that it's an object? If such is the case wouldn't `Array.isArray(props)` already return false if `props` was an object? Or is this intended to override something I'm not seeing?

1. Parenthesis

    Granted parenthesis can be omitted on ternary logic and equality checks, however given the environment (Node, Deno, Browser, Etc.) it's running in, it can sometimes be unpredictable.

    ```ts
    const tag = (tag) => (
      props = EMPTY_OBJ,
      children = (props.tag != null) || (Array.isArray(props) ? props : EMPTY_ARR)
    ) => h(tag, (props === children ? EMPTY_OBJ : props), children)


    const example = tag('svg');

    // When called with tag attribute and children array omitted
    const vnode = example({ tag: 'value' });

    // I'm running this in Deno and `props.tag != null`
    // was ignored (falsey) until I enclosed it in parenthesis.
    ```

---

I like how the function can omit the props parameter and still handle the children parameter. But maybe it would be better to go completely variadic? Something like:
```ts
const tag = (tag) = (...args) => {
  let props = {}, children = [];  // New objects for mutations
  for (const arg of args) {
    if (Array.isArray(arg)) { children = [ ...children, ...arg ]; }
    else { props = { ...props, ...arg }; }
  }
};
```
This would allow any number of arguments to be accepted in any order. Though personally, I think I prefer limiting it to just 2 parameters, it's more readable.

**Comment by zaceno** [comment]
Not the package author, but here's my 2c:

1) I wouldn't exactly call it a bug - although it's unexpected. It's generally pretty unusual to have just a bare, self closing tag anyway (I guess <br /> might be the one case I can think of). So it's quite reasonable to expect one argument at least.

2) Don't think I'd call this a bug either, but a misuse of the api. If two arguments are given, the first should be an object containing the props. Since an array is _technically_ an object, well .. there you go.

3) The point of the `props.tag` check (if I recall correctly) is to enable single-node children without array wrappers. E g:

```js
p(text("foo"))
// or
p({class: 'error'}, text("foo"))
```
You're correct it's presumed unlikely that "tag" will be a property sent to any html/svg node. Moreover, `tag` _is_  a property of hyperapp's vnodes. So `props.tag != null` is basically taken to mean: `props` is a single vnode.

4) this is news to me. Seems very strange that precedence rules for expressions would work differently on different runtimes. 

5) I've experimented with the variadic style in the past and I think for now I prefer the neatness/clarity of "array means children". I usually even use arrays for single-node children even though it's not strictly necessary (see point 3).

**Comment by frenetic43** [comment]
@zaceno
1. & 2. Maybe calling it a bug is a stronger word than I thought. I wouldn't call this behavior app-breaking, more like you said, a "misuse of the api" but as a general rule; 'if it can go wrong, it will go wrong... eventually'. So, personally I like to hear about even unlikely use-cases in my own projects so I can eliminate the option of 'going wrong' before it happens.

2. Ah, but the point was that the `props === children` comparison is checking if they're the _same_ object. Which would be the case if no attributes object was passed and the `children` default value copied the `props` parameter. Of course, you could pass pretty much anything as the first parameter including functions and classes, after all they're _all_ objects but they wouldn't be the same as the `children` object.
    ```ts
    import { h as hFunction } from 'hyperApp';
    import { svg } from 'hyperApp/svg';
    
    const vnode = svg(hFunction, [ 'Array 2' ]);
    
    // Results in
    h('svg' hFunction, [ 'Array 2' ]);
    ```
    And yes, even I'm asking: "Why would I do that?"

3. Ah, thank you. I didn't look closely enough at the core code. Looking up how `text("foo")` works I think I got it.
    ```js
    // A vNode is just an object with set properties
    var createVNode = (tag, { key, ...props }, children, type, node) => ({
      tag, props, key, children, type, node,
    })
    
    // So the text function is putting the text value in the `tag` property
    export var text = (value, node) =>
      createVNode(value, EMPTY_OBJ, EMPTY_ARR, TEXT_NODE, node)
    
    // And createNode is checking both the vdom.type and vdom.tag
    var createNode = (vdom, listener, isSvg) => {
      var props = vdom.props
      var node =
        vdom.type === TEXT_NODE
          ? document.createTextNode(vdom.tag)
        ...
    ```
    Yeah, so it's a check to see if a VNode was passed as the first parameter.


4. Okay, honestly this was just embarrassing... 
    Like I mentioned in my opening post, I've never seen complex default properties for parameters before.
    ```ts
    // What I thought was happening, basic short-circuit assignment evaluation
    children = ( props.tag != null ) || ( Array.isArray(props) ? props : EMPTY_ARR )
    
    // Not unlike you see elsewhere, such as
    param = paramMightBeUndefined || defaultParamValue;
    
    // How it's supposed to read...
    children = (
        ( props.tag != null || Array.isArray(props) )
        ? props
        : EMPTY_ARR
    )
    ```
    So yeah, number 3 is bogus, I broke it by adding those parenthesis.
    
    But to be fair half the time I can't remember which language I'm coding in. So I tend to put arbitrary and unnecessary parenthesis around things anyways. Though I still stand by my statement that different environments can have unpredicatable differences.
    
5. Honestly, I think the appeal of variadic functions as someone who's more used to languages where they're not an option is just the novelty of them.

    I was looking at HyperApp because I was writing a wrapper around those incredibly-verbose DOM calls and the convention of the `h` function caught my eye. I was also looking at [HyperScript](https://github.com/hyperhype/hyperscript) which is more variadic and weighing the pros and cons.
    
    I'm thinking from the standpoint of code-complexity and like you said the "neatness/clarity" or just readability, variadic functions might be more trouble than they're worth.

**Comment by zaceno** [comment]
Regarding #5 and variadic functions, you're right, hyperscript has them, and also has transformation of plain strings to virtual text-nodes. And I think also flattening of children. I could be wrong but suspect that's all inherited from JSX and `React.createElement`. Hyperscript is trying to be JSX compatible.

Hyperapp's `h` function used to be Hyperscript/JSX compatible. At some point (2.0.19 ?) it was realized that the core of hyperapp could be made more efficient by not doing the loop over children to see if they are vnodes or strings to map to text-vnodes. Because only people using JSX were taking advantage of that logic, and it could just as easily be separated out into a helper function that JSX-users could optionally include (see https://github.com/zaceno/hyperapp-jsx-pragma) 

So that's the backstory why hyperapp's `h` isn't quite what you expect, and why you need `text` for text-nodes.

**Comment by frenetic43** [comment]
@zaceno
Ah, that makes sense. I haven't used JSX as yet, the closest I've come is [Tagged Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) and they do much the same thing. The first parameter is an array of static strings and the interpolated variables are presented as a variable length list of parameters. I wonder if there's a connection between the two?

Separating that variadic functionality into an optional include only for those who use it does seem more efficient.

---

## Update on other issues.

2. `props === children`. If the purpose is just to manage omitting the props parameter this works fine. I think I can chaulk the issue up to just the intricacies of JavaScript.

    It's funny, you go to school, learn a language like C++ and they drill into you that you always make class members private and use getters and setters for data-security. Then you start using a language like JavaScript where you can create properties anywhere, anytime, and anyone can access them and there is always that voice in the back of your head saying 'something... is off here'.

    I do notice however, there is a TypeScript declaration file for the 'core' HyperApp file that does define a `Props` type. Which is probably the best protection you can get for 'misuse of apis' in JS. Something like that added to the package files might be a good idea.

1. The missing `props = EMPTY_OBJ` default parameter in the SVG package `tag` function.

    There is also the matter of scope here. HyperApp appears to be intended to manage the DOM internally so creating a new tag without attributes or children is almost impossible.

    As I mentioned however, I was just looking at `h` type functions to create a simple wrapper around DOM calls, so in my own case, it's entirely possible to create an empty element and configure it later. My current project is more 'render once and that component over there adds listeners that change classes' so HyperApp's vDOM diffing isn't really a good fit.

    I ended up with chained operators:
    ```ts
    h('div', { attrs }, [ children ])
      .attrs({ more attrs })
      .on('trigger', () => 'do stuff')
    ```

    But when someone looks at the HTML package and then at the SVG package, it's just... out of place, is the best I can describe it.
  

Either way, I'm just going to mark this issue as 'closed'. I think it mostly comes down to 1) I was curious and 2) JavaScript drives me nuts.

**Comment by jorgebucaran** [comment]
> @frenetic43 Something like that added to the package files might be a good idea.

It should be there ([/hyperapp/package.json#L12-L14](https://github.com/jorgebucaran/hyperapp/blob/c3717e3ff78b6fa8663575d34d330d68929a0974/package.json#L12-L14)) ([unpkg.com/browse/hyperapp/](https://unpkg.com/browse/hyperapp/)).

**Comment by frenetic43** [comment]
Sorry, I was referring to typing for the `tag` function included in the SVG and HTML packages, which I don't see in the declaration file. Or is that the `TypedH` interface?

Something like this? (In TypeScript)
```ts
export function tag <Type extends Element>
  (tag: string, namespace?: string) {

  const createVElement: {  // Typed to Overloaded Function Declarations
    (): VElement<Type>;
    (attrs: Attributes): VElement<Type>;
    (children: Children): VElement<Type>;
    (attrs: Attributes, children: Children): VElement<Type>;

  } = (  // Parameters
    attrs: Attributes | Children = {},
    children: Children = (Array.isArray(attrs) ? attrs : [])

  ) => new VElement <Type> ( tag,    // Return Call
    (Array.isArray(attrs) ? {} : attrs),
     children, namespace );
    
  // ... attach other functions to createVElement

  return createVElement;
}
```

**Comment by zaceno** [comment]
> @zaceno Ah, that makes sense. I haven't used JSX as yet, the closest I've come is [Tagged Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) and they do much the same thing. The first parameter is an array of static strings and the interpolated variables are presented as a variable length list of parameters. I wonder if there's a connection between the two?
> 

You may be interested in another project of mine https://github.com/zaceno/hyperlit - haven't updated it much lately but it works pretty well, except for some minor occasional whitespace wierdness. (I really should get back to fixing that)

**Comment by zaceno** [comment]
@frenetic43 

> Sorry, I was referring to typing for the `tag` function included in the SVG and HTML packages, which I don't see in the declaration file. Or is that the `TypedH` interface?
> 

Like @jorgebucaran said, there aren't official type declarations for those files. But I made one for  @hyperapp/html at least, in case you're interested, here: https://github.com/zaceno/todomvc-hyperapp/blob/main/.types/hyperapp-html.d.ts
