### ISSUE TITLE
Why there is no `mount()`function?

### ISSUE THREAD

**Issue by bitsnaps** [jorgebucaran/hyperapp#1117]
Is there any specific reason why there is no shortcut for `document.getElementById(el)`, I would suggest:
```js
const $ = (el) => document.querySelector(el);
...
const node = $('#app');
```
or -if you're jQuery allergic:
```js
const mount = (el) => document.getElementById(el);
...
const node = mount('app');
```
This may saves some stroke keys, improve readability and helps writing less error prone code.

**Comment by jorgebucaran** [comment]
Well, because it's not strictly necessary. Hyperapp provides you with just the essentials, giving you the freedom to build and customize as you wish.
