### ISSUE TITLE
Development build of Hyperapp

### ISSUE THREAD

**Issue by vdsabev** [jorgebucaran/hyperapp#417]
As discussed on [Slack](hyperappjs.slack.com), I'm creating this issue so we can have a discussion about having a separate build of Hyperapp that developers can use for better debugging and detailed error messages.

### Why?
Today, I stumbled upon an issue where the `h` function wouldn't accept a date, like `{new Date()}`. Which is reasonable, except I got an error that I had a hard time understanding at first, which was `Uncaught TypeError: Cannot read property 'length' of undefined`. You can see a reproduction of the error here: https://codepen.io/vdsabev/pen/Ewpggx

Hyperapp already _has_ a great developer experience due to having so few concepts to learn. To make the learning process (and beyond) even easier, I think the community would benefit from enhanced error messages in cases like mine. This, however, can't come at the cost of bloating the library - at least not in production.

This issue is about _showing better errors_. #388 is somewhat related - it's about _showing the errors in a better way_.

An example of what React does is: `react-dom.development.js:65 Uncaught Error: Objects are not valid as a React child (found: Thu Oct 12 2017 19:55:23 GMT+0300 (Eastern European Summer Time)). If you meant to render a collection of children, use an array instead.`

### So?
What do you all think? Approaches, examples, alternatives?

Your move.

**Comment by JorgeBucaran** [comment]
This is how our current distro looks like.

```
hyperapp.js
hyperapp.js.gz
hyperapp.js.map
```

What we could do is add a new build.

```
hyperapp.dev.js
```

Anyone correct me if I am wrong, but I believe we need not distribute a sourcemap with a dev build since it's not minified. And providing a gzipped build of a dev build is overkill IMO.

@vdsabev What are some things you would like hyperapp.dev.js to do other than more readable error messages?

**Comment by rajaraodv** [comment]
We just need a non minimized file that we can import, maybe like: 
`import {h, a} from 'hyperapp/dev'` or something similar. But is certainly useful because I'm manually downloading non-minified source files to debug the code.

**Comment by JorgeBucaran** [comment]
@rajaraodv That would not be more helpful than using sourcemaps. I assume you are? :)

For CDN use, yes you would be right, but I would be inclined to add descriptive error messages as well as warnings, like missing keys and whatnot.

**Comment by rajaraodv** [comment]
ah! I didn't realize that you had actual source in the npm dist! Anyway, I think we need an unminified version  both in CDN(for codepen or regular apps) and for npm usage.

 In React, by default, when you import React, they provide a "developer" build with lots of warnings and error messages and ask people to set NODE_ENV=production when generating production build. When they set that, React automatically switches to it's Production build.

**Comment by JorgeBucaran** [comment]
> I think we need an unminified version both in CDN (for codepen or regular apps) and for npm usage.

We already have an unminified version for node.js / npm — the files inside `src`. When you build your project using a modern bundler like Rollup or Webpack, you'll bundle your app using the files inside `src`, because we have enabled this in package.json via pkg.module. [See here](https://github.com/hyperapp/hyperapp/blob/0e5f4f153c8ebc707ce51dc684fea73d3fabe416/package.json#L7).

We **do** need an unminified version in dist as that would help CDN users as well as Browserify users. What I suggest is to make that version the `dev` version anyway.

**Comment by rajaraodv** [comment]
Yep, we need it just for CDN as we already have it in /src

**Comment by JorgeBucaran** [comment]
We could start by just distributing an unminified file in dist since that would involve zero special maintenance.

**Comment by rajaraodv** [comment]
One of my big issues when working with Codepen was that we didn't have an unminified source to debug.

**Comment by vdsabev** [comment]
> What are some things you would like hyperapp.dev.js to do other than more readable error messages?

Can't really think of much right now. Perhaps some additional type assertion checks - code that won't necessarily produce an error, but is an anti-pattern. I don't have enough Hyperapp experience yet to be able to tell. Perhaps you could think of a few examples - what have you seen people do with Hyperapp that makes the hair stand up on the back of your neck?

I think mostly everything else can be outside core - things like logging, HMR, time-travel debugging, devtools integration, or deep-freezing the state.

**Comment by JorgeBucaran** [comment]
@rajaraodv Why doesn't CodePen pick the sourcemap?

**Comment by rajaraodv** [comment]
Not sure! If I put a debugger; to dig into the source, it doesn't do anything. For example in this, if I put a debugger to look into "update", nothing happens https://codepen.io/rajaraodv/pen/pWZaBN

**Comment by vdsabev** [comment]
From the Slack discussions, another use case @selfup bumped into: he used the obsolete `root` property. A development build could throw an error if any unknown properties are used in the `app` function call. Or show warnings for deprecated properties, including migration steps.

**Comment by okwolf** [comment]
From a previous Slack discussion:
> I’m not sure if we should skip patching DOM elements that have been mutated outside Hyperapp, or maybe have a check in a future developer build that would warn the dev about this problem.

Right now`patchElement` throws a very unintuitive
>`Uncaught TypeError: Cannot read property 'childNodes' of undefined`

when there's a mismatch between the children of `oldNode` and `element`. One way this can happen is modifying the DOM in between `repaint` updates. What should we do?

**Comment by Pyrolistical** [comment]
We could add a warning for #438

**Comment by okwolf** [comment]
I was just about to start writing a shim to support [`react-devtools`](https://github.com/facebook/react-devtools) when I realized that I could already get all the same information by making some dev build types of changes that make it available in the DOM.

This is another use case for a dev build I'd like to explore. 👀

**Comment by frenzzy** [comment]
Instead of adding a development build to the core, we can create a higher-order app as a separate project and use it in the development only the same way as [logger](https://github.com/hyperapp/logger). There are a lot of interesting things which HOA may do, for example it may use logger under the hood, validate actions signatures, validate html, runtime error handling with overlay for developer and more.

**Comment by okwolf** [comment]
@frenzzy please see https://github.com/hyperapp/logger/issues/3.

There are also limits to what you can check using an HOA (treasonous, I know 😂 ) so IMO it would be better to do this within a separate dev build of Hyperapp.

**Comment by mattdesl** [comment]
In my experience, most modules on npm are not pre-minified, as it introduces a more complex development workflow. Instead, the burden is on the developer to minify them (_if they so choose_ — I know several devs that prefer to host non-minified demos for users to explore the source).

Any particular reason the `'main'` module has to be pre-minified?

**Comment by frenzzy** [comment]
@okwolf ok, what if instead of development build and HOA (higher order app) create a _HyperappDevTools_ browser plugin? Then all the helpers/warnings/hints/etc will be available even for production app.

**Comment by Pyrolistical** [comment]
@frenzzy I would never use a browser plugin. Those things are not secure

**Comment by okwolf** [comment]
@frenzzy ok, what if instead of development build and HOA (higher order app) create a HyperappDevTools browser plugin? Then all the helpers/warnings/hints/etc will be available even for production app.

I don't think a browser extension would help much. Some of the checks we'd want to do are so deep within the internals of Hyperapp that we're better off swapping out a different implementation of `app`/`h` that does them.

**Comment by JorgeBucaran** [comment]
I thought a browser extension would be really cool, as it could be a mix of all the other things like time travelling, etc.

**Comment by jorgebucaran** [comment]
What's the simplest thing we can do to improve the current situation? Logs?

**Comment by okwolf** [comment]
> @jorgebucaran What's the simplest thing we can do to improve the current situation? console.logs?

Probably, if we can write them in a way that they get compiled out of the non dev build through dead code elimination.

**Comment by jorgebucaran** [comment]
@okwolf I'll create a PR. 👍

**Comment by okwolf** [comment]
@jorgebucaran which warnings/log messages were you planning on adding first?

**Comment by jorgebucaran** [comment]
@okwolf Still haven't created it, but the gist of it is using uglify to remove console.log by adding it to the pure_funcs array.

**Comment by jorgebucaran** [comment]
See https://github.com/jorgebucaran/hyperapp/issues/753 for the resolution! 🎉
