### ISSUE TITLE
Height attribute on img element not working

### ISSUE THREAD

**Issue by jonlov** [jorgebucaran/hyperapp#634]
I was using hyperapp 1.0.1 and this was working
```html
<img src="https://i.pinimg.com/originals/87/b8/67/87b8671c2d08dc83554806539022bde7.gif" height="100px"/>
```
I update to hyperapp 1.1.2 and now it doesn't work, but it does without the "px" like this
```html
<img src="https://i.pinimg.com/originals/87/b8/67/87b8671c2d08dc83554806539022bde7.gif" height="100"/>
```
Here is the [Codepen](https://codepen.io/0n/pen/yvrJmy)

So I went and check what changes were made, and apparently, this breaks after the version 1.0.2.
The problem is [here on line 138](https://github.com/hyperapp/hyperapp/compare/1.0.1...1.0.2#diff-1fdf421c05c1140f6d71444ea2b27638R138) where before it was always using setAttribute
```javascript
if (value == null || value === false) {
    element.removeAttribute(name)	
} else {	
    element.setAttribute(name, value)	
}
```
and now is using 
```javascript
if (typeof value === "function" || (name in element && !isSVG)) {
    element[name] = value == null ? "" : value
} else if (value != null && value !== false) {
    element.setAttribute(name, value)
}
```
If the element has the attribute and because the image height attribute is an int and not a string it is set to 0.

It's not a big issue you could just write the number without the "px". However, there are people who use the "px" like I was doing and then the whole images on the site disappear. Probably there are similar cases like this with other elements.

**Comment by jorgebucaran** [comment]
@jonlov Oh, very interesting. So the problem is that:
```js
element.setAttribute("height", "100px") 
```

...sets the height to `0`?

**Comment by jorgebucaran** [comment]
@mindplay-dk Another use case we forgot to cover?

**Comment by jonlov** [comment]
@jorgebucaran no, setAttribute works just fine. The problem is that
‘’’
element[name] = value == null ? "" : value
‘’’
Sets “100px” to 0. I guess the setAttribute removes the px, but if you set it directly to the object it needs to be an integer.

**Comment by frenzzy** [comment]
```js
const img = document.createElement('img')
img.height = 100                    // <img height="100" />
img.height = "100"                  // <img height="100" />
img.height = "100%"                 // <img height="0" />
img.height = "100px"                // <img height="0" />
img.setAttribute("height", 100)     // <img height="100" />
img.setAttribute("height", "100")   // <img height="100" />
img.setAttribute("height", "100%")  // <img height="100%" />
img.setAttribute("height", "100px") // <img height="100px" />
```
> **`HTMLImageElement.height`**
> Is a `unsigned long` that reflects the height HTML attribute, indicating the rendered height of the image in CSS pixels.
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement

> **HTML `<img>` element `height`**
The intrinsic height of the image in pixels. In `HTML 4`, the height could be defined pixels or as a percentage. In `HTML5`, however, the value must be in pixels.
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by jonlov** [comment]
@frenzzy is not a bug, it will still work using it without px or %. However, 

```
<img height="100px" /> is not the same as <img height="100%" />
```

Also, I didn't know what was happening because it was working on hyperapp 1.0.1 and after some research (time wasted), I realize that this was happening. So I think there's going to be people trying to use the % or px and it won't work. In React it does work.

One solution that I think it would be to change this if statement

```
if (typeof value === "function" || (name in element && !isSVG)) {
// to 
if (typeof value === "function" || (name in element && !isSVG && (typeof element[name] === typeof value))) {
```

or just remove it that line. But I think that

```
element[name] = value 
```

is better than calling a function in performance. So removing it probably will affect the benchmarks

```
img.setAttribute("height", 100) 
```

**Comment by jorgebucaran** [comment]
@jonlov Sorry for the inadvertent breaking changes, I honestly didn't realize and since there was no test for this particular issue this happened. Do you know how other libraries handle this? Inferno, Preact, Mithril, etc.

**Comment by jonlov** [comment]
@jorgebucaran not sure how they handle this, never used any of them. I'll have a look and see if I find anything in their source code.

**Comment by jonlov** [comment]
@jorgebucaran I really miss this feature. I need to write a class or `style={{height: '100%'}}` for every time I want to do a simple `height="100%"`. Are we going to support this?

If we do, would like me to create a PR with the solution in the [comment](https://github.com/hyperapp/hyperapp/issues/634#issuecomment-370188820) I did before?

**Comment by jorgebucaran** [comment]
@jonlov Sorry, I can't _at the moment_ because I would need to commit to supporting it for life. I need more time to study this and see if there's an alternative or not.

**Comment by jonlov** [comment]
@jorgebucaran that's fine, not rush with this. I need to check if there's a similar case like this with other attributes.

**Comment by lukejacksonn** [comment]
@jonlov how often and under what circumstances are you putting height on images like you describe here? It is something I rarely (if ever) have to do, given the plethora of other ways to achieve the same thing; so I am curious!

**Comment by jonlov** [comment]
@lukejacksonn I don’t use percentages on images that much, but I always used the “px” on all the img tags. So when I updated hyperapp all the images broke and I didn’t know why. In all the frameworks I use this always worked. So I’m not sure if there’s going to be people that are going to get stuck because of this.

**Comment by lukejacksonn** [comment]
Thanks for the explanation. I would usually control the height of images with CSS or inline styles, so would never have noticed!

**Comment by jorgebucaran** [comment]
@jonlov You mentioned that it works in React, can you check if it also works in Preact?

**Comment by frenzzy** [comment]
Preact works the same ways as Hyperapp.
Demo: https://codepen.io/frenzzy/pen/MVvrZm?editors=0010

**Comment by jorgebucaran** [comment]
I don't think we should change this. cc @frenzzy?

**Comment by frenzzy** [comment]
Agreed
