### ISSUE TITLE
Support xlink:ref attribute! (#211)

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/hyperapp#645]
It's time to bring #211 back to life. Let's do it.

/cc @ngryman 😉

**Comment by ngryman** [comment]
😂 I remember this one! I could update the PR so it reflects the new code changes. Is that ok for you?

**Comment by jorgebucaran** [comment]
@ngryman Yes! 🙏

**Comment by jorgebucaran** [comment]
@ngryman Ping.

**Comment by ngryman** [comment]
@jorgebucaran Pong! I'm on it.

**Comment by ngryman** [comment]
It seems I don't have write access anymore, so I forked it.

**Comment by jorgebucaran** [comment]
SVG `<use>` `href` works in the latest Safari. Finally!
