### ISSUE TITLE
Component libraries?

### ISSUE THREAD

**Issue by knipferrc** [jorgebucaran/hyperapp#702]
First of all absolutely love hyperapp, nice work, looking forward to 2.0. Just out of curiosity are there any component libraries built with hyperapp? Couldnt find any.  Thought about making one, would there be interest in a hyperapp component lib?

**Comment by knipferrc** [comment]
Awesome! Yeah I was thinking about a component lib from scratch. Maybe hyper-ui or something like that.

**Comment by knipferrc** [comment]
Got started on this, wondering though, since there is no concept of local state, how do we handle toggle for collapsible's etc. Should this all be handled by props or can I use the global store somehow without creating an "app"?

**Comment by russoturisto** [comment]
This may be off-topic, but for me conceptually HA is for building apps based on 3rd party components (at least the ones that require local state).  Also there may be a (possibly blasphemous) way to support local state in HA components - https://github.com/hyperapp/hyperapp/issues/672#issuecomment-383351446

Thanks, :)

**Comment by jorgebucaran** [comment]
@russoturisto Why blasphemous? 😉

**Comment by russoturisto** [comment]
Cause local state is the source of all evil, and speaking of it offends God? :)

I guess it's just my view of current way of things in UI state management.   Global state can itself be partitioned (once complexity is high enough) into an appropriate graph in which all "local" state is properly isolated, maintained and properly cleaned up when necessary.  However by keeping it global you enable cross cutting concern coverage, additional notification mechanisms, etc.

Ultimately it's up to the app developer to manage their state, so who's to say that (property demarcated) global state is not local?

Thanks, :)

**Comment by atomiks** [comment]
@knipferrc

I believe with stateful components, you need to store information about each component that will be used the state beforehand as objects, e.g.:

```jsx
const Collapsible = ({ name, isOpen }, content) => (state, actions) => (
  <div class="Collapsible">
    <button
      class="Collapsible__button"
      onclick={() => actions.collapsible.toggle(name)}
    >
      {name}
    </button>
    {isOpen && <div class="Collapsible__content">{content}</div>}
  </div>
)

const state = {
  collapsible: {
    items: [
      { name: "Contact", isOpen: false },
      { name: "About", isOpen: false } 
    ]
  }
}

const actions = {
  collapsible: {
    toggle: name => ({ items }) => ({
      items: items.map(
        n => n.name === name ? { ...n, isOpen: !n.isOpen } : n 
      )
    })
  }
}

const view = (state, actions) => (
  <main>
    <Collapsible name="Contact">
      <p>Child nodes.</p>
    </Collapsible>
    <Collapsible name="About">
      <p>Child nodes.</p>
    </Collapsible>
  </main>
)
```

Therefore without local state stateful components can't be independent, they are dependent on the global state.

**Comment by russoturisto** [comment]
Sorry about contributing to hijacking of this thread (and re-igniting the "state" religious war).  :(

I totally agree - all is well if you have the key to lookup the state by. :)

**Comment by jorgebucaran** [comment]
It's fine. AFAIC we're discussing local state, but really talking about _emulating_ it using slices.

**Comment by russoturisto** [comment]
yep

**Comment by knipferrc** [comment]
So I created a few basic components so far trying to figure out what is the preferred method of styling in hyperapp? I tried picostyle but ran into some issues with styles overriding each other. Currently using emotion anyone have any other suggestions?

**Comment by Jesspu** [comment]
So we built one for all of work projects, its far from perfect and is always being updated from project to project, but it has quite a few components and mostly up to date documentation. You can also render the docs as component to get to see what everything looks like and how it works. 

https://www.npmjs.com/package/@firstfleet/hyperappcomponents

**Comment by jorgebucaran** [comment]
Hi @knipferrc! Do you have any updates for us? :)

**Comment by knipferrc** [comment]
Hi all, sorry been super busy lately and haven't had much time, definitely wanna get back to this though.

**Comment by dishuostec** [comment]
Recently I use hyperapp and cordova, both of them are awesome!
I made a pull to refresh component by fork PulltoRefresh.js, maybe it can help someone on create web page for mobile device.

https://www.npmjs.com/package/@dishuostec/hyperapp-pulltorefresh

**Comment by jorgebucaran** [comment]
Please send your Hyperapp components libraries or similar Hyperapp-based libraries to https://github.com/hyperapp/awesome. 👋
