### ISSUE TITLE
Transitions broken in 1.2.6

### ISSUE THREAD

**Issue by zaceno** [jorgebucaran/hyperapp#710]
Between 1.2.5 and 1.2.6, this snippet was introduced in the child-patching algorithm:

```js
        if (newKey != null && newKey === getKey(oldChildren[i + 1])) {
          if (oldKey == null) {
            removeElement(element, oldElements[i], oldChildren[i])
          }
          i++
          continue
        }
```

In cases where all children are keyed, and the first one is removed, I believe this somehow causes `onupdate` not to be called for the rest of the children. (Not exactly sure how yet)

Why do I think this?

The behavior can be observed in the "Toasts" example of @hyperapp/transitions: https://codepen.io/zaceno/pen/QOYOZd

Add a few messages (like five) Click the messages away from the top.

Notice that the remaining children don't slide up smoothly as they should. Rather they skip up immediately. This means that the `Move` transition isn't being triggered.

Also, notice that the fade-out animation for removed toasts doesn't occur from their current position at the top, but from their *original* position (before you started removing them). This tells me that the position-tracking isn't being triggered either.

Both the `Move` transition and position tracking are triggered by the `onupdate` lifecycle method. So my conclusion is that `onupdate` is not being called. 

Cross-reference: https://github.com/hyperapp/transitions/issues/19

**Comment by zaceno** [comment]
@SkaterDad If I'm not mistaken, this was an optimization from you. Does the notion that it might cause onupdate not to be called in the other children (that aren't removed) give you any ideas?

**Comment by zaceno** [comment]
One theory could be that perhaps `removeElement` in the snippet above expects the element to be removed immediately?

-- That is not always the case. When using `onremove` lifecycle events, the event-handler may defer removal for a while. (Like the `Exit` transition does, in the "toasts" example above)

**Comment by SkaterDad** [comment]
> @zaceno @SkaterDad If I'm not mistaken, this was an optimization from you. Does the notion that it might cause onupdate not to be called in the other children (that aren't removed) give you any ideas?

Yep, that was my contribution.  It fixed an issue I was having where `<input>` elements in a form would lose focus if you toggled an element right before them.  As a nice side effect, it vastly improved some benchmarks also by preventing the VDOM from moving more elements than it needed to for simple cases.

I've done some experimenting with animations in hyperapp, but never came up with a solution I was happy with.  Trying to do it with hyperapp's VNode lifecycle hooks is very challenging, and leaves your implementation at the mercy of the patch algorithm.

I think in elm, animations are all done via application state, since you can't hook into the VNode lifecycles.

In some other libraries, like snabbdom, there are more ways of hooking into the VDOM to achieve these animations. 

In Vue, to have a re-ordering animation you have to use the [`<transition-group>` component](https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/components/transition-group.js), which manages the animations of its children.  Could something like that be an option?

**Comment by SkaterDad** [comment]
> @jorgebucaran Do you think you could expand on this (if you have any experience with animation in Elm)?

I don't have much first-hand experience, but I've read through some example code.  Since elm is very locked down, the libraries can't mess with DOM nodes directly, so the animation state is kept in the model, and applied by style attributes.

For my own hyperapp apps, I've just stuck with CSS animations/transitions so far.  I'd prefer to do more elaborate stuff in the future, but I tend to go down very deep rabbit holes when I focus on non-feature work :laughing:

**Comment by zaceno** [comment]
@jorgebucaran `onremove` is not the immediate problem here (indirectly it *may* be... don't know). It seems for some reason `onupdate` is not called on the children in this case. That's why I'm saying this is a bug in Hyperapp, not specifically about transitions.

The fix for the bug *might* turn out to be to disable the delayed-remove feature of `onremove`. That would be a shame because it would leave `@hyperapp/transitions` permanently broken (and it wouldn't fix *my* problem 😛 ) But that's probably still better than leaving it in  a semi-broken state.

**Comment by zaceno** [comment]
It's off-topic, but I too would be interested in state-based patterns for managing transitions in Hyperapp. I've tried before but not managed to make something reusable & general out of it.

**Comment by SkaterDad** [comment]
Yep, I figured you were talking about `@hyperapp/transitions`.

Looking into hyperapp's source again, I would expect this function still gets called for all of the children:
https://github.com/hyperapp/hyperapp/blob/master/src/index.js#L304

The `isRecycling` flag should be `false` by then, so it's confusing why `onupdate` wouldn't get added to the lifecycle queue.

**Comment by zaceno** [comment]
So I ran some tests. And it looks like it doesn't have anything to do with removals. Or keys. As far as I can tell, `onupdate` is *never* called!

I ran this test:

```js
test("onupdate bug?", done => {
    var count = 0
    const onupdate = () => { count++ }
    const state = { toggled: false }
    const actions = {toggle: () => ({toggled: true})}
    const view = state => h('ul', {onupdate},
        state.toggled
        ? [
            h('li', {}, ['a']),
            h('li', {}, ['b']),
        ]
        : [
            h('li', {onupdate}, ['a']),
            h('li', {onupdate}, ['b']),
        ]
    )
    const {toggle} = app(state, actions, view, document.body)
    toggle()
    setTimeout(_ => {
        expect(count).toBe(2)
        done()
    }, 200)
})
```

And it fails!!

This seems really wierd. Surely someone else would have noticed this too? Or is no one else using onupdate?

I looked at the test for `onupdate` and noted that, while it has some `expect`s in the `onupdate` handlers -- it doesn't actually verify that `onupdate` is being called (so those `expects` aren't being checked at all)!

**Comment by zaceno** [comment]
Here's the test I wrote to try to replicate the behavior in the toasts example. 

```js
test("onupdate bug?", done => {
    var count = 0
    const onupdate = () => { count++ }
    const onremove = () => {} //noop
    const state = { toggled: true }
    const actions = {toggle: () => ({toggled: false})}
    const view = state => h('ul', {},
        state.toggled
        ? [
            h('li', {key: 'a', onremove}, ['a']),
            h('li', {key: 'b'}, ['b']),
            h('li', {key: 'c'}, ['c']),
        ]
        : [
            h('li', {key: 'b', onupdate}, ['b']),
            h('li', {key: 'c', onupdate}, ['c']),
        ]
    )
    const {toggle} = app(state, actions, view, document.body)
    setTimeout(_ => {
        toggle()
        setTimeout(_ => {
            expect(count).toBe(2)
            done()
        }, 200)
    }, 200)
})
```

It PASSES -- meaning my analysis of what is happening is probably wrong. 

I still think onupdate is not being called for some reason, in that particular case. But I'm not sure why.

**Comment by zaceno** [comment]
Thanks @SkaterDad, and good debugging tip! I actually do that too often... wonder why I didn't think of it this time 😜 

So you've confirmed that onupdate *is* called properly. So I'm out of concrete ideas 😓 

Another observation one could make  is that it's only observed in the Toasts example. Not the other transitions examples. That's not a huge spread of cases, but one thing that's unique about the Toasts example is that it uses deferred removals, in a set of multiple children . (The caursel example also uses deferred removal, but it's only removing the one child)

There is a bug that I've seen only very rarely, where some elements aren't removed properly. That's not exactly what's occuring here (because all elements are eventually removed when you click them). But perhaps it's a new flavor of that bug, produced by the new code in the patching algorithm.

(Please note: I'm not advocating we remove that code. It should stay.  I'm just trying to understand what's happening, and the only (seemingly) relevant diff between 1.2.5 and 1.2.6 is that)

**Comment by jorgebucaran** [comment]
Here is a start: https://github.com/jorgebucaran/superfine/tree/store-elem-in-vnode

If I can get somewhere I like with that branch and use my time well, I may be able to include a partial diff rewrite in 2.0.

**Comment by zaceno** [comment]
Current status of this issue: waiting for superfine's new vdom to be ported to hyperapp as it fixes a bug. The bug was present before hyperapp v1.2.6 as well, but likely exacerbated in v1.2.6, and so that's when I started observing it in @hyperapp/transitions. 

https://github.com/hyperapp/hyperapp/issues/737

**Comment by jorgebucaran** [comment]
A current focus is on shipping V2, so I think I'll never be able to get to this, even after V2. 🙏
