### ISSUE TITLE
JS universal library (widget, component) based on hyperapp (v1 or v2)

### ISSUE THREAD

**Issue by dmitrykurmanov** [jorgebucaran/hyperapp#732]
Just a little bit history: 
I think it is the same problem created by @mindplay-dk https://github.com/hyperapp/hyperapp/issues/672#issuecomment-377922207
@rbiggs talks about local state https://github.com/hyperapp/hyperapp/issues/672#issuecomment-378113751
and then @jorgebucaran talks about just create separate hyperapp's `app` : https://github.com/hyperapp/hyperapp/issues/672#issuecomment-378140442

And I want to discuss @jorgebucaran's approach with creating separate app for component. We can wrap it in `UMD` build (by webpack, rollup or another tool). And we get a universal component that works in the any web framework via the some API. For example [sortablejs](https://github.com/RubaXa/Sortable) it is just library created with JavaScript. And we can use it elsewhere (community of framework could create popular wrapper-component for that library). Why don't we create same component with Hyperapp? Hyperapp's size allows us just include it in library's code (or dependency may be).

I think that main question is intepopability. Users of that library may wants to call some methods (actions) to get/set something outside of **hyperapp** app and they wants to add event handlers (for example before and after every action)

So what about creating the universal library based on hyperapp? Does hyperapp support this use case?

**Comment by selfup** [comment]
I think this will be solved with subscriptions and middleware in V2.

Currently hyperapp V1 exposes actions so you can call them outside of the app instance.

One way to get current state is to have an action that just returns state. So like:

```js
appState: () => (state) => ({ ...state });
```

In V2, the middleware approach would mean that we can do stuff before or after (unclear which point as of yet - but V2 source is up on a branch)

Otherwise this is an interesting question 🙏

**Comment by dmitrykurmanov** [comment]
This is an experimental repo with treeview based on hyperapp: https://github.com/dmitrykurmanov/hypertree
It has several problems, main of them is *How to call event after the action?* (the [code](https://github.com/dmitrykurmanov/hypertree/blob/master/src/actions.js#L12))

I will try to change hyperapp to v2 and leave feedback asap.

**Comment by zaceno** [comment]
@dmitrykurmanov 

The way (currently) to dispatch an event bar after an action foo (which sets state), is to rename foo to _foo, and then make another foo-action where you: first call actions._foo(),  then dispatchEvent(“bar”)

In v2 you can (if I understand correctly) have an “effect” which dispatches bar-events, and the new syntax will probably allow you to chain an effect after an action without requiring a secondary action.

... but I haven’t really understood effects so I’m not 100% sure this use case will be simplified by them.

**Comment by dmitrykurmanov** [comment]
@zaceno we will see, I don't totally understand hyperapp v2 too. But I hope 😌

**Comment by jorgebucaran** [comment]
@dmitrykurmanov AMA! 😄

Feel free to open all the issues you want with specific V2 questions and I'll do my best to answer them.

**Comment by dmitrykurmanov** [comment]
I've tried hyperapp2 and I think that subscribe don't allow us to call something after the dom update, because it calls before the patch https://github.com/hyperapp/hyperapp/blob/2b3d85625321038ed2369ddb4ecc320a9e20984e/src/index.js#L576-L582

@jorgebucaran What is the correct way to do it? `Dispatch`?

**Comment by jorgebucaran** [comment]
@dmitrykurmanov Two questions:

1. What is the correct way of doing what exactly?
2. What were/are you trying to do?

**Comment by dmitrykurmanov** [comment]
@jorgebucaran 
1. Call some function after the action (after the dom update)
2. For now it is just interest. I am trying to create widget based on hyperapp. And I want to add listener ouside of hyperapp app that is calling every time when hyperapp state updated. Like the subscribe, but _after_ patch the DOM.

**Comment by jorgebucaran** [comment]
@dmitrykurmanov Maybe we can change exactly when subscriptions are updated in the code, but as a rule of thumb, subscriptions and DOM updates are completely unrelated business and neither should interfere or influence the other.

**Comment by dmitrykurmanov** [comment]
@jorgebucaran, ok I understand. I will also try to play with effects. May be this is what I need. Thank you. Anyway I think that now I understand hyperapp better.

**Comment by dmitrykurmanov** [comment]
@jorgebucaran I've created an example with the treeview component based on hyperapp.v1. 
http://plnkr.co/edit/LXrlHj0DNeKe86s76sGA?p=preview.

**Comment by dmitrykurmanov** [comment]
@jorgebucaran 

> So, this is what you had in mind.

yes 👍 

> Everything looks great until you start using the component via imperative method calls like addActionHandler and changeTitle.

Yes, that's why I asked about the internal `dispatch` export.

> In V2 (also in V1) you can create and share a tree-view-like component, but it should be used declaratively, within other Hyperapp apps and not like a jQuery widget.

The main idea is creating universal component (not only for jQuery or Hyperapp). I will create a few examples for Hyperapp, React, Vue and jQuery. And I'll post links to them here. 

I'm better at creating examples than writing in English 😆

**Comment by dmitrykurmanov** [comment]
@jorgebucaran here an example of declarative using [hypertree](https://github.com/dmitrykurmanov/hypertree) in hyperapp : https://github.com/dmitrykurmanov/hypertree-hyperapp/blob/master/src/index.js

For now `components/HyperTree.js`  in the src folder but in the future in will be come from the npm as dependency.

PS to see example in action, please clone the repo and run `npm i` and then `npm start`

**Comment by dmitrykurmanov** [comment]
@jorgebucaran  Here an example with vuejs: https://github.com/dmitrykurmanov/hypertree-vue

_As for examples for React and jQuery I think we don't need it to demonstrate the universal component based on Hyperapp. In React we get practiacally the same example as hyperapp. And Jquery example will be  almost the same as plnkr example above._

That's what I meant by the universal component, based on Hyperapp.
