### ISSUE TITLE
V2 class/className attribute API

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/hyperapp#754]
## Summary

I find myself using [classcat](https://github.com/jorgebucaran/classcat) quite often when I want to add or remove a class to/from a DOM element. The idea of conditionally adding classes in a declarative style suits the nature of the VDOM well.

With V2 I want to introduce the ability to toggle element classes on and off through the `class` attribute. This means that in addition to a string, you will be able to use an object or array for this attribute.

The behavior will be adapted from [classcat](https://github.com/jorgebucaran/classcat) specifically for Hyperapp. Classcat will continue to exist as an independent package which can be used with other frameworks or as a standalone library.

### `class` as a string

```jsx
import { h } from "hyperapp"

export const HoverButton = state => (
  <button
    class={`btn ${state.isPressed ? "btnPressed" : ""} ${
      !state.isPressed && state.isHovered ? "btnOver" : ""
    }`}
  >
    {state.label}
  </button>
)
```

### `class` as an object

```jsx
import { h } from "hyperapp"

export const HoverButton = state => (
  <button
    class={{
      btn: true,
      btnPressed: state.isPressed,
      btnOver: !state.isPressed && state.isHovered
    }}
  >
    {state.label}
  </button>
)
```

### `class` as an array

```jsx
import { h } from "hyperapp"

export const HoverButton = state => (
  <button
    class={[
      "btn",
      {
        btnPressed: state.isPressed,
        btnOver: !state.isPressed && state.isHovered
      }
    ]}
  >
    {state.label}
  </button>
)
```

## Prior Art
- [elm-lang/html/2.0.0/Html-Attributes#classList](https://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Attributes#classList)
- [JedWatson/classnames](https://github.com/JedWatson/classnames)
- [jorgebucaran/classcat](https://github.com/jorgebucaran/classcat)

---

👋 Do you think you'll find this useful? Do you have any ideas for improvements? What else would you like to see?

**Comment by SkaterDad** [comment]
I'd find this very handy to have built in.

Most of my CSS lately is with utility libs like Tailwind, and manually building up the class combinations is tedious.  I should probably use classcat, but sometimes laziness wins! 

I assume regular strings will still be useable also?

**Comment by jorgebucaran** [comment]
> I assume regular strings will still be useable also?

Yup. You can a string, an array or an object. See above, I added more examples.

**Comment by tetradice** [comment]
Great! This is exactly the function to be built-in 👏

**Comment by okwolf** [comment]
I misread the title to mean [JavaScript classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) and was briefly like: 🤯

**Comment by jonaskuske** [comment]
Oh, I love this feature in Vue!
Might be reason enough to upgrade my hyperapp v1.x site to V2 after all 🎉

**Comment by frenzzy** [comment]
Since classes concatenation feature is not always necessary and useless for css-in-js approaches which usually calculate a single class name in runtime, I am worried about performance impact.

Browser's DOM contains [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) style data structure besides `className`. Could we also consider to add special `classList` prop which will work with arrays?

What about composable components, will you need to use something like `classcat` anyway to make/use third-party reusable components?

**Comment by jorgebucaran** [comment]
@frenzzy Adding a `classList` attribute is a reasonable request. Would you also like to keep the `style` attribute string only and add a new `styleObject` instead? If avoidable, I'd rather _not_. Using `class` as an array or object in addition to a string, is a powerful feature as we can derive from classcat / classnames downloads per month.

> **Note**: Because this change only affects the `class` attribute, you'd be able to use `className` for applying a single class name. But you shouldn't rely on this implementation detail an always use the Hyperapp's canonical `class` attribute regardless of what you are doing.

## Let's measure that

We don't want to optimize prematurely, so let's ask the real question here, what/which is faster?

>**<https://jsperf.com/classlist-vs-classname-test>**
<img width="866" alt="screen shot 2018-09-03 at 8 11 23" src="https://user-images.githubusercontent.com/56996/44961755-43d45200-af51-11e8-8fbb-41b58c66565b.png">

The results indicate that className vs V2 className are virtually the same and that classList is the slowest.

**Comment by jonaskuske** [comment]
@jorgebucaran  

Hmm, so if I write a component that always adds its own classes but is also supposed to accept classes via props, I'd have to do
```javascript
const Component = props => {
  const { class: classProp } = props;
  let className;

  if (Array.isArray(classProp)) {
    className = [...classProp, 'predefined classes'];
  } else {
  className = [classProp, 'predefined classes'];
  }

  return (
    <somemarkup class={className} />
  );
};
```

Or will hyperapp always flatten the Array so can wrap the received `class` prop in an Array and add your styles to it no matter its type?

**Comment by jorgebucaran** [comment]
@jonaskuske 👍Arrays will be recursively flattened. 

```jsx
<div class={[[["foo", ["bar", ["baz", [{ bam: true }]]]]]]}>Hello</div> 
```
will give you this.
```html
<div class="foo bar baz">Hello</div>
```

**Comment by frenzzy** [comment]
Almost no effect on performance and super easy classes extension..
```js
const Button = (props) => <button {...props} class={['material-ui-btn', props.class]} />
```
💯 😍

**Comment by TheNando** [comment]
Do these get rendered inline or do they compile to a stylesheet with generated classes?

**Comment by SkaterDad** [comment]
@TheNando This topic is just about the class list, not inline styles.

Inline styles get attached to the DOM node properties.

**Comment by jorgebucaran** [comment]
> @TheNando ...compile to a stylesheet with generated classes

Nope, just added to the className property.

**Comment by jorgebucaran** [comment]
@frenzzy Interesting. Thanks for letting me know. 

I'm locking as I don't want to keep discussing this. I've made up my mind about it already.
