### ISSUE TITLE
"Real World" example implementation?

### ISSUE THREAD

**Issue by aadrian** [jorgebucaran/hyperapp#761]
Is there any "Real World" example implementation for Hyperapp as a frontend?
https://github.com/gothinkster/realworld

I cond't find any, and there's none listed there either :( .

Thank you.

**Comment by jorgebucaran** [comment]
👋 Hi @aadrian. I haven't implemented one myself, but I remember seeing at least _two_ being shared in Slack in the past month.

I was able to find one of them by @kwasniew here https://github.com/kwasniew/hyperapp-realworld-example-app.

**Comment by kwasniew** [comment]
There's a pending issue in the realworld codebase: https://github.com/gothinkster/realworld/issues/257

**Comment by Swizz** [comment]
Thinking about this, should I archive mine [Swizz/hyperapp-realworld-example-app](https://github.com/Swizz/hyperapp-realworld-example-app) ? :thinking:

**Comment by jorgebucaran** [comment]
@Swizz That's up to you. Consider at least adding a note to the README indicating that it's a work in progress or something along those lines.

**Comment by aadrian** [comment]
@jorgebucaran IMHO if hyperapp is really that used https://twitter.com/JorgeBucaran/status/1041130992424038400

Than one of the official implementations should be there listed: https://github.com/gothinkster/realworld and the community should be able vote for it :) .

**Comment by Swizz** [comment]
@aadrian As posted by @kwasniew some comments ago. 
There is a pending issue here https://github.com/gothinkster/realworld/issues/257

**Comment by aadrian** [comment]
@Swizz might be also be helpful if the example wouldn't have JS errors in the console: https://github.com/kwasniew/hyperapp-realworld-example-app/issues/1

**Comment by jorgebucaran** [comment]
@aadrian There is no official implementation, so how could one of the official implementations be listed there? I haven't built one because, unfortunately, I don't have time. 

I am interested in gothinkster/realworld and I'd love to see Hyperapp listed in it, but an official implementation will have to wait until #726 is merged and V2 has been released. 

In the meantime, feel free to help out @kwasniew, or build one yourself.

**Comment by aadrian** [comment]
> There is no official implementation, so how could one of the official implementations be listed there? 

You just declare one as the "official" :) . The community votes for it, to get a higher visibility there on that site too.

**Comment by jorgebucaran** [comment]
kwasniew/hyperapp-realworld is great, but I can't declare it as the official one (yet) for a few reasons:

- It's in V1 and I want to draw attention to V2, not V1
- It uses lenses instead of V1 slice feature
    - I can understand that lenses are more powerful whatever V1 provides out of the box for updating deeply nested state, but it's a missed opportunity to use a built-in feature
