### ISSUE TITLE
Async Action does not update

### ISSUE THREAD

**Issue by urbanhop** [jorgebucaran/hyperapp#768]
Async actions do not work. I believe the example in the doc is wrong:

    const actions = {
      upLater: () => async (state, actions) => {
        await new Promise(done => setTimeout(done, 1000))
        actions.up(10)  ///<<<< why should this change state?
      },
      up: value => state => ({ count: state.count + value })
    }

How could the call to an action *ignoring its return value*, update the global state?

**Comment by frenzzy** [comment]
Using [ESLint no-shadow](https://eslint.org/docs/rules/no-shadow) rule allows to prevent such situations in the future.

**Comment by urbanhop** [comment]
compliments on + thx for hyperapp. i'm in ;-)
