### ISSUE TITLE
Conditional side effects in v2

### ISSUE THREAD

**Issue by fuzetsu** [jorgebucaran/hyperapp#770]
Currently writing the following will throw `Uncaught TypeError: obj[1].effect is not a function` when `state.condition` evaluates to false.

```js
const Action = state => [
  { ...state, foo: 'bar' },
  state.condition && Effect()
]
```
This is because the following line of code does not check if obj[1] has a value before invoking `effect` on it.
https://github.com/jorgebucaran/hyperapp/blob/V2/src/index.js#L573

It is easy to write a wrapper to handle this scenario, but I feel like this might be a common enough use case of effects to warrant handling it.

**Comment by fuzetsu** [comment]
True, let's collect the necessary data then :)

My scenario was an action that would increment the page index and conditionally trigger an effect that would fetch more pages based on whether you were approaching the end of the available pages.
```js
const NextPost = state => [
  { ...state,  pageIndex: state.pageIndex + 1 },
  state.pageIndex + 5 > state.pages.length && LoadMorePages(state.search, state.lastPage)
]
```

Of course I could write it as:
```js
const NextPost = state => {
	const newState = { ...state, pageIndex: state.pageIndex + 1 }
	return state.pageIndex + 5 > states.pages.length
		? [newState, LoadMore(state.search, state.lastPage)]
		: newState
}
```

But I feel like the first syntax is nicer and it would be very easy to handle in core with minimal impact to performance or functionality (hopefully). 

I'm curious if you can think of any downsides?

The only thing I've thought of so far is that it could take longer to realize that an effect is not working because it's not returning an object, instead of just getting an error right away.

**Comment by SkaterDad** [comment]
It might be worth adding a `typeof` check to `obj[1]` to prevent runtime errors, since this style of JS seems to common.

I personally prefer to write the ternary, since you explicitly define the `true` and `false` cases.

**Comment by SkaterDad** [comment]
Since @jorgebucaran recently added effect batching into the V2 code, I was doing some testing with conditional effects.

Here is a pattern I just tried out which works well:
```js
function MyAction(state) {
  return [
    { ...state, updated: true }, // Updated state
    [Effect1, { prop1: true } ], // Always needed effect
    state.shouldRunEffect2 && [Effect2, {}] // Conditional
  ].filter(Boolean) // <-- Remove the conditional effects before Hyperapp sees it!
}
```

An alternative approach is to replace the optional effect with a NoOp function.  I don't like this as much, but some folks may like it.
```js
function MyAction(state) {
  return [
    { ...state, updated: true }, // Updated state
    [Effect1, { prop1: true } ], // Always needed effect
    state.shouldRunEffect2 ? [Effect2, {}] : [NoOp] // Conditional
  ]
}

function NoOp() {}
```

**Comment by jorgebucaran** [comment]
@SkaterDad BTW you may write `[MyEffect] instead of `[MyEffect, {}]`.

**Comment by jorgebucaran** [comment]
We can close here now that conditional and batched effects are implemented.

1. Conditional effects

```js
const anAction = state => [state, state.foo && anEffect(state.bar)]
```

2. Batched effects

```js
const anAction = state => [state, anEffect(state.bar), anotherEffect(state.baz)]
```
