### ISSUE TITLE
How to pass the state to multiple components?

### ISSUE THREAD

**Issue by lolo32** [jorgebucaran/hyperapp#771]
Hi,

I want to split the view in different file, but how to pass the state to these component?

```javascript
// Note, do not use this code like this, it does not do what it will be

import {app, h} from "hyperapp"

// Component that returns a string
const Component = () => (state) =>
	h("div", null, [
		state.id && h("div", null, ["OK"]),
		!state.id && h("div", null, ["KO"])
	])

// Component2 that cannot use the state
const Component2 = (state) =>
	h("div", null, [
		state.id && h("div", null, ["OK"]), // Error, state.id not defined
		!state.id && h("div", null, ["KO"]) // Error, state.id not defined
	])

app({
	container: document.body,
	init: {id: true},
	view: (state) => 
		h("div", null, [
			h(Component),
			h(Component2)
		])
})
```

**Comment by jorgebucaran** [comment]
@lolo32 I think this is what you want.

```jsx
// Component that returns a string
const Component = state => ...

// Component2 that cannot use the state
const Component2 = state => ...
app({
  container: document.body,
  init: { id: true },
  view: state => h("div", null, [h(Component(state)), h(Component2(state))])
})
```

As you can see, we're just calling the component function, passing the state we received in the view.

**Comment by zaceno** [comment]
What @jorgebucaran said 😄 

But why not simply:

```jsx
import {app, h} from "hyperapp"

const Component = props =>
	h("div", null, [
		props.id && h("div", null, ["OK"]),
		!props.id && h("div", null, ["KO"])
	])

app({
	container: document.body,
	init: {id: true},
	view: (state) => 
		h("div", null, [
			h(Component, state),
		])
})
```

**Comment by jorgebucaran** [comment]
@lolo32 I've renamed the title of your issue to more closely match what I think it is you are asking. 

Please let me know if I'm mistaken.

**Comment by lolo32** [comment]
@jorgebucaran the solution that you provided does not work.
I have an error :

- `InvalidCharacterError: String contains an invalid character` with Firefox 
- `Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.` with Chrome.

In fact, the error is from this extract code from HA2
```javascript
var createElement = function(node, lifecycle, eventProxy, isSvg) {
  var element =
    node.type === TEXT_NODE
      ? document.createTextNode(node.name)
      : (isSvg = isSvg || node.name === "svg")
        ? document.createElementNS(SVG_NS, node.name)
        : document.createElement(node.name)
...
```
`node.name` is an object, returned by the `h` function

@zaceno Your solution works, but it modify the `state` object, adding `children` property to the `state`.

**Comment by zaceno** [comment]
@lolo32 
> Your solution works, but it modify the state object, adding children property to the state.

That is not correct. The state can only be modified by actions. What I'm doing is I'm using the fact that you can *pass props to components*. Since the `Component` needs the `id`  value in the state, I pass that value as a *property* named `id` to the component. I *get* the value from the state, in the view.

Here, this works just as well:

 ```js

import {app, h} from "hyperapp"

const Component = ({reverse}) =>
	h("div", null, [ h("div", null, [ reverse ? "KO" : "OK"]) ])

app({
	container: document.body,
	init: {id: true},
	view: (state) => 
		h("div", null, [
			h(Component, {reverse: !state.id}),
		])
})
```

make sense?

**Comment by jorgebucaran** [comment]
@lolo32 My code was incomplete, my bad.

```jsx
// Component that returns a string
const Component = state => props =>...

// Component2 that cannot use the state
const Component2 = state => props => ...
app({
  container: document.body,
  init: { id: true },
  view: state => h("div", null, [h(Component(state)), h(Component2(state))])
})
```

Now, that should work. Please let me know if that fixes your issue.

**Comment by lolo32** [comment]
Thank you @jorgebucaran and @zaceno , both solutions are working. It's up to me to use my prefered

**Comment by jorgebucaran** [comment]
@lolo32 Yes, that's right. 

Glad to know you got everything working. 👋
