### ISSUE TITLE
How to handle shared objects?

### ISSUE THREAD

**Issue by akva** [jorgebucaran/hyperapp#778]
I am learning hyperapp and I ran into an issue of shared objects. That is objects that are referenced from multiple places in the global state. Here is an example: https://jsfiddle.net/81xqudvh/8/ . Sorry, it's a little bigger than strictly necessary to demonstrate the issue, but I wanted to make it somewhat realistic. If you click '+'/'-' buttons, it will update the score of the currently selected item in the detail pane view, but not, obviously, in the list view. I was wondering what is the common practice to deal with this sort of situations.

Thanks.

P.S. `wireStateToActions` seems to turn `selected: null` into `selected: {}`

**Comment by okwolf** [comment]
You're duplicating state for one of the `state.items` into `state.selected`. Consider storing only a unique identifier for the selected item and then using a single source of truth for the values. It's also a bit odd to have the `inc` action under the `selected` slice, which is a feature that will be removed in the next version anyway.

**Comment by akva** [comment]
> Consider storing only a unique identifier for the selected item and then using a single source of truth for the values.

I thought about this too. It would definitely work in a simple scenario like this one. I wonder how would it scale to a more complicated scenarios where one object can be a member of multiple collections. I could of course always dedicate one of the collections to be the source of truth (might not be obvious which one) and then use ids everywhere else. Then instead of writing `book.author` I would write `authors[book.author_id]`. Well, that looks quite unconventional and I guess this is not how most js code is written. 

I realize this issue is not specific to hyperapp but seems to be inherent to immutability in general. In a mutable world one would simply mutate selected item in place and all views would magically update. Just to demonstrate that it works (although I know it's cheating): https://jsfiddle.net/dwq5zr48/

**Comment by dunhamsteve** [comment]
You might find the redux discussion of normalization interesting: https://redux.js.org/recipes/structuringreducers/normalizingstateshape  
If I'm reading you right, it is close to what you're describing .  

My toy app that I'm playing around with in hyperapp2 takes that to a bit of an extreme and just has an uuid -> object map at the top level. (And it's queuing up misses and fetching them from the server.)

**Comment by akva** [comment]
Thanks for the link. Nice write up. It is indeed very close to what I'm describing. It does solve my original problem, but it leads to new problems. Let me elaborate. Let's take as an example the very page we are having our conversation on - github's issue page. We have a list of comments with the respective authors in the middle; on the right panel we have a list of all participants. In the spirit of the normalized state we might model it like this (I am simplifying it a bit compared to the redux post)

```
state = {
  users: {
    u1: {id: 'u1', name: '...'},
    u2: {id: 'u2', name: '...'},
  },
  comments: {
    c1: {author: 'u2', content: '...'},
    c2: {author: 'u1', content: '...'},
    c3: {author: 'u2', content: '...'}
  },
  ui: {
    comments: ['c1', 'c2']  // order of comments in the main panel
    participants: ['u1', 'u2']
  }
}
```

Now, for example, if I "update" the `name` of `u1` both of these paths will see the new value:
```
state.users[state.ui.participants[0]].name
state.users[state.comments[state.ui.comments[1]].author].name
```
So that's fine. However now we have another problem. Since `ui.comments` and `ui.participants` references will not have changed the respective memoized views (and I assume the views to be memoized as this is one of the major benefits of immutable state) will not know they have to re-render. Of course this could be solved by forgoing view memoization, but then it's not very clear why we shouldn't just mutate user object in place.

I am curious how you go about it in your toy app?

**Comment by dunhamsteve** [comment]
For my app, I'm just running the full view function, with no laziness. In my case, it's fast enough that it's not a problem. My `view` method is running in 5-6ms, maybe 8ms for pages that are ~1300 elements, and for minor or no DOM changes `patch` is running in sub-millisecond time.  When it actually does have to write the entire DOM (e.g. when the initial chuck of records loads), it looks like it's still around 20ms for patch.

How other platforms approach this (I'm not an expert):

I think redux handles this by having you wrap your component with a "container" that has a function to pull the state you need from the store.  It then checks containers to see if it needs to rerender. (I don't know if it re-renders just the subtree or somehow marks stuff as dirty.)

Reagent seems to automatically wrap components with something that monitors your access to state ("atoms") and then updates those components when that state changes. My understanding is that you should use a cursor if you depend on something deeper in the state like `state.users.u1` or it will fire for every change to the state object. But even with those changes, I'm still getting better performance out of hyperapp.

**Comment by akva** [comment]
Thanks for sharing your experience. I basically do the same. No memoization. Creating virtual dom is so fast that I don't see why I should be bothered with memoized views. And it's not like it has to be recreated on every frame, 60fps. Only on user interactions, and users are idle most of the time. It also offers a very conceptually simple model - you can do whatever you want to your state, shared objects or not, and the `view` will make sure the gui is always consistent. 

But now I am wondering why should I be bothered with immutable state. What other advantages does it offer besides memoized views.

**Comment by jorgebucaran** [comment]
This issue has run its course. To see other benefits of memoization (laziness) see https://github.com/jorgebucaran/hyperapp/issues/721. 👋😄

**Comment by okwolf** [comment]
I would recommend putting what you currently have under `state.ui.comments` somewhere inside `state.comments` and likewise `state.ui.participants` under `state.users`.

That groups the related data together, and you would memoize on changes to either `state.comments` or `state.users` for the parts of the `view` that needed them.
