### ISSUE TITLE
Submit type declarations to @types

### ISSUE THREAD

**Issue by cmaas** [jorgebucaran/hyperapp#782]
The general repository for TypeScript declaration files is under @types (https://github.com/DefinitelyTyped/DefinitelyTyped). It'd be nice to have the declaration file for Hyperapp in this repo, so that everything in VSCode works automatically.

Right now, VSCode doesn't  find `hyperapp.d.ts` automatically, which results in the following error:

<img width="747" alt="bildschirmfoto 2018-11-22 um 11 41 39" src="https://user-images.githubusercontent.com/6094364/48897941-b87da500-ee4b-11e8-9f4a-635ad4b982fd.png">

To be honest, I absolutely have no clue how to tell VSCode/TypeScript that the declaration file is under `./node_modules/hyperapp/hyperapp.d.ts`.

So the alternative to submitting the declaration file to the @types repo would be: Please update the README and give instructions on how to use the declaration file properly (i. e. not simply copy&pasting it into my own code).

Edit: Hmm, it appears that the problem is on my side. I have a subfolder `client`, which has a separate `tsconfig.json` and for some reason, VSCode and TypeScript don't recognize the Hyperapp declaration file you provided. Have to investigate this further.

**Comment by frenzzy** [comment]
Probably you have to specify [`moduleResolution`](https://www.typescriptlang.org/docs/handbook/module-resolution.html) in your `tsconfig.json`:
```js
{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "h",
    "module": "commonjs" // or "moduleResolution": "Node"
  }
}
```

**Comment by cmaas** [comment]
`"moduleResolution": "node"` fixed it. Many many thanks. This was driving me nuts. So all fine, issue can be closed, because Hyperapp comes with `typings` key in `package.json` and TypeScript should be able to handle the declarations file. No need to publish to @types I guess (except maybe for discoverability reasons).

**Comment by jorgebucaran** [comment]
@cmaas Glad you were able to figure it out! 

Thanks, @frenzzy.
