### ISSUE TITLE
Conditional render

### ISSUE THREAD

**Issue by olegantonyan** [jorgebucaran/hyperapp#783]
I have a value in state and I'd like to render an appropriate component depending on this value. Like a route, but without a router. Is this possible?

**Comment by jorgebucaran** [comment]
@olegantonyan Yes, it's possible.

```jsx
state.someValue && <MyComponent value={someValue} />
```

Is that what you were looking for?

**Comment by zaceno** [comment]
Or perhaps:

```
{
   state.var === 'foo' ? <Foo ... />
   : state.var === 'bar' ? <Bar ... />
   : state.var === 'baz' ? <Baz ... /> 
   : <Default ... />
}
```

**Comment by frenzzy** [comment]
One more example:
```js
const Foo = (props, children) => <h1 {...props}>Foo {children}</h1>
const Bar = (props, children) => <h1 {...props}>Bar {children}</h1>

const state = { example: Foo }

const actions = {
  setValue: (value) => ({ example: value })
}

const view = (state, actions) => (
  <main>
    <state.example>Example</state.example>
    <button onclick={() => actions.setValue(Foo)}>Foo</button>
    <button onclick={() => actions.setValue(Bar)}>Bar</button>
  </main>
)

app(state, actions, view, container)
```
Demo: https://codepen.io/frenzzy/pen/OavPqa/left/?editors=0010

**Comment by zaceno** [comment]
Lots of ways! 🎉 😄

**Comment by olegantonyan** [comment]
Thanks guys!
One problem with the last example. It works only if I put all the components into index.js.
If I put them into separate files and import, then it gives an error:
`InvalidCharacterError: String contains an invalid character`

**Comment by jorgebucaran** [comment]
@olegantonyan That doesn't sound like an Hyperapp error, though. It may be something with your build system or how you are importing the files. Without code, we can only speculate.

Closing as solved.

**Comment by olegantonyan** [comment]
@zaceno  with this approach
```{
   state.var === 'foo' ? <Foo ... />
   : state.var === 'bar' ? <Bar ... />
   : state.var === 'baz' ? <Baz ... /> 
   : <Default ... />
}```
where to put this code? It's not valid jsx, so I cannot place this into view:
```
const view = (state, actions) => (
   state.var === 'foo' ? <Foo ... />
   : state.var === 'bar' ? <Bar ... />
   : state.var === 'baz' ? <Baz ... /> 
   : <Default ... />
)
```

**Comment by jorgebucaran** [comment]
@olegantonyan The following is valid JSX.

```jsx
const view = (state, actions) =>
  state.var === "foo" ? (
    <Foo />
  ) : state.var === "bar" ? (
    <Bar />
  ) : state.var === "baz" ? (
    <Baz />
  ) : (
    <Default />
  )
```

**Comment by olegantonyan** [comment]
Got it! Thanks

**Comment by selfup** [comment]
A much cleaner way and more performant would be to use a switch statement:

```js
const LoadComp = (val) => {
  switch (val) {
    case 'foo':
      return <Foo />;
    case 'bar':
      return <Bar />;
    default:
      return <Default />;
  }
}
```

then just call it in your JSX:

```js
<div>
  {LoadComp('foo')}
</div>
```

**Comment by olegantonyan** [comment]
Yeah, I switched from Parcel to Webpack and now it's ok. Not sure if it was a bug or my mistake. 
Switch looks much cleaner. Thank you @selfup

**Comment by selfup** [comment]
@olegantonyan glad you got it figured out! 🎉

**Comment by selfup** [comment]
Yea object mappings are useful as well 👍

**Comment by jorgebucaran** [comment]
Lots of ways, indeed! 😍

**Comment by Swizz** [comment]
The future is [`do expr`](https://github.com/tc39/proposal-do-expressions).

```jsx
return (
  <nav>
    <HomeButton />
    { do {
      if (loggedIn) { <LogoutButton /> } 
      else { <LoginButton /> }
    } }
  </nav>
)
```

**Comment by sergey-shpak** [comment]
@okwolf object mapping looks nice, but it's fair to mention it works only with primitive types
Object keys are converted to string by `toString()` method, as result using non-primitive values can lead to unexpected results, like (which always falls to last key value) :
```javasctipt
{
  '[object Object]': <Component1 />,
  '[object Object]': <Component2 />,
}['[object Object]']
```
