### ISSUE TITLE
Components and Fragments?

### ISSUE THREAD

**Issue by IngwiePhoenix** [jorgebucaran/hyperapp#785]
Hey!

I want to create an application, but React is _way_ too big (`react`+`react-dom` = >100kb) for my use. So I have been recommended to try out this project here, and I really like it so far! Simple, small - and, like, _really_ small! Pretty much what I wanted - there is even SSR.

Now, I am in fact going to leverage SSR where possible. I come from PHP (Yii1, Laravel) and honestly am not a big fan of sending megabytes of JavaScript to my client - so, I want to keep that as small as possible, hence I will render on the server where I possibly can. Thus, this feels more natural to me as well, obviously.

Since I use (TailwindCSS)[http://tailwindcss.com/], I am building a couple of components on the CSS side to get the styling right, but also would like to make those components as JavaScript files, so that I can easily create a menubar from JSX, for instance. Or make modals and pre-configure a11y to them. So I wondered, how I could properly make components?

Now, as I use JSX as sort-of a view engine on the server, I am not always going to need to really render a `div`. I may just want to construct a view within a controller and return that, and have it merged into my base layout. So I do not really need a wrapping element - which brings me to Fragments. Are there any plans for adding support for fragments to this project?

Thank you in advance!

Kind regards,
Ingwie

**Comment by jorgebucaran** [comment]
> Are there any plans for adding support for fragments to this project?

Do you mean `Fragment` / `<>` support? Yes, I intend to, but I plan to release V2 (https://github.com/jorgebucaran/hyperapp/pull/726) first. FYI you can return an array of vnodes from a Hyperapp component, so there's already some support.

**Comment by IngwiePhoenix** [comment]
Oh that would help a lot! Could you provide me a short example?

I have a hierarchical namespace structure - and I want to put my components into `UI/Components` and have the app itself start from `UI/index.js`. Each subdirectory of `Components` contains a folder, holding a component's logic and style (which is used in the SCSS build, so it doesn't matter here). So let's say I have `UI/Components/Modal` that would be used like this:

```js
import {Modal, ModalButtons} from "UI/Components/Modal";
// ...
<button>Trigger modal</button>
<Modal title="Hello" type="info">
  This is the modal body.
  <ModalButtons>
    <button>OK</button>
  </ModalButtons>
</Modal>
```

Obviously, this is a conceptual component - but basically I want to use this from my app every here and there. So how would I go about returning that? If I thought this in `Fragments` i would wrap this in `<>...</>`. So how do I do that with what you suggested?

Sorry for asking such an elaborate question, but I am new to Hyperapp :)

**Comment by frenzzy** [comment]
```js
return [<button />, <Modal />]
```
or
```js
const Fragment = (props, children) => children
return <Fragment><button /><Modal /></Fragment>
```
or
```js
const Fragment = (props, children) => children // and pragmaFrag=Fragment in .babelrc
return <><button /><Modal /></>
```
See #596

**Comment by jorgebucaran** [comment]
Same as https://github.com/jorgebucaran/hyperapp/issues/530. 👋
