### ISSUE TITLE
Sample code could not build with TypeScript 3.2.2.

### ISSUE THREAD

**Issue by naoki-tomita** [jorgebucaran/hyperapp#788]
I created typescript project.
And I copied sample code rewriting with typescript 3.2.2.
[This is sample code](https://github.com/naoki-tomita/hyper-sample/blob/master/index.tsx)

But, I encountered a type error.

> JSX element type 'VNode<Attributes> | View<State, Actions>' is not a constructor function for JSX elements.
> Type 'View<State, Actions>' is missing the following properties from type 'Element': nodeName, children, key [2605]

This error will disappear if use TypeScript 3.1.4.
So, I think it need to fix `.d.ts` file.
Like [this](https://github.com/naoki-tomita/hyperapp/pull/1/files).
Are there plans to fix it?

**Comment by jorgebucaran** [comment]
I'm happy to work with anyone interested in adding typings to Hyperapp, but for now, I need to focus on shipping V2.
