### ISSUE TITLE
Add support to destroy app instance bound to DOM.

### ISSUE THREAD

**Issue by wanton7** [jorgebucaran/hyperapp#789]
We are trying to embed hyperapp into our company's old jQuery based application and I've hit a wall. I tested different kind of rendering libraries that don't need pipeline like Webpack and just using `<script>` is enough. What's missing is way to `destroy` hyperapp`app` instance. Ex. Vue.js has `vm.$destroy()`.

We sometimes destroy existing HTML, like using Ajax to load HTML from server and replacing old HTML with jQuery. We also also use jQuery UI's `remove` event to clean up everything properly when old HTML is replaced and it had components made with jQuery. We like to replace these components progressively using hyperapp but could not find anything like `vm.$destroy()` in Vue.js or `ReactDOM.unmountComponentAtNode()` in React to destroy hyperapp `app` instances properly.

**Comment by wanton7** [comment]
@jorgebucaran yes that's exactly what I need! Component might have registered itself to some external service or maybe it's wrapping some jQuery/JavaScript component so having hyperapp call those remove/destroy lifecycle events is what I need. I also need the call  to be synchronous, so after it returns everything has been destroyed/unmounted.

**Comment by wanton7** [comment]
@jorgebucaran By synchronous I mean that hyperapp itself won't do any unnecessary `setTimout` stuff or something similar.  If developer can create asynchronous remove and destroy events then it's up to them to make sure everything critical is removed synchronously when these lifecycle events is called.

**Comment by wanton7** [comment]
I've been thinking about this and it would better to add new life cycle event maybe called `onunmount` in form of (element: Element) => void. Because when unmount/destroy app you might to handle things differently. Like you wouldn't use effects to fade out etc. because you know everything in view is going to be destroyed.

**Comment by jorgebucaran** [comment]
@wanton7 Sounds like the existing [`ondestroy`](https://github.com/jorgebucaran/hyperapp#ondestroy), which is not meant to be confused with [`onremove`](https://github.com/jorgebucaran/hyperapp#onremove). Were you aware of those?

**Comment by wanton7** [comment]
@jorgebucaran `ondestroy` is called after element is removed from DOM, so it won't usually work for me. `onremove` would work if there was an extra boolean parameter like `(element, done, unmount) =>`.  Having that `unmount` patameter for both `onremove` and `ondestroy` would do nicely..

**Comment by jorgebucaran** [comment]
Hey @wanton7. I think what you want is what's described in jorgebucaran/superfine#136 and not lifecycle events at all. It's my fault for bringing them up.

I talked about lifecycle events because your https://github.com/jorgebucaran/hyperapp/issues/789#issuecomment-448029532 reminded me of them.

Also for the record: `ondestroy` is the counterpart of `oncreate`. It is called on every element so you can free resources allocated in `oncreate`. This is how global subscriptions are implemented in V1. 

`onremove` is used to delay the removal of an element, e.g. for creating animations.

**Comment by jorgebucaran** [comment]
Tracking in #863.
