### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by jagdishjadeja** [jorgebucaran/hyperapp#790]
https://codepen.io/jorgebucaran/pen/zNxZLP this example given in  README.md is not working

**Comment by jorgebucaran** [comment]
@jagdishjadeja The example in the README is working fine. 

![2018-12-19 20 53 13](https://user-images.githubusercontent.com/56996/50218719-36dc5100-03d0-11e9-9acf-403ee5fdb7cd.gif)

**Comment by jorgebucaran** [comment]
@jagdishjadeja The example in CodePen uses `disabled={state.count <= 0}` to demonstrate setting attributes declaratively, the example in the README doesn't. 

I'll make it the same. Thanks! 💯
