### ISSUE TITLE
How is the v2 progress?

### ISSUE THREAD

**Issue by owcc** [jorgebucaran/hyperapp#791]
I really like this framework, especially the v2 improvements.I'm looking forward to start new project with v2. 

Thanks for this great job and Happy new years!

**Comment by ThobyV** [comment]
Happy new year from here too. I Just feel there's a need to appreciate and commend the Devs/Contributors of Hyperapp for such an awesome project.

Hyperapp literally changed how I viewed Frontend Engineering and that humbles me alot.

Thank you for such open, amazing technology @Jorgebucaran and all contribution team. Hope to see V2 out in the wild soon!

**Comment by okwolf** [comment]
As someone wiser than me once wrote:
> [Hyperapp is one of those bizarre compromises that somehow manages to actually be good instead of mediocre at everything.](https://twitter.com/okwolf/status/961506418049343489)

It's so minimal that it should be useless, and yet it includes just enough awesome that you can build great things with it.

**Comment by jorgebucaran** [comment]
V2 is coming along well. `V2` is now the default branch of this repository, so you only have to look at the README to see how we're coming along. 👋:smile:
