### ISSUE TITLE
Exporting createElement

### ISSUE THREAD

**Issue by apla** [jorgebucaran/hyperapp#793]
I have a web app which preloads image and video information before hiding splash screen. So far I created DOM elements for `video` and `img` like this:

```js
	const el = this.el = document.createElement('video');
	el.addEventListener('loadeddata', this.onVideoLoad.bind(this), false);
	el.addEventListener('abort', this.onVideoAbort.bind(this), false);
	el.addEventListener('loadedmetadata', this.onVideoMeta.bind (this), false);
	el.setAttribute('preload', 'metadata');
	el.setAttribute('muted', 'true');
	el.setAttribute('playsinline', 'true');
	this.config.sources.forEach(source => {
		const srcEl = document.createElement('source');
		srcEl.src = patchLocalVideo(source.url);
		srcEl.type = source.type;
		el.appendChild(srcEl);
	});
```

and within the app code looks like this:

```js
               <video
                   style={{width: '100%'}}
                    onloadeddata={onVideoLoadedData}
                    onended={onVideoEnded}
                    onupdate={onVideoTagUpdate}
                    repeat="1"
                    autoplay="true"
                    muted="true"
                    playsinline="true"
                    preload="metadata"
                    video-should-play={screenIsActive}
                    
                    src={widget.data.el.currentSrc}
                ></video>
```

If I can use `createElement`, code will look uniform.

I prefer not to add preloader's elements to DOM.

I know at least one additional use case: checks for real width of the text elements without adding those elements to DOM.

I understand that function cannot be exported just as is — createElement [adding lifecycle callback](https://github.com/jorgebucaran/hyperapp/blob/master/src/index.js#L228) when `oncreate` attribute is present and updateAttribute [relies upon app's callbacks](https://github.com/jorgebucaran/hyperapp/blob/master/src/index.js#L189)

**Comment by jorgebucaran** [comment]
@apla Did you try using that inside a Hyperapp view? We already export `hyperapp.h`, so we don't need to export `createElement`.

**Comment by mrozbarry** [comment]
You should be able to pre-load without rendering to the page. You might want to check out [mdn's page on MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) for videos. Images are more straight forward:

```
const preloadImage = (source) => {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = (err) => rejectr(err);
    image.src = source;
  });
};

const preloadCollection = (sources, onSuccess, onFail) => {
  return Promise.all(sources.map(preloadImage))
    .then(onSuccess)
    .catch(onFail);
}

// For V1

const actions = app({ actions: { /* have imagePreloadSuccess/Fail here */ } });

preloadCollection(
  ['image1.png', image2.png'],
  actions.imagePreloadSuccess,
  actions.imagePreloadFail,
);

// For V2

const PreloadEffect = (props, dispatch) => {
  return preloadCollection(
    props.images,
    () => dispatch(props.onSuccess),
    () => dispatch(props.onFailure),
  );
}

const PreloadImages = (images, onSuccess, onFailure) => [PreloadEffect, { images, onSuccess, onFailure }];

app({
  init: [initialState, PreloadImages(['image1.png', image2.png'], imagePreloadSuccessAction, imagePreloadFailureAction)],
  // ...
});
```

The MediaSource variation shouldn't be _that_ different. Once the browser has loaded the media metadata, it should keep that cached for when you create a video tag. You could also grab a reference to the element in v1 using lifecycle hooks, or with a mutation observer subscription in v2 - with that dom reference, you can set the MediaStream and Sources directly from the preloaded values.
