### ISSUE TITLE
what is it? isSvg = isSvg

### ISSUE THREAD

**Issue by uxitten** [jorgebucaran/hyperapp#794]
<img width="455" alt="screen shot 2019-01-13 at 11 16 55 pm" src="https://user-images.githubusercontent.com/1549069/51089894-87ee2380-1789-11e9-97eb-820c4ec94f5f.png">

and

<img width="334" alt="screen shot 2019-01-13 at 11 17 16 pm" src="https://user-images.githubusercontent.com/1549069/51089901-8cb2d780-1789-11e9-8613-156f0dc9b55d.png">

i think this code is enough:
```javascript
(isSvg || node.nodeName === "svg")
```

**Comment by jaeh** [comment]
if i am reading this correctly the isSvg var gets used below this lines and hence needs to be set.
(isSvg || node.nodeName === "svg") would make isSvg stay falsy, which is not what we expect later on,
to get around this we would need to repeat this OR condition everywhere we now just reference isSvg.

**Comment by jorgebucaran** [comment]
@uxitten We need to set `isSvg` to call `createElement` recursively and later when calling `updateAttribute`. Basically what @jaeh said (thanks by the way).

https://github.com/jorgebucaran/hyperapp/blob/61addd8d1ce1436b8c8d601e010cfb89dbd3eae2/src/index.js#L218-L243
