### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by dishuostec** [jorgebucaran/hyperapp#796]
How to reproduce:
1. open [codepen](https://codepen.io/anon/pen/EGqKRw)
2. click "to state 1", then click "asyncChange", then click "to state 4" twice before node 2 disappear

**Comment by jorgebucaran** [comment]
@dishuostec Reproduced. Looks like a bug. Anyone else seen something like this before?

**Comment by SkaterDad** [comment]
I've seen a similar error with the V2 branch, and work around it by adding keys.

**Comment by jorgebucaran** [comment]
@dishuostec With lifecycle events now out of V2, there's no way to run your demo, but if you find a way to reproduce the problem in V2, please reopen. 👋
