### ISSUE TITLE
Defining CSS classes inside Hyperapp Components - V2?

### ISSUE THREAD

**Issue by B-Teague** [jorgebucaran/hyperapp#797]
What is the best way to add css classes to html \<head\> from within a Hyperapp component?
Would this be a new V2 feature?

Since the behavior, content and visuals of a component are all tightly coupled, I would like to define my css classes inside my components and add them to the document at most once when the component is included.

I do not want to use styles on a component that is repeated potentially hundreds of times which can be very CPU expensive, and I don't want to define my classes in a separate .css file.

See createCSSSelector:
[How to dynamically create CSS class in JavaScript and apply?](https://stackoverflow.com/questions/1720320/how-to-dynamically-create-css-class-in-javascript-and-apply)

```
const {h} = require('hyperapp')
import cc from 'classcat'

/*
how to get hyperapp to add these classes to the HTML <head> at most once?
const classes = {
  todoItem: {
    "color": "black",
    "font-size": "6em",
    "margin": "0",
    "padding": "20px 0px"
  },
  done: {
    "text-decoration": "line-through"
  }
}
*/

const toggle = (state, {id, done}) => {
  return { ...state, 
   todos: state.todos.map(
      (todo)=> (todo.id === id ? {...todo, done: !done} : {...todo})                                      
    ) 
  }
}

const TodoItem = ({id, value, done}) => {
  return <div class={cc({todoItem: true, done: done})} onclick={[toggle, {id, done}]}>{value}</div>
}

export default TodoItem

```

**Comment by jorgebucaran** [comment]
@B-Teague What about using one of those CSS-in-JS libraries?

**Comment by B-Teague** [comment]
So, after researching several options, I have settled on picostyle.  Emotion was a close second.  However, I am having trouble getting picostyle to work with Hyperapp V2.

[Hyperapp V2 with JSX and Picostyle](https://glitch.com/edit/#!/teague-hyperapp-v2-jsx)

**Comment by B-Teague** [comment]
I figured out how to use picostyle correctly with Hyperapp V2.  You can close this issue.

**Comment by jorgebucaran** [comment]
@B-Teague Sounds good. 

Don't know if you are still interested, but have you heard about [Linaria](https://linaria.now.sh/). Looks nice too.

**Comment by zaceno** [comment]
@jorgebucaran Wow Linaria looks really great. Shame it doesn’t seem to work with parcel...
