### ISSUE TITLE
oncreate broken in V2?

### ISSUE THREAD

**Issue by B-Teague** [jorgebucaran/hyperapp#804]
Is oncreate broken in V2?
Here is oncreate writing to Console with V1 in index.jsx from the \<li\> element:
[Hyperapp V1 oncreate](https://glitch.com/edit/#!/teague-hyperapp-v1-jsx)

Same project using V2, but Console is never written:
[Hyperapp V2 oncreate](https://glitch.com/edit/#!/teague-hyperapp-v2-oncreate)

Am I doing something wrong?

**Comment by SkaterDad** [comment]
In V2, the lifecycle methods were camel-cased, so try `onCreate` instead.  I can't recall the exact reason this was done, but it's definitely something people should look out for when upgrading.

https://github.com/jorgebucaran/hyperapp/blob/e9d67578cfbe34fda7c78d12de951ee5ed175848/src/index.js#L106

**Comment by B-Teague** [comment]
Yup, camel case was the problem.
Definitely hope to see this as a "Gotcha" in the "upgrading to V2 documentation".
