### ISSUE TITLE
Using reactive streaming library

### ISSUE THREAD

**Issue by janat08** [jorgebucaran/hyperapp#808]
I'm not terribly experienced in paradigm, therefore I'm not sure how intrusive or effective integration of these libraries will be (mostjs/xstreamjs). Implementation wise they will likely start in subscription and end with action call. There's dysfunctional stuff that I never had to face nor can really imagine like circular dependencies thanks to onionify (state library of cyclejs), which I worry will not go over well.

**Comment by jorgebucaran** [comment]
@janat08 There's nothing like streams in V1, but there are no restrictions to what you can do inside an action (or event handler). As long as you eventually call an action to update the state you should be able to use your favorite reactive library in V1 or do whatever you want.

V2 will have subscriptions. That's the closest to streams in this new paradigm. Just like the VDOM is a declarative layer to the imperative DOM API, subscriptions are a declarative layer for [handling global events](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers) like window events and custom event streams such as clock ticks, geolocation changes, and WebSockets in the browser.

Subscriptions represent event streams whose lifecycle is determined by changes in your program state and expressed with arrays.

```js
export const subscriptions = state => [
  state.isIntro || state.isLost || state.isWon
    ? MouseClicks(startGame)
    : state.isInPlay && [
        AnimationFrame(tick),
        KeyDowns(keyPressed),
        KeyUps(move)
      ]
]
```

Like the view, your `subscriptions` function will be called for every state change. So, if a new subscription appears in the array, we'll start the subscription. When a subscription leaves the array, we'll cancel it. If any of its properties change, we'll restart it.
