### ISSUE TITLE
what's this line of code meaning?

### ISSUE THREAD

**Issue by Paleless** [jorgebucaran/hyperapp#815]
l was reading the source code and l found "isSvg = isSvg" at line 218.
l feel confused and l want to what' its meaning?

**Comment by jorgebucaran** [comment]
@Paleless `isSvg` is an argument to `createElement`. In this line we try to set `isSvg` to `true` if `node.nodeName` is `"svg"` unless `isSvg` is already true, which is the case when creating elements under an `<svg>` parent.

https://github.com/jorgebucaran/hyperapp/blob/61addd8d1ce1436b8c8d601e010cfb89dbd3eae2/src/index.js#L218

**Comment by Paleless** [comment]
got it, thanks @jorgebucaran
