### ISSUE TITLE
Checkbox broken in v2 alpha

### ISSUE THREAD

**Issue by zaceno** [jorgebucaran/hyperapp#816]
It seems that setting `checked: state.someBoolValue` has no effect on the checkedness of the checkbox. 

https://codepen.io/zaceno/pen/pYdPod?editors=0010

**Comment by SkaterDad** [comment]
@zaceno It works okay if you remove the `preventDefault()`.

**Comment by zaceno** [comment]
huh, well look at that! You're right @SkaterDad . I could have sworn I tried it without too. Also... why would that even make a difference?  Seems like a strange implementation of preventDefault() in browsers.

Anyhow... Case closed! Thanks!
