### ISSUE TITLE
Hyperapp#v2 Synthetic Events

### ISSUE THREAD

**Issue by sergey-shpak** [jorgebucaran/hyperapp#817]
```jsx

import { app, h, eventDispatcher } from 'hyperapp'
import SyntheticEvents from 'synthetic-events-hub'

app({
  init: {},
  view: state => <div>Synthetic Events</div>,
  subscriptions: state => [
    SyntheticEvents({
      listen: ['mouse','key', 'touch'],
      dispatcher: eventDispatcher
    })
  ],
  container: document.body
})

```
Is it even possible?

**Comment by jorgebucaran** [comment]
Hyperapp already wraps event handlers, that's why they can return a new state or a [state, effect] tuple. We don't impose restrictions on how you implement subscriptions either. You should be able to wrap DOM global events like `mousemove`, `keydown`, and so on using the Subscription API.

**Comment by mrozbarry** [comment]
@jorgebucaran I had a discussion with [sshpak on slack around this PR](https://hyperapp.slack.com/archives/C42RQKF8E/p1552765730136700), which might give you more details and context.

**Comment by sergey-shpak** [comment]
@mrozbarry thanks, discussion briefly:
> SyntheticEvent, a cross-browser wrapper around the browser’s native event. It has the same interface as the browser’s native event, including stopPropagation() and preventDefault(), except the events work identically across all browsers [More](https://reactjs.org/docs/events.html)

To implement synthetic events hub for hyperapp we need to expose `eventDispatcher` (possibly simplify hyperapp core events proxy?), to trigger vdom events.

Benefits of synthetic events:
- performance (event delegation - all events handled by one node (document))
- cross browser/device events implementation

**Comment by jorgebucaran** [comment]
@sergey-shpak Send me a PR with the changes if you want and I'll have a look, but I don't plan to discuss this anymore.
