### ISSUE TITLE
js.org Source Annotations Website

### ISSUE THREAD

**Issue by mrozbarry** [jorgebucaran/hyperapp#819]
See [slack conversation here](https://hyperapp.slack.com/archives/C41ECC0V6/p1553165862002900)

I think we have full buy-in from @jorgebucaran on having the hyperapp source code annotated for the https://hyperapp.js.org site, so I think we should explore creating this annotated source code.

It's important that we do this for both V1 and V2, since there are many V1 sites alive in the wild that may not be upgraded.

**Comment by mrozbarry** [comment]
**note:** Made this a follow-up comment on my own experimentation, since I don't think this is necessarily the way we'll proceed.

I experimented with [docco](https://github.com/jashkenas/docco) on the hyperapp V2 branch, with [really good success](http://idiotic-brush.surge.sh/).

Docco works by parsing comments in the source code as markdown, and generates static html pages. This could work really well as a travis build step that re-builds the documentation and publishes every PR merge.

I think we could write an annotated header that contains:

```markdown
# Hyperapp

[twitter]() [github]() [slack]() _should be the same as the README.md header links_

    LICENSE INFORMATION HERE

**Note:** This is the documentation for version 2.x. If you're looking for 1.x documentation, [click here](/1.x).

...annotated source goes here
```

I think that gives maximum information while keeping in the realm of docco. Docco does support custom templates, but it's not well documented - a custom template may make it easier for us to have a proper header with links, rather than abusing the annotation section.

**Comment by okwolf** [comment]
Could you please post a repo or a gist with the source of your Docco experiment?

Would the plan be to include the annotations in the original source file or maintain it as a separate entity?

**Comment by mrozbarry** [comment]
Yeah, I'll push my branch up once I'm at my computer.  The simple version is the comments are inlined in the hyperapp.js source code, and looks something like this:

```js
// # Hyperapp

// ## Utilities

// Roughly corresponds to [dom nodeType](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType). Constants provided here for cross-platform compatibility
var DEFAULT_NODE = 0
var RECYCLED_NODE = 1
var LAZY_NODE = 2
var TEXT_NODE = 3
var EMPTY_OBJECT = {}
var EMPTY_ARRAY = []

var map = EMPTY_ARRAY.map
var isArray = Array.isArray

// Using a promise here (when available) ensures that rendering happens on the next available tick.
// This should prevent updates from locking the javascript thread.
var defer =
  typeof Promise === "function"
    ? function(cb) {
        Promise.resolve().then(cb)
      }
    : setTimeout

// While `Object.assign` may be a good replacement for our `merge` function,
// [mdn’s compatability table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility) demonstrates that this may require polyfills.
var merge = function(a, b) {
  var out = {}

  for (var i in a) out[i] = a[i]
  for (var i in b) out[i] = b[i]

  return out
}

// `Array.prototype.flat` will be a good replacement candidate once there’s [better browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat).
var flatten = function(arr) {
  return arr.reduce(function(out, obj) {
    return out.concat(
      !obj || obj === true
        ? false
        : typeof obj[0] === "function"
        ? [obj]
        : flatten(obj)
    )
  }, EMPTY_ARRAY)
}
```

**Comment by okwolf** [comment]
[Here](https://gist.github.com/jorgebucaran/8dc33b7947f3193eb2ea3d5700e27036) are some notes @jorgebucaran already made about v1 for reference.

**Comment by jorgebucaran** [comment]
I love the idea of a future website with just links, documentation derived from GitHub's README, and Hyperapp's annotated source. Docco seems nice, but it does require adding comments to Hyperapp's source code, am I right?

**Comment by okwolf** [comment]
@jorgebucaran I believe the comments would need to be added to either the original source or copies that are maintained for documentation purposes. Obviously it would be easier to keep the annotated source in sync with the original source of truth if they were combined, but I'm not sure if you'd be willing to accept that. It's an ongoing maintenance cost either way.

**Comment by mrozbarry** [comment]
Just a bump to mention PR #820 .

**Comment by mrozbarry** [comment]
@jorgebucaran yeah, we would need to add/maintain comments. I'm not completely convinced this is awful as long as the comments are meaningful for hard-to-read pieces of code.

As a start, we could really just comment with headers for different groups of functions (ie Utilities, Subscriptions, VDom, Runtime).

**Comment by jorgebucaran** [comment]
Going with https://hyperapp.dev.
