### ISSUE TITLE
Wouldn't work with plugins code in documentation -> corrected below

### ISSUE THREAD

**Issue by burnsvaughan** [jorgebucaran/hyperapp#821]
the .babelrc file should have the following for the transform react jsx plugin, not @babel that is in the current documentation. Took me a while to find but got the answer.

}
  "plugins": [["babel-plugin-transform-react-jsx", { "pragma": "h" }]]
}

**Comment by jorgebucaran** [comment]
@burnsvaughan Why?

**Comment by jorgebucaran** [comment]
It seems to works with babel 7. Maybe you were using babel 6 or older.

- Demo: https://hyperapp-calculator-example.glitch.me
- Source: https://glitch.com/~hyperapp-calculator-example
