### ISSUE TITLE
TypeScript Parameterized Views

### ISSUE THREAD

**Issue by aminnairi** [jorgebucaran/hyperapp#823]
Hi there,

I was wondering that maybe there could be a TypeScript definition for ParameterizedView (like I liked to called this one).

So the following is working and defined in the `hyperapp.d.ts`.

```tsx
export const MaterializeComponent: View<State, Actions> = (state, actions) => (
    <div class='component-class' onclick={actions.clicked}>{state.title}</div>
);
```

And this one has no type definitions.

```tsx
export const MaterializeComponent: View<State, Actions> = (properties, children) => (state, actions) => (
    <div class={properties.class} onclick={actions.clicked} title={state.title}>{children}</div>
);
```

So I ended up doing my own implementation and it is working:

```tsx
import { h, View, Children } from 'hyperapp'
import { State } from '../state';
import { Actions } from '../actions';

interface ParameterizedView<State, Actions> {
    (properties: object, children: Children): View<State, Actions>
}

export const MaterializeComponent: ParameterizedView<State, Actions> = (properties, children) => (state, actions) => (
    <div class={properties.class} onclick={actions.clicked} title={state.title}>{children}</div>
);
```

I'm no TypeScript guru nor a confirmed TS developper but there is room for enhancement for this one. And who knows, maybe the next hyperapp type defininition file could include this one interface? What do you guys think?

**Comment by jorgebucaran** [comment]
@aminnairi I'd prefer if you create a PR in the V2 branch with the type definitions and move the discussion there, rather than this issue. 🙏

**Comment by aminnairi** [comment]
@jorgebucaran You are right. I'm gonna create a PR then. Thanks for guiding me!
