### ISSUE TITLE
[Release] Styled-Components for Hyperapp is here (2.1kb gzipped)

### ISSUE THREAD

**Issue by SilentCicero** [jorgebucaran/hyperapp#824]
Hey all,

I've made a little port of Styled-Components version 1 for Hyperapp. You can use it right now hot off the presses. I've actually been using this for a long time, I just never published it.. sorry :( It follows the original styled-components interface / api design.

Tests are coming, but if you want to write tests for me that would be super helpful. I have fallen in love with hyperapp, I use it all the time and everywhere. V1 is solid.

Not sure if someone did a version of this for Styled-Components already, but mine is special in that it's also super tiny (2.1ish gzipped, maybe a little heavier)

Github:
https://github.com/SilentCicero/hyperapp-styled-components

NPM:
```
import styled from 'hyperapp-styled-components`;

const MyButton = styled.button`
     color: red;
`;
```

Best, SilentCicero

**Comment by selfup** [comment]
Been waiting for something like this! That's great! :tada:

**Comment by jorgebucaran** [comment]
@SilentCicero Thanks for sharing! If you send me a PR to [hyperapp/awesome](https://github.com/hyperapp/awesome) I'll merge it in a heartbeat.
