### ISSUE TITLE
Merge subsequent text nodes into one

### ISSUE THREAD

**Issue by gyopiazza** [jorgebucaran/hyperapp#825]
Hello! When doing some **server-side rendering** experiments (using the **v2 alpha** and **hyperapp-render**) I've noticed that – on hydration – text nodes trigger an unnecessary render when containing interpolated strings. 

In my example the children become `['Title: ', 'Some Title', '!']` instead of `['Title: Some Title!']` and a new `createTextVNode()` is created for each array item. This is probably caused by bundling the `h()` pragma which results in a diff mismatch that triggers the unnecessary render:

`return Object(hyperapp__WEBPACK_IMPORTED_MODULE_0__[\"h\"])(\"h3\", null, \"Title: \", props.title,  \"!\")`

I applied a patch to the while() loop of the h() function: instead of creating a text node for each word it combines the previous and the current, if they are both text nodes. This is also like browsers render HTML by default, by combining text nodes when they are siblings. Also React seems to do something similar because the text nodes are kept together and no extra render is done during hydration.

Patched version:
```js
while (rest.length > 0) {
    var previousNode = children[children.length-1]
    if (isArray((node = rest.pop()))) {
      for (i = node.length; i-- > 0; ) rest.push(node[i])
    } else if (node === false || node === true || node == null) {
    } else if (typeof node === 'string' && previousNode && previousNode.type === 3) {
      previousNode.name += node
    } else {
      children.push(typeof node === "object" ? node : createTextVNode(node))
    }
  }
```

Current version:
```js
while (rest.length > 0) {
    if (isArray((node = rest.pop()))) {
      for (i = node.length; i-- > 0; ) rest.push(node[i])
    } else if (node === false || node === true || node == null) {
    } else {
      children.push(typeof node === "object" ? node : createTextVNode(node))
    }
  }
```

Here is an online demo with a MutationObserver listener to show that the DOM is being recreated even though the server-side and the client-side HTML are the same:
https://hyperapp-ssr-demo.glitch.me/

Please let me know if this issue is caused by the bundler (webpack) and/or the proposed patch makes sense (for which I could create a PR).

Thank you!

**Comment by SkaterDad** [comment]
This does sound like a good thing to fix.  Not sure if `h` or somewhere deeper would be best, though.

It looks like you're probably doing this: `<h1>Test {interpolated}</h1>`?

The JSX babel transform turns that into multiple children.  If you use es6 interpolated strings instead, you can get a single child.  [Here's an example on the Babel REPL.](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTACCsGcA8AIAsBQAbApgF1gNwIYCcBLHAIzVgF5YAiXQktKgbkUQDMBXAOwGN0CB7TtgKoA7gAoAlLADeiWLDwZ2eIQB4AJgSwA-eQtgBlfgFtUsdKmiZRBdPFg5ZtIqVQBfRakjtk6SLAEQia-fAAOZNzwBMgaSpwAdPpqwFq6iO4sHDx8grDEONwA1nzFkFKy-kroKuppegayAAYKAIJC3gBsgZyWeGH8yDiWGrCQ6IScAOawtvaOsAAkMi70Hl4-fgFBsILmUTEaADSOnKNhSpCoeFjesACe_Cqz0ZZhheYX_GHXyPcJCiamQUKXqGSAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2&prettier=false&targets=Node-8.4&version=7.4.3&externalPlugins=)

**Comment by jorgebucaran** [comment]
Oh, JSX, why do I keep supporting you? If you're using a compiler, you'd expect it to do something reasonable like turning all siblings into a single text child, not let all that work to the hyperscript processor. 

@gyopiazza Is this only present during hydration?

**Comment by gyopiazza** [comment]
@SkaterDad that's correct, the interpolated JSX strings become multiple text nodes. The backtick is a good workaround though.

@jorgebucaran I've added an onClick event to change the title in the example, the text nodes are still split after re-rendering. Probably because the bundled code has the h() with multiple arguments. I wonder if it's possible to configure the compiler to keep interpolated values as one argument – as it logically should – using `+` instead of `,`

On a side note, it took me a while to appreciate JSX – but – if we have to write HTML in JS then it's a good template processor compared to writing functions (at least for me).

**Comment by jorgebucaran** [comment]
> @gyopiazza In my example the children become ['Title: ', 'Some Title', '!'] instead of ['Title: Some Title!'] and a new createTextVNode() is created for each array item.

I understand this isn't ideal, but what's the problem? What's broken? 

What if we remove hydration and get rid of half of the problem? Just a terrible idea worth mentioning.

**Comment by gyopiazza** [comment]
>@jorgebucaran I understand this isn't ideal, but what's the problem? What's broken?

I think the compiler could do a better job at keeping the arguments as they are.

>What if we remove hydration and get rid of half of the problem? Just a terrible idea worth mentioning.
For me it's a very important feature, I hope you won't consider the idea 🙏🏼

**Comment by jorgebucaran** [comment]
@gyopiazza I agree, the compiler could do a better job! :)

**Comment by jorgebucaran** [comment]
@gyopiazza I agree, the compiler should do its job! This is a JSX-specific optimization beyond the scope of Hyperapp. That's why I asked you "what's broken?". It's a symbolic question. My point is (if my understanding is correct) nothing is actually broken, so why add bytes and make Hyperapp slow for the sake of JSX? 

> On a side note, it took me a while to appreciate JSX – but – if we have to write HTML in JS then it's a good template processor compared to writing functions (at least for me).

Yeah. JSX, despite being a PITA (because it's not standard JavaScript) is convenient for those familiar with HTML, which I assume are most people.

**Comment by gyopiazza** [comment]
@jorgebucaran those bytes were added to debug the issue and I thought to share them because it's a very little patch. I'll see if I can take a look at the babel plugin (but I'm going to have a much harder time lol).

**Comment by jorgebucaran** [comment]
> @gyopiazza I'm going to have a much harder time

Please share your findings, and consider creating an issue (or a PR 😬) in the [Babel](https://github.com/babel/babel/issues) repo to suggest adding this feature to the JSX compiler. IMO the JSX compiler should merge text nodes by default.

**Comment by SkaterDad** [comment]
> @jorgebucaran  IMO the JSX compiler should merge text nodes by default.

I think that'll be difficult or impossible, since the compiler doesn't typically know what type of value a variable or function will return.

An expression like this: `<h1>Static and {dynamic}</h1>` could do pretty much anything. `dynamic` could be a string, a VNode, an array, etc...

**Comment by jorgebucaran** [comment]
Hmm, I see! That makes sense @SkaterDad. 👍 

Okay, so I think the [latest](https://github.com/developit/preact/blob/master/src/create-element.js) Preact isn't doing anything, but if I parse this correctly, [8](https://github.com/developit/preact/blob/3aaa578270c0c6cd1fb7f5cf992737eec2934433/src/h.js#L62-L72) was? Inferno's [createElement](https://github.com/infernojs/inferno/blob/master/packages/inferno-create-element/src/index.ts) doesn't seem to care either. Am I looking at the wrong place?

**Comment by gyopiazza** [comment]
@SkaterDad @jorgebucaran I've been doing some more research because SkaterDad is right in that the compiler cannot know the value of a variable beforehand. I can't find exactly where and if the "text nodes" are merged in React. Now I'm thinking that instead of caring about merging the nodes, they (React, at least) do a diff that takes into account full text, independently of the amount of nodes.

This is just guesswork, I'll keep you updated if I find something else.

**Comment by jorgebucaran** [comment]
I'm not adding more responsibility to `h` for the time being.

**Comment by gyopiazza** [comment]
@jorgebucaran fair enough, I just want to notify @frenzzy that the components used for server side rendering should never do string concatenation the "standard JSX way":
```
const what = 'good'

const notGood = <h1>This is not {what}</h1>

const good = <h1>{`This is ${what}`}</h1>
```

**Comment by jorgebucaran** [comment]
> @gyopiazza I've noticed that – on hydration – text nodes trigger an unnecessary render when containing interpolated strings.

By the way, what do you mean by an unnecessary render? In Hyperapp terms, "to render" is when we update the DOM in response to state transitions. So, I don't know if you mean what I mean by render or something else since you were also discussing hydration here. Clarify, please? 🙏

**Comment by gyopiazza** [comment]
@jorgebucaran I might have misused the term "render", what I mean is that with interpolated strings inside components, the hydration doesn't recycle the existing nodes because their amount is different. For example:

```
const someH1 = props => <h1>An {props.interpolated} string</h1>
```

Gets compiled into **3 text nodes** instead of **just one** as expected when hydrating. This is due to how compilers split the parameters, in this case the "children" become `['An', props.interpolated, 'string']` (3 text nodes) instead of `['An' + props.interpolated + 'string']` (1 node).

Here is an example of what I mean, I've setup a mutation observer that logs the changes in the console and the hydration should not trigger any DOM update since the state is the same. The DOM update 
happens anyways because the compiled text nodes are different than what the hydration expects:
https://hyperapp-ssr-demo.glitch.me/

As suggested by @SkaterDad , the solution is to use template literals for strings interpolation:
```
const someH1 = props => <h1>{`An ${props.interpolated} string`}</h1>
```

**Comment by jorgebucaran** [comment]
@gyopiazza I see what you mean now. A different question. How important is this in the big scheme of things? Hyperapp is still reusing other existing DOM content like your `h3` in that example. Just curious.

**Comment by frenzzy** [comment]
Imagine you have the following JSX:
```jsx
<div>Foo{"Bar"}Baz</div>
```
Hyperapp V2 VDOM for this JSX may look like this:
```js
{ name: 'div', ..., children: [
  { name: 'Foo', ... },
  { name: 'Bar', ... },
  { name: 'Baz', ... }
] }
```
**The problem:**
If we return from the server the following html:
```html
<div>FooBarBaz</div>
```
Browsers converts this markup to the following DOM:
```
<div>
  "FooBarBaz"
</div>
```
It will be hydrated as:
```js
{ name: 'div', ..., children: [
  { name: 'FooBarBaz', ... }
] }
```
Hyperapp compares hydrated vdom with jsx vdom and sees that children are different and updates all the content of the `div` element.
**The solution:**
Render such JSX to the following html markup (React.js does that):
```html
<div>Foo<-- -->Bar<-- -->Baz</div>
```
Then browser will convert such markup to the following DOM:
```
<div>
  "Foo"     // node.nodeType = TEXT_NODE 3
  "<-- -->" // node.nodeType = COMMENT_NODE 8
  "Bar"     // node.nodeType = TEXT_NODE 3
  "<-- -->" // node.nodeType = COMMENT_NODE 8
  "Baz"     // node.nodeType = TEXT_NODE 3
</div>
```
And if fix [Hyperapp hydration algorithm](https://github.com/jorgebucaran/hyperapp/blob/b5c3cc57e673edbb6029013b2bc9cfa29322c8a7/src/index.js#L374-L385) to skip comment nodes, hydrated VDOM may look exactly the same which turned out from JSX:
```js
{ name: 'div', ..., children: [
  { name: 'Foo', ... },
  { name: 'Bar', ... },
  { name: 'Baz', ... }
] }
```
This means hyperapp will not patch DOM on startup. Profit!

**Comment by jorgebucaran** [comment]
Thank you, @frenzzy. I understand what happens behind the scenes; my question is how essential hydrating adjacent text nodes in the big scheme of things is?

We do not want to throw away SSR content and re-create all the DOM nodes, that's why we try to recycle as much DOM as we can, but text nodes are cheaper to patch/create than HTML elements. In the big scheme of things, how much profit do we get from this PR? The proposed changes to `h` introduce logic that will run for every node when recalculating the virtual DOM, not only on startup but whenever the state changes.

**Comment by gyopiazza** [comment]
@jorgebucaran I completely agree with your performance concerns. On the other hand repainting text nodes might add some time-to-interactive delay, probably even more than the overhead caused by the PR (we could also adjust it to only run once && if a state is provided). It 's also perfectly reasonable to keep everything as it is because the issue only happens when hydrating (and we could simply suggest to concatenate strings and variables within template literals to avoid DOM updates).

**Comment by jorgebucaran** [comment]
> @gyopiazza On the other hand repainting text nodes might add some time-to-interactive delay

We need a demo to confirm that. If you have time for that one of these days and you'd like to scratch that itch, make one and show us your results please (no pressure, though, at your leisure)! 🙏
