### ISSUE TITLE
`onupdate` cause infinity rerendering 

### ISSUE THREAD

**Issue by 11111000000** [jorgebucaran/hyperapp#827]
![2019-04-19-135334_1366x768_scrot](https://user-images.githubusercontent.com/977130/56409220-a8f37280-62aa-11e9-9397-f9756fea1c11.png)

... and very hot cpu:

![2019-04-19-135414_1366x768_scrot](https://user-images.githubusercontent.com/977130/56409221-a8f37280-62aa-11e9-9c8a-02618828d1d7.png)

    "hyperapp": "^1.2.9"

**Comment by jorgebucaran** [comment]
@11111000000 Without looking at your code, I can only speculate. It's likely that you are dispatching an action inside the `onupdate` handler, causing the view to re-render. When the DOM is updated, Hyperapp will invoke `onupdate` again creating an infinite loop. The solution is not using actions inside `onupdate` or not using `onupdate` at all.

Hyperapp V2 doesn't have lifecycle events, so this won't be an issue going forward.

**Comment by 11111000000** [comment]
@jorgebucaran  all actions is simple as:
```
  oncreate: () =>
    state =>
    ({ shown: true }),
  
  onupdate: () => true, /* TOFIX: https://github.com/jorgebucaran/hyperapp/issues/827 */
  
  onremove: () => true,
  
  ondestroy: () => true
```

**Comment by 11111000000** [comment]
When I change it to 
`onupdate: () => () => ({})` it fired infinitly too, but slowly.
`onupdate: () => () => true` cause infinity loop
`onupdate: () => () => false` works as expected
`onupdate: () => false` works too
 
what I need to return to simply do nothing, and how to guarantied avoid this leak in future?

**Comment by frenzzy** [comment]
You have to return anything (`undefined`, `null`, `false`, `0`) which will go to `else` case [here](https://github.com/jorgebucaran/hyperapp/blob/1.2.9/src/index.js#L124-L128):

https://github.com/jorgebucaran/hyperapp/blob/bb0d38c2028a20d84e8038bec729a4f22d208648/src/index.js#L124-L128
