### ISSUE TITLE
Found error when running any hyperapp

### ISSUE THREAD

**Issue by dickyj** [jorgebucaran/hyperapp#828]
Hi,
When I try to install any hyperapp, I keep getting this error and a blank page, any clues why?
Seems to be the subscriptions code.
![Screenshot (13)](https://user-images.githubusercontent.com/6478334/56409534-2075d180-62ac-11e9-9679-2268bc2e299c.png)

**Comment by okwolf** [comment]
Based on the error, it looks like you're returning a non-array from your `subscriptions`. It would be easier to tell if you could share your code in a pen or a repo.

**Comment by dickyj** [comment]
This is the code that I am running:
https://github.com/loteoo/hyperapp-todolist

**Comment by dickyj** [comment]
This is the specific line in the code:
subscriptions: state => window.localStorage.setItem('hyperapp-todolist', JSON.stringify(state))

setItem will return undefined. What would be the fix then?

**Comment by infinnie** [comment]
```js
subscriptions: state => {
    window.localStorage.setItem('hyperapp-todolist', JSON.stringify(state));
    return state;
}

**Comment by jorgebucaran** [comment]
@dickyj That's not how subscriptions work at all! :)

Until there's proper documentation for this feature, see https://github.com/jorgebucaran/hyperapp/issues/752. 👋
