### ISSUE TITLE
Consolidate default and custom payload into one payload

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/hyperapp#830]
Let's start with a quick recap to make sure we're all on the same page.

1. An action can take a default payload.

```jsx
const Change = (state, event) => ({ ...state, value: event.target.value })

// ...

<input type="text" value={state.value} oninput={Change} />
```

2. An action can take a custom payload.

```jsx
const Remove = (state, { id }) => ({ /* ... */ })

// ...

<button onclick={[Remove, { id: item.id }]} />
```

3. Sometimes you need both a custom and the default payload. What happens to the default payload if an action takes a custom payload? The default payload shifts one position to the right!

```jsx
const UpdateItem = (state, { id }, event) => ({
  ...state,
  items: state.items.map(item =>
    item.id === id
      ? {
          ...item,
          value: event.target.value
        }
      : item
  )
})

// ...

<input
  type="text"
  value={state.value}
  oninput={[UpdateItem, { id: todo.id }]}
/>
```

Wouldn't be better if default and custom payloads were only one payload? The other day, I wanted to wrap an action and noticed I needed a conditional inside the wrapper function to determine if the action was called with or without a custom payload since that affects how the action is dispatched. The fact that the action signature changes depending on how you use it can be difficult to understand at first. Destructuring the event object inside an action is awkward too. I'd rather define actions that take a value and not think about events at all.

I found a way to solve all the above by consolidating both payloads into a one payload.

Here's the generalized action signature before and after the proposed changes.

```jsx
// Before
const anAction = (state, [customPayload,] defaultPayload) => newState
```

```jsx
// After
const anAction = (state, payload) => newState
```

Let's see how it works.

- Without a custom payload, the action takes the default payload precisely as described in case (1).
- With a custom payload, the action takes the custom payload precisely as described in case (2).

What about case (3)? How to consolidate the default and custom payload into one as promised? 

```jsx
<input
  type="text"
  value={state.value}
  oninput={[UpdateItem, event => ({ id: todo.id, value: event.target.value })]}
/>
```

Notice this allows you to create a custom payload with the `event.target.value` instead of `event`, so we can write our action this way:

```jsx
const UpdateItem = (state, { id, value }) => ({
  ...state,
  items: state.items.map(item => (item.id === id ? { ...item, value } : item))
})
```

The ability to create a custom payload can also be useful when you need to use the payload multiple times. Destructing can help, in fact:

```jsx
const NewSrcCurrency = (state, { target: { value } }) =>
  newCurrency({
    ...state,
    srcCurrency: value,
    tgtCurrency:
      state.tgtCurrency === value ? state.srcCurrency : state.tgtCurrency
  })
```

...but it's always simpler and more generic to write an action this way:

```jsx
const NewSrcCurrency = (state, value) =>
  newCurrency({
    ...state,
    srcCurrency: value,
    tgtCurrency:
      state.tgtCurrency === value ? state.srcCurrency : state.tgtCurrency
  })
```

I haven't decided what to call the payload function yet. Decoders? Getters? All suggestions are welcome. I already rewrote a few example apps using this syntax, and I can see that reusing payload functions will be very common; for example, `e => e.target.value` will be commonplace. It makes a lot of sense to define the function separately, rather than inlining it when assigning the action to on-event handlers.

```jsx
const getValue = event => event.target.value
```

```jsx
<input type="text" value={state.value} oninput={[NewValue, getValue]} />
```

```jsx
<input
  type="text"
  value={item.value}
  oninput={[Update, event => ({ id: item.id, ...getValue(event) })]}
/>
```

That's it! 

## Summary

1. Default
```jsx
const MyAction = (state, event) => newState
...
onclick={MyAction}
```

2. Custom
```jsx
const MyAction = (state, { foo }) => newState
...
onclick={[MyAction, { foo: 42 }]}
```

3. Default+Custom
```jsx
const MyAction = (state, { foo, bar, baz }) => newState
...
onclick={[MyAction, e => ({ foo: 42, bar: 72, baz: e.target.value })]}
```

**Comment by SkaterDad** [comment]
I like it. Reminds me of elm's event handling and associated functions.  Definitely seems to encourage more reusable bits. 

https://package.elm-lang.org/packages/elm/html/latest/Html.Events#targetValue

They call those functions decoders, but that's a little weird for a JS lib.  Hmmm... Adapters, selectors, extractors...

**Comment by jorgebucaran** [comment]
I also briefly considered going back to event handlers like in V1:

```jsx
oninput={() => Change}
onsubmit={e => [Change, e.target.value]}
```

But that makes it impossible to do (1) and (2) exactly as I described in my post, which I strongly prefer. For example, you couldn't do this since every event handler would receive the event object first.

```jsx
×  oninput={Change}  
×  oninput={[Change, "foo"]}
```

By the way, this feature allows to call `preventDefault()` and `stopPropagation()` without going through an effect, but I'd still prefer an effect for that.

```jsx
onsubmit={[SubmitForm, e => e.preventDefault()]}
```

**Comment by diontools** [comment]
From the viewpoint of TypeScript.
The current Hyperapp V2 can not be type-safe because TypeScript can not pass the user-side State type to IntrinsicElements. If Hyperapp returns to an event handler like V1 and adds dispatch to the view, type-safe can be achieved.

```tsx
app<State>({
    view: (state, dispatch) => <input oninput={ev => dispatch(Change, ev.target.value)} />
})
```

It is verbose but effective. I am writing such a library [Typerapp](https://github.com/diontools/typerapp).

**Comment by jorgebucaran** [comment]
@diontools Did you read https://github.com/jorgebucaran/hyperapp/issues/830#issue-436385480 and have anything useful to say other than promote your library?  I'm just checking because I don't know if you're referring to the action signature in V2 before _or_ after this proposal.

**Comment by jorgebucaran** [comment]
@diontools Did you read https://github.com/jorgebucaran/hyperapp/issues/830#issue-436385480 and have anything useful to say other than promote your library? 😉  

I'm just checking because I don't know if you're referring to the action signature in V2 before or after this proposal. 

> @diontools The current Hyperapp V2 cannot be type-safe because TypeScript cannot pass the user-side State type to IntrinsicElements.

You definitely know TypeScript better than I do, but the solution is to write our own Html types! :)

**Comment by petejohanson** [comment]
Does creating the new arrow function each time to decode the event cause any problems with vdom diffing/equality checking and performance?

**Comment by SkaterDad** [comment]
> @jorgebucaran  You know TypeScript better than I do, but the solution is to write our own Html types! :)

Yep.  We're not exactly creating real DOM nodes anyway.  Fully type-safe code would be nice, but it's hardly a requirement for reliable software.

I strongly prefer the way things are right now, as opposed to adding `dispatch` to the views (like diontools showed), and having to pass that down the component tree.  Decoupling actions from the view is one of HA v2's best features.

> @petejohanson Does creating the new arrow function each time to decode the event cause any problems with vdom diffing/equality checking and performance?

I wouldn't expect it will have much impact on performance.  Since you're keeping the same event name (ex: `onclick`), hyperapp won't do anything drastic like `removeEventListener`/`addEventListener`.  There is a form of [event delegation](https://github.com/jorgebucaran/hyperapp/blob/16f6d0c40ca214fcbeedd91b602e7520bbe08b70/src/index.js#L431), so [the handler just gets updated in-place](https://github.com/jorgebucaran/hyperapp/blob/16f6d0c40ca214fcbeedd91b602e7520bbe08b70/src/index.js#L91).

Any seriously expensive component can be wrapped up in a `Lazy` component to optimize the diffing cost.

**Comment by petejohanson** [comment]
@SkaterDad Ah, I hadn't dug into the internals on events, the use of delegation makes sense to avoid performance problems. Thanks.

Other name ideas: Injectors? Adaptors/Adapters?

I definitely like this proposal as a whole. It definitely simplifies actions, and leads to more areas of re-use.

**Comment by jorgebucaran** [comment]
> @petejohanson Does creating the new arrow function each time to decode the event cause any problems with vdom diffing/equality checking and performance?

Basically what @SkaterDad said. 😄 

My take. Two questions in disguise here. 

1. Diffing/equality: No problems there. We don't look at actions until they're dispatched. You can even assign numbers or strings to on-event attributes and the state will be updated with that value when the event is fired.

2. Performance: There's undeniably a tiny performance hit when using a "decoder" (payload creator) function as it will be created from scratch every time we call the `view` function. I wouldn't worry about this. Most decoders can be declared separately, so there is no performance hit at all. They probably belong to an events utility library.

```jsx
const targetValue = e => e.target.value
const targetChecked = e. => e.target.checked
```

Decoders doing more things can also be declared separately, but they will create a new function anyway.

```jsx
const idNameAndValue = (id, name) => e => ({ id, name, value: e.target.value })

<select onchange={[UpdateSelect, idNameValue(item.id, item.name)]} .../>
```

**Comment by jorgebucaran** [comment]
@diontools You could start [here](https://github.com/diontools/typerapp/blob/f9e95b58e73bd5e8587bdc73a3733329293b9bf6/types/Html.d.ts#L216). DOM on-event handlers in Hyperapp are a facade for the action dispatching mechanism, not DOM event handlers as we usually know them.

**Comment by diontools** [comment]
@jorgebucaran 

Minimal hyperapp.d.ts to clarify the problem.

```typescript
export type Action<S, P = void> = (state: S, props: P) => S | [S, ...any[]];

export interface InputEvent extends Event {
    target: HTMLInputElement
}

declare global {
    namespace JSX {
        interface IntrinsicElements {
            input: {
                oninput?: Action<S, InputEvent> | [Action<S, P>, P] | [Action<S, P>, (ev: InputEvent) => P],
            };

            div: {};
        }
    }
}
```

I can not specify State type (S) and Props type (P) of Action to oninput property. It can be avoided by using generic functions, but it does not work well.

```typescript
oninput?: <S, P>(ev: InputEvent) => Action<S> | [Action<S, P>, P],
```

I need some ideas, but I couldn't find them.

**Comment by jorgebucaran** [comment]
@diontools You would need to throw away most of `IntrinsicElements` and rewrite it from scratch.

**Comment by jorgebucaran** [comment]
Implemented now in the new beta!
