### ISSUE TITLE
How To Reference An Element in V2

### ISSUE THREAD

**Issue by owcc** [jorgebucaran/hyperapp#832]
I follow this issue [How To Reference An Element](https://github.com/jorgebucaran/hyperapp/issues/12), but it can't be commit any more. so, how can I Ref to an element Dom since lifecycle has been removed in V2 ?

**Comment by okwolf** [comment]
You might want to read the [issue on replacing lifecycle events](https://github.com/jorgebucaran/hyperapp/issues/717#issue-337438224) for some inspiration.

**Comment by jorgebucaran** [comment]
@owcc You can get a reference to an arbitrary DOM node using `getElementById`, `querySelectorAll`, etc. In V2 there are valid reasons to do this; for example, giving focus to an element comes to mind. More often than not, there will be specialized libraries, so you don't have to write any effects by yourself, but it largely depends on what you are trying to do. 

Here's how you may give focus to an element.

```jsx
import { h, app } from "hyperapp"
import { focus } from "@hyperapp/dom"

app({
  // ...
  view: state => (
    <main>
      <input id="input" />
      <button onclick={[state, focus("input")]} />
    </main>
  ),
  node: document.getElementById("app")
})
```

The `focus` effect could be implemented as follows:

```jsx
const focusFx = id => document.getElementById(id).focus()
export const focus = id => [focusFx, id]
```

Keep in mind that `@hyperapp/dom` doesn't exist yet, so you'll have to implement your own effect anyway for now. And when `@hyperapp/dom` does exist the API may not be as shown above. I'm just giving you an idea. 

See also https://github.com/jorgebucaran/hyperapp/issues/717.

**Comment by okwolf** [comment]
This will work for small apps, but I think we will still need a better story as Hyperapps grow. For example, if you are implementing a UI widget library with reusable form controls that have custom focus behavior and there might be a dozen or more of them on the screen at once. You would either need to require users to specify a globally unique identifier (which could be tough if the source of the data is dynamic) for each input they include or generate such a thing (which would make the `view` impure).

This also applies to other use cases like [`play`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play)ing one video in a gallery, getting exact node [dimensions](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect), etc.

**Comment by jorgebucaran** [comment]
That sounds speculative to me. Feel free to come back with hard evidence when you build something.

**Comment by okwolf** [comment]
It's speculative in that I have yet to build a large Hyperapp. As much as I'm not a fan of refs, I have run across situations in larger [React](https://reactjs.org/docs/refs-and-the-dom.html) and [Vue](https://vuejs.org/v2/api/#ref) projects where they come in handy.

I would like to add that your approach does seem to be what [Elm suggests](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#focus).
