### ISSUE TITLE
Jest failing to import Hyperapp 2.0.0-beta2+

### ISSUE THREAD

**Issue by okwolf** [jorgebucaran/hyperapp#836]
This is because of the build outputting an [IIFE](https://github.com/jorgebucaran/hyperapp/commit/c6d17a4b5de51ec4853929cc0057d5b2c4ab0083) instead of UMD.

For more details and to repro see [this repo](https://github.com/okwolf/hyperapp-iffy).

**Comment by mrozbarry** [comment]
Verified on node 10.15.3 / npm 6.9.0.

**Comment by jorgebucaran** [comment]
Correct, I changed the output to IIFE.

**Comment by okwolf** [comment]
So does this mean that importing Hyperapp in Jest as a module is no longer a supported feature? This is a highly popular use case, one that I would like to at least find a workaround for.

**Comment by jorgebucaran** [comment]
@okwolf What about using node 12 with `--experimental-modules` or https://github.com/standard-things/esm?

**Comment by okwolf** [comment]
This was fixed in [`beta.13`](https://github.com/jorgebucaran/hyperapp/commit/12dade589516e83b48fb6796885172d5b8375384).
