### ISSUE TITLE
v2: automatically calling functions in component trees 

### ISSUE THREAD

**Issue by jaeh** [jorgebucaran/hyperapp#840]
in v1 i could do:
```
const component = () => OtherComponent
```
and it would execute my OtherComponent function with (state, actions) as arguments.

maybe v2 should call this function (maybe even with empty props object)?
```
OtherComponent({})
```

also, kinda related, there is no passing down full state to components anymore, is there?

**Comment by jorgebucaran** [comment]
@jaeh I think you're referring to what in the V1 documentation we used to call "lazy components". V2 has a different, unrelated feature called "lazy views" or just lazy, see #606. 

> also, kinda related, there is no passing down full state to components anymore, is there?

Correct. This is not in V2.

**Comment by jaeh** [comment]
hm, i am almost done with the rewrite, only one issue left:

i have the [Pre](https://github.com/magic-modules/pre/blob/master/src/index.mjs) module, which does syntax highlighting, and it has a gloal theme shared between all Pre's.

i used to set the global state.pre.theme value and access it in the Pre component without the user of the module declaring the state explicitly eg:
```
Pre('some_javascript_code()')
```
which i would expand internally to:
```
Pre({ content: 'some_code()', theme: state.pre.theme })
```

looking through the codebase i see no way to add a StateProvider component (pseudocode)
```
export const StateProvider = state => (node, props, children) => h(node, { ...state, ...props }, children)
```
(Without initializing it in app.render to get the state, which would be a pretty ugly hack)

but, looking at subscriptions code, i see that they get the state passed to 
```
batch(subscriptions(state))
```
am i correct that this would be my way to subscribe to state changes?

**Comment by jaeh** [comment]
actually, thinking about this a bit more,
i can write a StateProvider component in userland and pass the state to it in my view function. will try that now :)
