### ISSUE TITLE
bug for custom elements with children

### ISSUE THREAD

**Issue by zaceno** [jorgebucaran/hyperapp#842]
There seems to be a problem working with custom elements with children. See this example:

https://codepen.io/zaceno/pen/qGPxqL?editors=0010

Notice the console outputs errors when you try to change the text in the input field.

I am at a loss to explain it. For all I know, custom elements should be like any other node. Perhaps some particular accomodations need to be made if an element has a shadow dom?

**Comment by infinnie** [comment]
https://codepen.io/anon/pen/dEVrWM?editors=0010

So I tried to change the `my-p` to a simple `span`. The problem still occurs.

**Comment by infinnie** [comment]
Here the variable expected to be an element,
![image](https://user-images.githubusercontent.com/8168391/58076323-82439700-7bdc-11e9-963a-31136393313a.png)
is instead an event whose `children` is `undefined`.

**Comment by infinnie** [comment]
The correct `settext` function should be `const settext = (state, e) => ({ text: e.target.value })`

**Comment by zaceno** [comment]
Oh rats! 🤦🏻‍♂️ ...so embarrassed! Thanks @infinnie!
