### ISSUE TITLE
Update babel details in V2 docs

### ISSUE THREAD

**Issue by mrozbarry** [jorgebucaran/hyperapp#843]
Babel [recommends using babel.config.js](https://babeljs.io/docs/en/configuration) instead of `.babelrc`.

Our docs current say:

> Then, add the following configuration to your .babelrc file, creating one if you haven't already.
```json
{
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "h"
      }
    ]
  ]
}
```

We should update that to something like:

> Then, add the following configuration to your babel.config.js file, creating one if you haven't already.
```js
module.exports = function () {
  return {
    plugins: [
      [
        "@babel/plugin-transform-react-jsx",
        {
          pragma: "h"
        }
      ]
    ]
  }
}
```

**Comment by jorgebucaran** [comment]
@mrozbarry Why? did babel change? I am using that as my .babelrc with Parcel.

**Comment by mrozbarry** [comment]
At work, I've been upgrading some projects babel and jest dependencies, and ran into some problems where .babelrc wasn't being read.

That said, this is mostly because the babel team is recommending migration to `babel.config.js`. I don't think there's any immediate harm to using `.babelrc`, but I think the long term advice we should give is to use `babel.config.js`.

**Comment by jorgebucaran** [comment]
@mrozbarry Hmm, I see... 

Do you happen to know if babel supports ES modules by default?

```jsx
export default () => ({
  plugins: [
    [
      "@babel/plugin-transform-react-jsx",
      {
        pragma: "h"
      }
    ]
  ]
})

```

**Comment by jaeh** [comment]
just tested it,
babel ignores babel.config.js if it exports an es6 module :(

**Comment by jorgebucaran** [comment]
Alright, since Babel reads `.babelrc` fine, let's keep the documentation unchanged for now and revisit this later.

**Comment by mrozbarry** [comment]
Babel doesn't support an es module for config, but I don't think any other similar tool does either.

Yeah, this isn't a big deal for the immediate future, just thought it would be worth mentioning while I know a lot of thought is going into the README.
