### ISSUE TITLE
[Feature] hooks will comming?

### ISSUE THREAD

**Issue by cbbfcd** [jorgebucaran/hyperapp#846]
just like the title.
is there any plan to let hyperapp to support hyperapp/useState or others.
it's will be cool, i think.

**Comment by jorgebucaran** [comment]
@cbbfcd Hyperapp has effects and subscriptions instead. They vary in their approach but cover similar ground to React Hooks. The docs already have some coverage and will continue to expand as I can write them. 

In case you're new to the party, effects and subscriptions are a declarative, purely functional interface to side effects and event streams.

Related: #750, #752
