### ISSUE TITLE
Just a doubt regarding the inner workings of setState function

### ISSUE THREAD

**Issue by githingeorge** [jorgebucaran/hyperapp#847]
```javascript
var setState = function(newState) {
    if (state !== newState) {
      if (subscriptions) {
        subs = patchSubs(subs, batch([subscriptions(newState)]), dispatch)
      }
      if (!lock) defer(render, (lock = true))
    }
    return (state = newState)
  }
```
In the above code if you remove defer and make render() call then state is not updated. Currently it works because of async/defered rendering and we are just hoping the next line return (state = newState) runs before our render function. Is there any certainty that state will be updated before render call?. Ideally shouldnt it be state = newState then call defer(render)

**Comment by jorgebucaran** [comment]
Hi @githingeorge. Yes, the state will be updated before the render call. As you said, it works because `render` is deferred. 💯 

You might get in trouble if you override `requestAnimationFrame` with an [identity function](https://en.wikipedia.org/wiki/Identity_function), but that'd be odd.
