### ISSUE TITLE
V2 docs give examples with V1 link

### ISSUE THREAD

**Issue by fabio-looker** [jorgebucaran/hyperapp#851]
The current V2 docs say to use https://unpkg.com/hyperapp , but this currently resolves to https://unpkg.com/hyperapp@1.2.10/dist/hyperapp.js

I'm not sure what would be the best way to have the README always link to the right version though :-/

**Comment by jorgebucaran** [comment]
@fabio-looker V1 is still the latest version as V2 is still in beta. This works:

```html
<script type="module">
      import { h, app } from "https://unpkg.com/hyperapp@beta"
</script>
```
