### ISSUE TITLE
Hyperapp#2 effects signature

### ISSUE THREAD

**Issue by sergey-shpak** [jorgebucaran/hyperapp#854]
Due to current dispatch implementation, effect signature is `(dispatch, props, event)`, the last argument is always event (at least for user actions) and can not be changed.
It would be great to have possibility to overwrite/substitute last argument for effects, for example:

```jsx
const elementEffect = (dispatch, props, element) => {
  Object.keys(props).map(k => props[k] && element[k]())
  action && dispatch(action)
}

const withElement = (props, action) => 
  state => [state, [elementEffect, { props, action }]]

// this won't work because 'button' element won't be passed to effect
const blur = (state, button) =>
  [ withElement({ blur: true }), button ]

const eventTarget = event => event.currentTarget

// ...
<input type="button" value="focus" onfocus={[ blur, eventTarget ]}  />
```
^^ current issue can be resolved by passing 'element' as part of effect props, but the question is more about hyperapp#2 effect api design in general

**Comment by jorgebucaran** [comment]
@sergey-shpak Use an `id` to select the element.

**Comment by sergey-shpak** [comment]
@jorgebucaran updated example

**Comment by jorgebucaran** [comment]
I understand that passing the element would simplify focus and blur, but we can use an `id` to get the element inside the effect without complicating the API any further.

**Comment by sergey-shpak** [comment]
@jorgebucaran element can be passed as part of `props` to effect, or retrieved from `event` or queried by `id` inside of effect (as you propose). But api doesn't look consistent when you can easily pass param to action like `[action, param]`, but you cannot pass the same to effect `[withEffect, param]` (param will be lost, and `event` will be passed instead)
I don't want to complicate api or change core either, but looks like fix is pretty small somewhere in dispatch function

**Comment by jorgebucaran** [comment]
@sergey-shpak Sorry, I don't understand what you're trying to say. _"element can be passed as part of props"._ No, you can't. Where did you get that idea from?

**Comment by sergey-shpak** [comment]
passing 'element' as prop to effect (even if it is wrong, and no one should do this!)
```jsx
const effect = (dispatch, { props, element }) => { /* effect */ }

const blur = (state, element) => 
  state => [state, [effect, { element, props: { blur: true } }]]

const eventTarget = event => event.currentTarget

<input type="button" onfocus={[ blur, eventTarget ]} />
```
passing element with props(wrong!). querying by id or retrieving from event - works,
my point is that it would be great to have possibility to pass/substitute effect args, 
to make this happen

```jsx
const elementEffect = (dispatch, props, element) => {
// effect
}
const withElement = (props, action) => 
  state => [state, [elementEffect, { props, action }]]

const userAction = (state, event) => 
  [ withElement({ focus: true }), event.currentTarget ]

// dom query is effect to query dom 
const someOtherAction = (state) => 
  [state, dom.query(
    { id: 'some-id' },  
    // or even simple: withElement({ focus: true })
    (state, element) => [ withElement({ focus: true }), element ]
  )]
```

**Comment by jorgebucaran** [comment]
Gotcha. Then pass the element as part of effect props.

> But api doesn't look consistent when you can easily pass param to action like [action, param], but you cannot pass the same to effect [withEffect, param]

Effects are the other "return value" an action can have. If you stop trying to use effects like actions, which they're not, there's no inconsistency. ✨
