### ISSUE TITLE
Performance + SEO for starter example

### ISSUE THREAD

**Issue by aminnairi** [jorgebucaran/hyperapp#865]
This issue is more of a proposal to improve the starter example.

I figured that this example can be used by newcomers as a starter template for quick prototyping (or for those that do not use JSX).

I am proposing this template:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hyperapp Demo</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Hyperapp Demo">

    <link rel="preload" href="https://unpkg.com/hyperapp@2.0.0/dist/hyperapp.js" as="script">

    <script async>
      window.addEventListener("load", function() {
        const hyperappScript = document.createElement("script");

        hyperappScript.setAttribute("src", "https://unpkg.com/hyperapp@2.0.0/dist/hyperapp.js");
        hyperappScript.setAttribute("async", true);

        document.head.appendChild(hyperappScript);

        hyperappScript.addEventListener("load", function() {
          const { h, app } = window.hyperapp;

          app({
            init: 0,
            view: state =>
              h("div", {}, [
                h("h1", {}, state),
                h("button", { onClick: state => state - 1 }, "-"),
                h("button", { onClick: state => state + 1 }, "+")
              ]),
            node: document.getElementById("app")
          });
        });
      });
    </script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

Of course, the version of Hyperapp used could be a little bit more generic and when dealing with some more libs we would have used promises and `Promise.all` to load all libs but the points of this template are:
- Make the script non-blocking for performance purposes
- Add some starter meta tags in order to comply with the Google Chrome Audit

This is more verbose than the initial starter template but I guess people using this framework should now have some knowledge about HTML as well as 

Tell me what you think!

**Comment by jorgebucaran** [comment]
@aminnairi Overkill for a hello world too much? 😄  

The goal of the [quickstart](https://github.com/jorgebucaran/hyperapp#quickstart) is to get you started with Hyperapp as soon as possible, not bog you down in details. 

And you switched to the IIFE build, while I prefer using a module script. Module scripts behave like `defer` by default; they don't block the HTML parser while it fetches.

**Comment by aminnairi** [comment]
Yes you are right, this is kind of an overkill!

Especially since I just saw that there was a [`<link rel="modulepreload">`](https://developers.google.com/web/updates/2017/12/modulepreload), which could highly simplify the example code. May be we can use it in the starter example as well?
