### ISSUE TITLE
onAnimationFrame subscription can't be stopped

### ISSUE THREAD

**Issue by zaceno** [jorgebucaran/hyperapp#868]
Brought this up on the slack but since no quick conclusion was reached, I'm moving here for tracking.

Simply put: it seems `onAnimationFrame` as implemented in @hyperapp/events@0.0.1 cannot be stopped.  (using hyperapp@2.0.0-beta.25)

See this example:

https://codepen.io/zaceno/pen/mNqbJK

A suspicion is that it is somehow due to timing/interference with other use of rAF in core hyperapp.

Another clue might be gleaned from the fact that this alternative implementation (not using `cancelAnimationFrame` or keeping references) seems to work flawlessly -- at least in the above example:

```
const onAnimationFrame = (f => a => [f, a])((dispatch, action) => {
    let noop = () => {}
    let nextFrame = () =>
        requestAnimationFrame(time => {
            dispatch(action, time)
            nextFrame()
        })
    nextFrame()
    return () => {
        nextFrame = noop
    }    
})

```
(to wit: https://codepen.io/zaceno/pen/ymPBKJ)

---

Edit: ping also @mrozbarry

**Comment by zaceno** [comment]
@jorgebucaran 
Good, quick work! I'm surprised that simply switching the order of dispatch & rAF made such a difference. Would you mind explaining why that worked?

Other thing: Why 2.0.1? Did you make changes in core as well? (I couldn't find any)

**Comment by jorgebucaran** [comment]
It's a "pre-release". I released it so that the docs matched the examples. Nothing discourages you more than official examples that don't work.

As to why rAF works now, I'm not sure, but it makes more sense to grab the next frame before dispatching an action that can change the state.
