### ISSUE TITLE
Subscriptions/effects signature

### ISSUE THREAD

**Issue by sergey-shpak** [jorgebucaran/hyperapp#874]
Hyperapp V2 introduces powerful concepts of effects and subscriptions into dev userland. 
Even though there are important differences of use (effects are designed to trigger external side-effects, and subscriptions (in opposite way) to react to any external change), from the technical point of view they are almost similar ('subscription' == 'effect+cancel fn') and their signature/mechanics can be unified. For example into something following:
#### Effects
```javascript
const effect = (dispatch, props) => {
  // start your effect here
  const cancel = () => {} // define cancel function
  // and return function if you want to cancel effect
  return state => props.condition(state) && cancel()
}

const action = state => [
  state, [effect, { condition: state => state.someProp } ]
]
```
#### Subscriptions
```javascript

const interval = () => {
  var timer
  var cancel = () => clearInterval(timer)
  return (dispatch, props) => {
    // do your effect here
    timer = timer ? timer : setInterval(() => props.action, props.delay)
    // return function to cancel if needed
    return state => props.condition(state) && cancel()
  }
}

app({
  subscriptions: [ // yes, it is an array now
    [interval(), { delay: 100, condition: state => state.stop }]
  ]
})
```

What benefits we can gain? 
1. Cancelable effects
2. Possible simplification of internal 'patchSub'

It's not a final proposal and it doesn't require any change, it's just an idea to discuss :)

**Comment by jorgebucaran** [comment]
I notice the similarities between effects and subscriptions, especially at a low level, but looking at them from above, I see they're very different. Effects are _commands_, initiated by actions. Subscriptions are a mechanism to connect to global streams to receive external input. 

HTTP requests with `fetch`, location changes with `setLocation`, `Math.random`, etc., are Hyperapp effects. The difference between `fetch` and using the effect API is that the `fetch` is imperative, and using an effect is declarative. A declarative layer saves us from dealing with async control flow and managing real side effects directly.

Global events like window events and custom events like clock ticks, geolocation changes, handling push notifications, and WebSockets in the browser are Hyperapp subscriptions. They're essentially a glorified wrapper around add/removeEventListener, setInterval, and requestAnimationFrame.

Now, in your proposal you're missing that effects/subscriptions use an <samp>effect function</samp>; and an (optional) <samp>effect constructor</samp> function.

```js
const fx = (dispatch, props) => {
  // Use dispatch somewhere, e.g., dispatch(props.action)
}

export const MyFx = props => [fx, props]
```

Why? If we create a new function from scratch every time we invoke Fx, we won't be able to assert `deepEqual(myFx1, myFx2)`. Testing.

And what about cancelable effects? Effects aren't usually cancelable; if you need to stop them, you should use a subscription, which will let you track an event over time.
