### ISSUE TITLE
debug log remains in index.js (v2.0.2)

### ISSUE THREAD

**Issue by tetradice** [jorgebucaran/hyperapp#886]
It's a very small thing, but I'm going to report it because I think that many people read the source of hyperapp.

```js
console.log("DEBUG MODE")
var RECYCLED_NODE = 1
var LAZY_NODE = 2
var TEXT_NODE = 3
```

**Comment by jorgebucaran** [comment]
Thanks! For something as simple as this, I'd appreciate a PR instead.
