### ISSUE TITLE
2.0.2 "is" is undefined

### ISSUE THREAD

**Issue by abeisgoat** [jorgebucaran/hyperapp#887]
Using a JSX version of the "Hello World" app we see `hyperapp@2.0.2` printing out an usual "DEBUG MODE" console log and then it proceeds to error out.

```js
import { h, app } from  "hyperapp"

app({
    init: 0,
    view: state =>
        <main>
            <h1>{state}</h1>
            <button onclick={state => state -1}>-</button>
            <button onclick={state => state + 1}>+</button>
        </main>,
    node: document.getElementById("app")
});
```

Then we get an error on page load from Hyperapp's `index.js`
```
index.js:138 Uncaught TypeError: Cannot read property 'is' of undefined
```

Code works fine with `hyperapp@2.0.1`

**Comment by jorgebucaran** [comment]
@abeisgoat Thanks! Fixed in 74a8aeb and available in 2.0.3. 👋
