### ISSUE TITLE
2.0.3 hyperapp bundle not rendering on dom

### ISSUE THREAD

**Issue by Louis-Chen** [jorgebucaran/hyperapp#895]
but older version 1.2.8 is working

have any  coding style was change in new version?

**Comment by zaceno** [comment]
Yes the api is quite different now. Too much to explain in brief here. Have a look at the readme and tutorial.

**Comment by jorgebucaran** [comment]
@Louis-Chen V2 which is in beta/pre-release right now is quite different from 1.2.8. Here's a link to the [tutorial](https://github.com/jorgebucaran/hyperapp/blob/master/docs/tutorial.md). Have a look and may the force be with you! 👋
