### ISSUE TITLE
<select value={state.selectedId}> does not update select component's selected item.

### ISSUE THREAD

**Issue by elhigu** [jorgebucaran/hyperapp#897]
This is probably user error, but I have not been able to figure out why this does not work.

So I have button that appends new options to `<select>` element, but I am not able to update options-list and select the newly added option at the same time. Select just resets to first option even that `selectedOption` is updated correctly.

 I was able to create simple reproduction for the issue: https://codepen.io/elhigu/pen/ExxbqLO

 (my workaround now is to trigger changing selected option in `setTimeout(() => {actions.selectLast() }, 0)` )

**Comment by mshgh** [comment]
This is actually HTML related. You should add `selected` attribute to the option(s) you want to have selected.
Not the nicest implementation, but good way to explain.
```javascript
option => option === state.selectedOption 
     ? <option value={option} selected>Option: {option}</option>
     : <option value={option}>Option: {option}</option>
```

**Comment by elhigu** [comment]
Thanks! That works for me 👍
