### ISSUE TITLE
using shared nodes in the function view can induce wrong display.

### ISSUE THREAD

**Issue by gbagan** [jorgebucaran/hyperapp#903]
An example here:

a minimal example here:
https://jsfiddle.net/ecmLpgw8/
The counter 2 is incremented while it must be the counter 1.

The problem is the algorithm "patch" which affects a dom node to a virtual node my mutate its attribute  .node. The algorithm does not manage cases where two virtual nodes have referential equality.

I think a way to fix this bug is to affect the virtual node to the dom node ( node.__vdom = vdom ) and adapts the algorithm accordingly.
The reason it that It can have several dom nodes associated with a virtual node but only one node associated with a virtual node.
Maybe it can produce performance issues, I don't know.

I agree that the example is an uncommon usage but It think it is remains a bug.
Notably, it breaks the concept of referential transparency.
If the fix  involves too much effort or prdouce too much performance issues, I am ok to not fix it.

**Comment by gbagan** [comment]
Another example. I try to make it more realistic.
https://jsfiddle.net/tu9s716x/1/

**Comment by jorgebucaran** [comment]
> @Guillaume this example is trivial, but we can imagine `openedDiv` and `closedDiv` need a lot of time to be computed

Sounds like a job for lazy views! https://github.com/jorgebucaran/hyperapp/issues/721

And you're also trying to optimize the wrong process. Computing nodes is never the bottleneck.

```js
import { h, app } from "hyperapp"

app({
  init: { items: [false, false, false, false, false] },
  view: state =>
    h("main", {}, [
      state.items.map(isOpen =>
        isOpen ? h("div", {}, "open") : h("div", {}, "close")
      ),
      h(
        "button",
        {
          onClick: ({ items }) => ({
            items: items.map((x, i) => (i == 3 ? !x : x))
          })
        },
        "open div 3"
      )
    ]),
  node: document.getElementById("app")
})

```

**Comment by gbagan** [comment]
Actually, it is more complex than I was thinking.
I think it can be fixed as follows:
we use a variable id that determines the render number. It starts from 0 and it is incremented at each render.
the vnodes contain an attribute .$id that will be mutated during the render.
getVNode need to be modified:
```
    if vnode.$id < current render id
        (that means that the vnode has not seen before during the current render)
    then
        change nothing and vnode.$id = current render id
    else make a shallow copy of the vnode 
```
That prevents problem with shared vnodes but keep optimization for lazy views

**Comment by gbagan** [comment]
I have thought and thought about how to fix this bug.
I think the only way to prevent strange behaviour when parts of the vdom are shared is to make not mutate the vdom returned by the function view.
I have started to write a patch.
The idea is to not store nodes into vnodes but in a structure that contains both vnodes and nodes.
This structure is mutable but vdom is immutable.
I have called it ptc but it just a temporary name it is a array of  3 elements [node, array of ptc children, vdom]
My tentative is here. It is not finished.
Just to give an idea.
https://github.com/gbagan/hyperapp/commit/467411e3c4e44341257c6998e72910285650dd10

**Comment by sergey-shpak** [comment]
@gbagan @jorgebucaran , 
hyperapp shouldn't mutate vdom, and the fix looks quite easy to me:
```js
var getVNode = function(newVNode, oldVNode) {
  // everything stays the same, except return new node
  // was : newVNode, and now:
  : Object.assign({}, newVNode)
}
```
creating and working with shallow copy of each vdom node is fixing 'shared nodes' or any other 'vdom mutation' issue, also this looks more 'functional' way of 'not mutating any external'.
Any thoughts?

**Comment by gbagan** [comment]
Just seen and it was my first idea.
But that breaks all optimizations based on comparing two vnodes. Lazy view, for example.

**Comment by sergey-shpak** [comment]
@gbagan there is no strict comparison between vNode objects, they compared by properties (`name`, `attributes`, etc), so creating and storing shallow copy of vNode doesn't impact on comparing vNodes.

Shallow copy of vNode still contains all the vNode props (lazy view, props, etc) and can be compared with new vNode the same way as before (without loosing any optimizations), but at the same time it allows to not mutate external vNode objects (solves 'shared nodes' or any other vnode mutation issue)

**Comment by gbagan** [comment]
In the function patch, the algorithm tests the two vnode and skip all the function if the test succeeds.
That permits to skip whole subtrees

**Comment by sergey-shpak** [comment]
@gbagan generally talking, this construction `if (oldVNode === newVNode) {}` is confusing and doesn't work as you expect, it can be omitted because:
1. Hyperapp expects that `view` function always returns new vdom tree (otherwise patching doesn't have any logical sense)
2. This construction **compares only object references (not theirs props)**, so even though view returns the same **vdom reference** it has to be passed into patching algo, **because attributes or children could be changed** and those changes has to be reflected into the dom

I can be wrong, but this construction comes more from 'writing code style' and doesn't solve any real case @jorgebucaran please confirm

**Comment by gbagan** [comment]
Maybe you are right.
For me, the main use is in combination with lazy view.
If the lazy view returns the same view than before. Then patch can skipp all the subtree returned by the lazy view

**Comment by gbagan** [comment]
Unless I am wrong, if two vnodes have the same reference, there children and attributes are necessarily the same. But the inverse is not true.

**Comment by sergey-shpak** [comment]
ok, let's clarify this
> For me, the main use is in combination with lazy view.
If the lazy view returns the same view than before, then patch can skip all the subtree returned by the lazy view.

**It doesn't work this way, you shouldn't store and return the same lazy view vdom to skip lazy view rendering**. [Lazy view rendering depends only on lazy props](https://github.com/jorgebucaran/hyperapp/blob/master/src/index.js#L368), if they have changed - hyperapp rerenders lazy view and patches the dom, if not - rendering/patching is omitted.

But while you were storing and returning the same vdom tree to omit patching dom (imo, which is wrong lazy usage) you have found the issue with 'shared vNodes' mutations, which is easily solved with shallow vNode copy (as I already [shown](https://github.com/jorgebucaran/hyperapp/issues/903#issuecomment-568258936))

**Comment by gbagan** [comment]
> It doesn't work this way, you shouldn't store and return the same lazy view vdom to skip lazy view rendering. Lazy view rendering depends only on lazy props, if they have changed - hyperapp rerenders lazy view and patches the dom, if not - rendering/patching is omitted.

That my point but I misspoked. Sorry.  (I have not said that I store the vdom)
Globally I had the same idea than you but I am convinced myself than it is not the good way to do (maybe I am wrong).
The question is what you keep as vdom after the render to use as previous vdom for the next render.
If you use the original vdom, you lose every information about dom nodes.
If you use the copy of the vdom, you lose all reference equality (and skip patching)

**Comment by sergey-shpak** [comment]
@gbagan ok, np, let's summarize the issue

1. Hyperapp mutates vNodes by storing reference to dom nodes
2. This mutation creates unexpected patching results when vNode is reused in vDom tree.
```
// simplified example
view: state => {
  const node = h('div', {}, [])
  // each of the nodes will share the same dom node
  return [ node, node, node ]
}
```
3. The simplest fix is to [create shallow copy of each vNode](https://github.com/jorgebucaran/hyperapp/issues/903#issuecomment-568258936) internally
4. In general, hyperapp patching algo is using vNode props to compare nodes, and it should work the same way with shallow copy of vNode. But there is one patching case to mention `if(oldVNode===newVNode){}` which may not work with shallow copy of node as expected, but this case has to be omitted [by following reasons](https://github.com/jorgebucaran/hyperapp/issues/903#issuecomment-568269546)

**Comment by jimfranke** [comment]
@jorgebucaran What are the current thoughts about this issue? Is shallow copying and omiting the reference equality check a plausible solution? If this could work the solution would be a lot simpler than the proposed PR.

**Comment by jorgebucaran** [comment]
@jimfranke I need to study this more carefully, but it seems like a user mistake, not a bug.

**Comment by zaceno** [comment]
The way I see it, we don't need to fix anything in hyperapp to allow reusing nodes, because it doesn't enable anything besides possibly optimization via memoization. But since that is essentially what `Lazy` is for, we're covered.

**Comment by gbagan** [comment]
I agree with Zaceno comments.
For me, this is clearly a (minor) bug unless it ispecified somewhere that one cannot share vdom subtrees.
But, I agree this bug is minor and fixing it will probably decrease performance.
Since performance seems to be an important aspect of hyperapp, I am ok to not fix it.
And honestly, I am very busy these weeks and at the moment, I have no time to dedicate to this bug.
