### ISSUE TITLE
Website is broken now

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/hyperapp#916]
#914 #915 #900 @loteoo @sergey-shpak Any ideas? 😅

**Comment by jirutka** [comment]
What do you see on https://github.com/jorgebucaran/hyperapp/settings in section “GitHub Pages”? You should have Source set to _gh-pages branch_ and Custom domain _hyperapp.dev_. Yous hould also see green message _Your site is published at https://hyperapp.dev/_.

**Comment by jorgebucaran** [comment]
Here you go:
![](https://user-images.githubusercontent.com/56996/73508863-a076bd80-4420-11ea-9356-08b3b064d932.jpg)

And here's my DNS console on CloudFare (currently using it for free https).

<img width="1079" alt="Screen Shot 2020-01-31 at 11 57 01" src="https://user-images.githubusercontent.com/56996/73509048-26930400-4421-11ea-85b5-63a9175d60e6.png">

**Comment by jirutka** [comment]
GH Pages for your repository is not active. Try to switch Source branch to master and then back to gh-pages. If it will not change the state, try to delete the gh-pages branch from GitHub and push it again (manually using your account with admin rights for the repository).

**Comment by jorgebucaran** [comment]
It worked! Thanks, @jirutka! 🎉
