### ISSUE TITLE
Website: Minor niggles.

### ISSUE THREAD

**Issue by zaceno** [jorgebucaran/hyperapp#917]
- ~The counter live example on the front page has a typo. The subtract button says "substract". The code example is correct though (so I assume the example is not executing the same code that is displayed on the page)~.

- ~In the tutorial, wherever there is a code snippet with an import of `@hyperapp/something`, the module gets replaced with `[email protected]` (probably due to the `@`)~.

- In the tutorial, in the aside where JSX and htm are mentioned, the words "JSX" and "htm" are actually links to more info, but links are indistinguishable from regular text so you have to get lucky and accidentally hover them with the mouse to discover them.

- ~The screenshots are missing from the tutorial~

- the stuff in blockquotes of the tutorial are meant to be “asides”. They are interesting, but not essential to the main thread. The current styling makes them too prominent imo and does not convey their “side note-ness” which is confusing.

- ~there is a bar of equal signs at the top. The markdown parser must have missed that this line means that the line above is a h1 (a valid-markdown way of denoting a h1)~

- The code highlighter font uses some ligatures that turn `==` into a triple equals sign and `=>` into a double lined arrow. Presumably `!=` turns into inequality symbol but I didn't check. While this can certainly be neat in your own dev setup, I think we should stop doing that in example code on the website because it misrepresents the characters you actually need to type. It is unlikely to confuse an experienced developer, but for beginner-programmers it may well. Also, will copy-n-paste work? 

---

EDIT 1: More niggles:
EDIT 2: Strike out fixed issues 
EDIT 3: One more niggle

**Comment by haykkh** [comment]
We can temporarily work around the `[email protected]` issue by loading the tutorial directly as apposed to navigating to it from [hyperapp.dev/](https://hyperapp.dev/).

**Comment by zaceno** [comment]
@haykkh Good tip! This time we didn't need it because I changed the tutorial so there wouldn't be any imports containing `@`

**Comment by jorgebucaran** [comment]
Adding a few more items to my list here:

- Change ecosystem to awesome. With #938 on the horizon, I want the website to focus the official goods (a.k.a things we can directly contribute to / have access to), but we could still have something like https://github.com/jorgebucaran/awesome-hyperapp in that page.
- Change sponsor to contribute. I think we might have a better chance of winning a few more sponsors by introducing people to the contribution process or create one if there isn't an official one.

**Comment by jorgebucaran** [comment]
Another thing I want to do is improve the syntax-highlighted code blocks theme. I don't like the current theme. Maybe we should try something with a dark background using the [official Hyperapp colors](https://www.figma.com/proto/IXKZlvYFiPR4T6T8sMcQkP/hyperapp.dev?scaling=min-zoom&node-id=0%3A460).

**Comment by jorgebucaran** [comment]
I've been thinking about what I believe we need to finish the Website and produce an official 2.0 release and came up with this list:

0. Round up the most glaring issues standing issues wit
1. Write a new *tutorial*. The current tutorial can be repurposed as a dev.to article or a blog post. The goal of the tutorial should be to give people a real taste of Hyperapp, nothing too hard, nothing too simple. There's no need to use all the features. Remember 80/20 rule. I should write a new comment to explain why I feel we need a new tutorial.
2. Write *contribute* (renamed from sponsor). The goal of this section is to explain *how* to contribute to Hyperapp and *what* contributions we're looking for. We can look at what other communities do and cherry-pick what works for us. This one should be relatively straightforward as soon as we find a good role model.
3. Write *awesome* (renamed from ecosystem): an ultra simplified https://vimawesome.com for Hyperapp. Is that a lot to wish for?
4. Write *guides*: there's no end to how many guides we can have here. Let's start with at least one guide, e.g., "Talking to servers" or whatever we find fun to write about that's also not already elaborated on the tutorial.
5. Write *API*. Just your typical API docs. Nothing fancy. The goal is to tell it how it is. No bells or whistles. What is `h`/`app` and how they work? How to create an action? Payloads—what's that? How to create an effect, a subscription? How to use lazy?
6. Implement *search*. My idea was to have a script create an "index" of all the pages, the tutorial, guides, API, etc., whenever we build the site (we could use Python, Rust, Haskell, or whatever fancy language we like) as a text file or a JSON file and then implement a search algorithm in JavaScript that uses it.
7. Use a different theme for code blocks.
8. Implement "join us: enter your email". I don't know if we can actually implement this without a server, though.

**Comment by zaceno** [comment]
All good ideas! But pretty ambitious. With this plan it will be a while until all the loose ends on the website are tied up and that might be a problem. 

Yes, it says it is a wip on the front page but that’s easy to miss and also not very common these days. People are finding lorem ipsum and broken search and getting a poor impression.

Also, even though it’s technically a placeholder, we shouldn’t be saying “2x faster than react” on a public facing website unless we mean it and can back it up.

So  I’d suggest dialing back the website as much as necessary to get rid of all the loose ends. And then add stuff incrementally as it gets done.

**Comment by zaceno** [comment]
About the tutorial, instead of covering all the features, you think we should move some parts (like effects & subs) to guides instead? Or is it the example itself that should be smaller? Maybe multiple small examples, like one per feature? I’m not opposed to it - just curious what you’re after with the 80/20 thing. 

Btw as much as I’d like to help, I just started a new job and think I won’t have much time (near time) for working on the tutorial. So feel free to get others involved!

**Comment by jorgebucaran** [comment]
> Yes, it says it is a wip on the front page but that’s easy to miss and also not very common these days. People are finding lorem ipsum and broken search and getting a poor impression.

True, it might be a better plan to leave the new tutorial for last.

> Also, even though it’s technically a placeholder, we shouldn’t be saying “2x faster than react” on a public facing website unless we mean it and can back it up.

True. It's not exactly 2x, more like 1.8x? We could link to the JS benchmark from there.

> About the tutorial, instead of covering all the features, you think we should move some parts (like effects & subs) to guides instead?

Yes, that makes sense. We could have a guide dedicated to "creating effects and subscriptions" as well as "talking to servers" or "creating WebSockets" that involve writing effects/subs anyway. When you wrote the tutorial, I was still on the fence about whether we should ship with official effects/subs, but now it's decided that we won't (#938).

> Btw as much as I’d like to help, I just started a new job and think I won’t have much time (near time) for working on the tutorial. So feel free to get others involved!

Absolutely. ❤️

**Comment by jorgebucaran** [comment]
Good/bad news. https://hyperapp.dev now (or will soon) redirects to the repo. I believe that having a website is a valuable asset for the project, but I haven't been able to design (or have designed) something that I'm satisfied with, so I'll just play it safe for now.
