### ISSUE TITLE
Website: Search is completely unusable on mobile

### ISSUE THREAD

**Issue by jirutka** [jorgebucaran/hyperapp#933]
When you click on the search box and start typing, the menu with the search box loses focus and disappears with the first keystroke.

It’s really bizarre that the website looks like mobile-first, but apparently no one has tested it on a small screen.

![hyperapp-search](https://user-images.githubusercontent.com/949228/76146609-61c5ca00-6094-11ea-9d8f-1da87abaeb6e.gif)

**Comment by jorgebucaran** [comment]
@jirutka That looks pretty inadequate, indeed.

**Comment by jorgebucaran** [comment]
@loteoo Can we close here?

**Comment by loteoo** [comment]
> @loteoo Can we close here?

Yup! It looks good to me at least for the UX
