### ISSUE TITLE
Incorrect function signature for custom Components with children?

### ISSUE THREAD

**Issue by B-Teague** [jorgebucaran/hyperapp#937]
I noticed hyperapp isn't using props.children the same as react, preact, ultradom, etc.....

See bug here for Preact:
preactjs/enzyme-adapter-preact-pure#61 (comment)

This is causing an issue for my framework agnostic CSS-in-JS library I am creating to use with hyperapp.

## Referencing children ```(props)``` vs ```(props, children)```
```js
function FancyBorder(props) {
  return (
    <div className={'FancyBorder FancyBorder-' + props.color}>
      {props.children}
    </div>
  );
}
```

**vs**

```js
function FancyBorder(props, children) {
  return (
    <div className={'FancyBorder FancyBorder-' + props.color}>
      {children}
    </div>
  );
}
```

## Passing children to a custom component
```js
<FancyBorder color="blue">
    <h1 className="Dialog-title">
      Welcome
    </h1>
    <p className="Dialog-message">
      Thank you for visiting our spacecraft!
    </p>
</FancyBorder>
```

## Suggested code change:
```js
return typeof name === "function"
    ? name({children, ...props})
    : createVNode(name, props, children, undefined, props.key)
```
**vs**
```js
return typeof name === "function"
    ? name(props, children)
    : createVNode(name, props, children, undefined, props.key)
```

**Comment by zaceno** [comment]
Since Hyperapp isn't aiming for api-parity with react, the signature isn't  "incorrect", but simply different ;). Personally I prefer hyperapp's signature since react needlessly reserves a prop-name. 

What kind of issue are you having? Perhaps there's a not-too-bad change you could make on your end to achieve cross-framework-compatibility?

PS About your code suggestion, bear in mind Hyperapp is written in es5 (or es3 even?) .

**Comment by B-Teague** [comment]
I need to be able to forward any children using a styled component to hyperapp's h function.

```js
FancyBorder = styled("div")({
  borderColor: "red",
  borderRadius: "25px"
}) 
// For React, this will return 
//    (props) => h("div", {className: "className-123"}, props.children)
// For hyperapp, this would need to return 
//    (props, children) => h("div", {class: "className-123", children)

const view = (state) => {
   return <FancyBorder>
      <p>Child content inside styled border</p>
   </FancyBorder>
}
```
I am already having to handle class vs className in React vs Preact and Hyperapp.
I can create a new options flag that says, use (props) or use (props, children)

**Comment by jorgebucaran** [comment]
> @B-Teague I can create a new options flag that says, use (props) or use (props, children)

This might be the best way to about this here, Brian. 👍

**Comment by B-Teague** [comment]
Options flag it is.  Closing the issue.

**Comment by zaceno** [comment]
@B-Teague Options flag sounds good. But you could even do something like:

```
(props, children) => h("div", {[children ? 'class' : 'className']: 'classname-123'}, children || props.children)
```

... but nah. option flag ftw
