### ISSUE TITLE
Hyperapp Context Pattern

### ISSUE THREAD

**Issue by sergey-shpak** [jorgebucaran/hyperapp#939]
Sometimes it's necessary to pass some props/state into deeply nested components without 'wiring' them by hands, so after some investigation I came to the following pattern:
```js
import { app, h } from 'hyperapp'

// Context hof is simple as 
const withContext = fn => (attrs, childs) => 
  fn(attrs, childs, (name, props, childs) => 
    typeof name === 'function'
    ? h(withContext(name), { ...attrs, ...props }, childs)
    : h(name, props, childs)
  )

// and example, all you need to do - is to wrap 
// initial view with context hof, and use 
// passed 'h' function to render vdom tree

const componentC = (props, childs, h) => 
  // {"state":1,"viewProp":true,"propA":true,"propB":true}
  h('div', {}, `Context: ${JSON.stringify(props)}`)

const componentB = (props, childs, h) => 
  h(componentC, { propB: true }, 'Component B')

const componentA = (props, childs, h) => 
  h(componentB, { propA: true }, 'Component A')

const view = (props, childs, h) => {
  return h(componentA, { viewProp: true }, 'View')  
}

app({
  init: { state: 1 },
  // wrapping view with context
  view: withContext(view),
  node: document.body
})
```
[working example](https://codepen.io/sergey-shpak/pen/gOaYwBP?editors=0010)

Btw, it should also work with jsx, even though we can set jsx pragma as 'arguments[2]' and get rid of importing 'h' into each file/component ;)

Any thoughts about this pattern?
@jorgebucaran @zaceno @mrozbarry @frenzzy @okwolf

**Comment by infinnie** [comment]
> even though we can set jsx pragma as 'arguments[2]'
this doesn’t work with the ES6 arrow function syntax.

**Comment by sergey-shpak** [comment]
@infinnie :+1: , to use `arguments[2]` as jsx pragma regular functions have to be used for components:
```jsx
function View(props, childs){
  return <ComponentA propA={true} />
}
```

**Comment by zaceno** [comment]
At a first glance, I like this pattern -- it's way more compact than the one I'm currently using in my wip form-library, and the way you pass context through component props is potentially much cleaner. I'm going to experiment with this to see how it works out in practice and report back.

**Comment by zaceno** [comment]
One problem is that this doesn't work when using [htm](https://github.com/developit/htm). But perhaps there are ways around that. 🤔

**Comment by sergey-shpak** [comment]
@zaceno I'm using my own 'html' factory implementation
```js
// helper.js
import { h } from 'hyperapp'

export const html = new Proxy({}, {
  get: (target, name) => (attributes, children) =>
    (typeof attributes === 'object' && !Array.isArray(attributes)
      ? h(name, attributes, children)
      : h(name, {}, attributes))
})

export const withContext = fn => (attrs, childs) => 
  fn(attrs, childs, (name, props, childs) => 
    typeof name === 'function'
    ? h(withContext(name), { ...attrs, ...props }, childs)
    : h(name, props, childs)
  )
```
and example
```js
import { html, withContext } from 'helper'
// any required element
const { div, span } = html

const ComponentB = (props, childs) => 
  span(`${JSON.stringify(props)}`)

const ComponentA = (props, childs, h) => 
  div([
    span(['ComponentA']),
    h(ComponentB, { propA: true }, '')
  ])

app({
  init: {},
  view: withContext(CoponentA),
  node: document.body
})
```
anyway, using html factory as shown above or using htm package - is a different task, and can be workarounded )

**Comment by sergey-shpak** [comment]
Also this pattern significantly simplifies Router (because `location` can be easily propagated to deeply nested Route components), for example as simple as:
```js
// withContext from prev example

// base Route component
const Route = ({ path, render, location }, childs, h) => 
  location === path && h(render, {}, childs)

// base navigation action
const navigate = (state, location) => ({ location })

const ComponentA = (props, childs, h) => 
  h('a', { onclick: [navigate, '/b'] }, 'Go to ComponentB')

const ComponentB = (props, childs, h) => 
  h('a', { onclick: [navigate, '/a'] }, 'Go to ComponentA')

const view = (state, childs, h) => 
  h('body', {}, [
    h(Route, { path: '/a', render: ComponentA }),
    h(Route, { path: '/b', render: ComponentB })   
  ])

app({
  init: { location: '/a' },
  view: withContext(view),
  node: document.body
})
```
and [working example of Context based Router](https://codepen.io/sergey-shpak/pen/JjYPLgp?editors=0011)

**Comment by jorgebucaran** [comment]
Great material for [Discussions](https://github.com/jorgebucaran/hyperapp/discussions) this issue was, but I think it has already run its course. Thank you, @sergey-shpak for sharing this pattern with us. 🙆‍♂️
