### ISSUE TITLE
Hyperapp State Provider

### ISSUE THREAD

**Issue by sergey-shpak** [jorgebucaran/hyperapp#941]
Passing app 'state' to each nested component is annoying and makes code less readable,
so after some research I came to the following approach: 
```js
import { app, h } from "https://unpkg.com/hyperapp@2.0.4"

// State Provider
const stateProvider = fn => state => 
  (function provide(target){
    if(typeof target === 'function')
      return provide(target(state))
    if(typeof target.name === 'function')
      return provide(target.name(state))
    if(target.children) target.children = 
      target.children.map(child => provide(child))
    return target    
  })(fn(state))

// please notice - returning function to get state
const DeeplyNestedComponent = props => state =>
  h('span', {}, `State prop is ${state.prop}`)

const SomeComponent = props => 
  h(DeeplyNestedComponent, {})

const View = props =>
  h(SomeComponent, {})

app({
  init: { prop: 123 },
  view: stateProvider(View),
  node: document.body
})

```
[working example](https://codepen.io/sergey-shpak/pen/MWaWpop?editors=0011)

StateProvider allows you get app state at any component level, simply by returning function from component (this works similar way as hyperapp#1 actions work ;) )

In case you want also propagate some props to deeply nested components you can take a look at [Context Pattern](https://github.com/jorgebucaran/hyperapp/issues/939)

As usual - any feedback is appreciated,
@jorgebucaran @zaceno @mrozbarry @frenzzy @okwolf

**Comment by jorgebucaran** [comment]
Looks pretty cool @sergey-shpak! 🏅:trollface:🏅

**Comment by zaceno** [comment]
Awesome @sergey-shpak  This is  a lot closer to how I've been doing context, except I hadn't realized the `target.name === 'function'` trick. I have been using a "consumer" function to create fake objects (in order to pass through `h`'s child-processing loop). This proves that unnecessary. Win!

**Comment by sergey-shpak** [comment]
@jorgebucaran , @zaceno thanks!

Just to be on the same page, imo _context_ - is an 'object' propagated through the chain of components, each component can access/update/propagate context - this means that context can be changed while goes through the chain (the same component can receive different contexts depending where it is used). Context can contain any sort of data.

As result [Context Pattern](https://github.com/jorgebucaran/hyperapp/issues/939) provides more powerful functionality - you can pass anything you want (not only app state), but at the same time it requires you to manually propagate context (by using passed 'h' function). On the other hand, `StateProvider` is much simpler solution and designed only to get app state.

**Comment by zaceno** [comment]
@sergey-shpak yes I'm on the same page. I realize this code snippet is for propagating app state to all components that need it. Still the mechanism of scanning the tree to find functions and call them is the same I was doing to share properties among components under a form. Only, I hadn't considered checking`typeof target.name === 'function'` before (I was doing something more complicated). So this code allowed me to simplify my code.

**Comment by sergey-shpak** [comment]
Updated to support true/false/null from components 
```js
/* Component State Provider */
export const stateProvider = fn => state => 
  (function provide(target){
    return typeof target === 'function'
    ? provide(target(state))
    : typeof target.name === 'function'
    ? provide(target.name(state))
    : target.children && { ...target, 
        children: target.children.map(child => 
          provide(child)).filter(Boolean)
      }
  })(fn(state))
```

**Comment by SkaterDad** [comment]
This is really clever, nice job!  Kind of wish this was built-in like in olden times.

Either way, quick to add, and I assume the perf impacts aren't terrible.

[Working example with 2.0.8
](https://codesandbox.io/s/zen-jennings-gw6pr?file=/src/index.js)

**Comment by brucou** [comment]
I'll err on the other side on the argument which is that having two different signatures for components make the code less readable. Uniformity is something that you want to minimize cognitive load. The less concepts the better and this is something Hyperapp is really good at.

**Comment by jorgebucaran** [comment]
Another interesting pattern. Thank you for sharing it with us @sergey-shpak. 🙌
