### ISSUE TITLE
Can't access Hyperapp 404 page

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/hyperapp#943]
Example: https://hyperapp.dev/foo

**Comment by Jacob-Marshall** [comment]
Hi,

I found this [guide](https://docs.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) that explains how to do it. You may have to make the page with HTML instead of hyperapp.

**Comment by jorgebucaran** [comment]
Thanks for the info! 

I got good/bad news. https://hyperapp.dev now (or will soon) redirects to the repo. I believe that having a website is a valuable asset for the project, but I haven't been able to design (or have designed) something that I'm satisfied with, so I'll just play it safe for now and use a redirect. The future is bright, but I want to focus on the stuff I can do best, creating Hyperapp.
