### ISSUE TITLE
Where can I find the typescript definition files of hyperapp?

### ISSUE THREAD

**Issue by oyzhen** [jorgebucaran/hyperapp#945]
Where can I find the typescript definition files of hyperapp?

I've tried `npm i -D @types/hyperapp` (couldn't found the package) and setting `"types": ["hyperapp']` in tsconfig.json, but no types detected.

**Comment by jorgebucaran** [comment]
@oyzhen There are none at the moment. There was a PR https://github.com/jorgebucaran/hyperapp/pull/839 here and you are also welcome to help out! 👋😄

**Comment by BlueGhostGH** [comment]
Any update on this?

**Comment by jorgebucaran** [comment]
@BlueGhostGH https://github.com/jorgebucaran/hyperapp/pull/969

**Comment by BlueGhostGH** [comment]
Thanks!
