### ISSUE TITLE
how can i rewite react in hyperapp

### ISSUE THREAD

**Issue by Louis-Chen** [jorgebucaran/hyperapp#948]
i want to import React Component  in hyperapp project

but it look like not working

maybe babel can not compile react and hyperapp in same project

it is possible?

**Comment by jorgebucaran** [comment]
Pure stateless React components are largely compatible with Hyperapp. I can say with confidence that 60% of the time, it works every time.

```js
const Welcome = (props) => <h1>Hello, {props.name}</h1>
```

React injects the component children in `props`, whereas Hyperapp components receive them as the second argument to the component function. Therefore, pure stateless React components with children will need to be modified to work with Hyperapp.

```js
// React
const Welcome = (props) => <h1>Hello, {props.name + props.children}</h1>

// Hyperapp
const Welcome = (props, children) => <h1>Hello, {props.name + children}</h1>
```

Finally, stateful components (`class`-based or `useState`-based) are not compatible with Hyperapp.

**Comment by Louis-Chen** [comment]
@jorgebucaran 
how about render ReactDOM in hyperrapp?
like: 
```js
import Component,{ useHook } from 'react-third-component' 
const ReactComp =() =>{
    const [count,setCount] = useHook()
    return <Component {....count,setCOunt}/> 
}
<div oncreate={(element) => {
  if (element) ReactDOM.render(<ReactComp />, element)
}}></div>
```

**Comment by zaceno** [comment]
@Louis-Chen That could probably work in hyperapp@1.x.x. But just make sure to use a `key` prop on the `div`. You can still use v1 of course but it isn't supported.

Might not work exactly like that though... Doesn't React's render replace the `element`? 

In hyperapp@2.x.x there are no `concreate` et c. You need to use other (admittedly more cumbersome) approaches to trigger the render and access the element.

**Comment by Louis-Chen** [comment]
@zaceno  
thanks i try this way successfully , it is work
