### ISSUE TITLE
where can I find the docs about 1.x version ?

### ISSUE THREAD

**Issue by lili21** [jorgebucaran/hyperapp#956]

**Comment by zaceno** [comment]
https://github.com/jorgebucaran/hyperapp/tree/V1

The README.md on the V1 branch has all the v1 docs.

**Comment by zaceno** [comment]
For even more (articles, examples and such) check the "V1" section of the awesome-list:

https://github.com/jorgebucaran/awesome-hyperapp

**Comment by jorgebucaran** [comment]
@lili21 Keep in mind that Hyperapp <2.0.0 is deprecated, please use Hyperapp >=2.0.0.
