### ISSUE TITLE
Example to interface websocket server

### ISSUE THREAD

**Issue by joelviel** [jorgebucaran/hyperapp#957]
Hi,

After browsing internet for a while, there is no example how to interface hyperapp 2 against websocket server,
It is mentioned to use subscription in that case, but how-to is not trivial,

For example, how to mix hyperapp 2 when receiving data from server with such websocket client https://socket.io/docs/client-api/ ?

Thanks

**Comment by okwolf** [comment]
I've published a [library of FX](https://github.com/okwolf/hyperapp-fx) that includes a [sub for listening on `WebSocket`s](https://github.com/okwolf/hyperapp-fx/blob/master/api.md#module_subs.exports.WebSocketListen) you should check out.

**Comment by jorgebucaran** [comment]
@joelviel [Here's an echo chat in codesandbox](https://codesandbox.io/s/hyperapp-minimal-ws-echo-chat-o6o80). It's using a slightly older v2, but the required modifications to upgrade for the latest in the `minimizations` branch is minimal, so it should be useful to you.

👋
