### ISSUE TITLE
Website: can't scroll code snippets horizontally on mobile

### ISSUE THREAD

**Issue by estevaog3** [jorgebucaran/hyperapp#959]
Hello, there,
Just discovered this framework. I noticed that I can't scroll horizontally the code snippets on a Motorola E4 plus phone, using the most recent version of Brave browser. 

Edit: the following code snippet overflows the phone's screen:
![screenshot2](https://user-images.githubusercontent.com/22309462/86166207-69e1c380-bae2-11ea-8b11-43208a63fc33.jpg)

**Comment by jorgebucaran** [comment]
Thanks for the info! 

I got good/bad news. https://hyperapp.dev now (or will soon) redirects to the repo. I believe that having a website is a valuable asset for the project, but I haven't been able to design (or have designed) something that I'm satisfied with, so I'll just play it safe for now and use a redirect. The future is bright, but I want to focus on the stuff I can do best, creating Hyperapp.
