### ISSUE TITLE
Lorem ipsum in your website

### ISSUE THREAD

**Issue by iamanas20** [jorgebucaran/hyperapp#960]
Hey there,
I really like this framework and really believing in the potential, one thing i noticed while checking the website [hyperapp.dev](url) is that lorem ipsum text.
Again, thank you for this blazing fast framework, will definitely use it soon. <3

**Comment by jorgebucaran** [comment]
@iamanas20 Thank you, I'll keep this open until we're done fixing this. 👍

**Comment by roryokane** [comment]
Specifically, the pages that contain nothing but placeholder text are [hyperapp.dev/guides](https://hyperapp.dev/guides) (edit [`guides.md`](https://github.com/jorgebucaran/hyperapp/blob/eec455a2b5cfb75a19e6eaddfe670a6456c2f25f/docs/src/pages/Guides/guides.md)) and [hyperapp.dev/ecosystem](https://hyperapp.dev/ecosystem) (edit [`ecosystem.md`](https://github.com/jorgebucaran/hyperapp/blob/eec455a2b5cfb75a19e6eaddfe670a6456c2f25f/docs/src/pages/Ecosystem/ecosystem.md)).

**Comment by jorgebucaran** [comment]
Thanks for the info! 

I got good/bad news. https://hyperapp.dev now (or will soon) redirects to the repo. I believe that having a website is a valuable asset for the project, but I haven't been able to design (or have designed) something that I'm satisfied with, so I'll just play it safe for now and use a redirect. The future is bright, but I want to focus on the stuff I can do best, creating Hyperapp.
