### ISSUE TITLE
Missing redirect when requesting some pages other than root

### ISSUE THREAD

**Issue by meinstein** [jorgebucaran/hyperapp#961]
Hey, first of all, very cool framework! While perusing, noticed that:

- Refreshing or directly landing on `https://hyperapp.dev/api` falls over
- But interestingly, `https://hyperapp.dev/tutorial` is fine

Cheers!

**Comment by jimt** [comment]
And what is presumably a variation on the theme: After following a link off https://hyperapp.dev/ and then hitting the browser back button, the Chrome address bar shows a http://hyperdev.app URL, but the display is the GitHub 404 page.

1. Visit https://hyperapp.dev/api
2. Click on the **improve this page** link near the bottom of the page
3. Use the browser back button (shows the 404 page)

**Comment by jorgebucaran** [comment]
Thanks for the info! 

I got good/bad news. https://hyperapp.dev now (or will soon) redirects to the repo. I believe that having a website is a valuable asset for the project, but I haven't been able to design (or have designed) something that I'm satisfied with, so I'll just play it safe for now and use a redirect. The future is bright, but I want to focus on the stuff I can do best, creating Hyperapp.
