### ISSUE TITLE
Web site: navigation does not show top of page

### ISSUE THREAD

**Issue by jimt** [jorgebucaran/hyperapp#962]
Using the web site left navigation menu does not show the top of the referenced page (unless the target page is so short that it fits on a single screen?).

To duplicate:

1. visit https://hyperapp.dev/
2. scroll down a couple of screens
3. click [tutorial](https://hyperapp.dev/tutorial) (or api) in navigation
4. navigates to selected page, but rather than the top of the page, you are scrolled down into the body
5. continued navigation clicks among the long pages does the same

**Comment by jorgebucaran** [comment]
Thanks for the info! 

I got good/bad news. https://hyperapp.dev now (or will soon) redirects to the repo. I believe that having a website is a valuable asset for the project, but I haven't been able to design (or have designed) something that I'm satisfied with, so I'll just play it safe for now and use a redirect. The future is bright, but I want to focus on the stuff I can do best, creating Hyperapp.
