### ISSUE TITLE
Remove reference to payload filters from tutorial

### ISSUE THREAD

**Issue by dwknippers** [jorgebucaran/hyperapp#965]
Currently the tutorial on the website references **payload filters**.
This was _experimental_ functionality and will be removed in the future (v2).

Ref: https://github.com/jorgebucaran/hyperapp/blob/minimizations/docs/tutorial.md#payloadfilters

**Comment by zaiste** [comment]
@dwknippers what's the proper alternative in this scenario?

**Comment by jorgebucaran** [comment]
@zaiste The trick is that an action can return an action too (`=> [MyAction, newPayload]`), so I usually define a function to help me with that.

```js
const withPayload = (filter) => (_, x) => filter(x)
```

and use it like this for example:

```js
{
  oninput: withPayload((event) => [
    MyAction,
    { id: state.currentId, value: event.target.value },
  ]),
}
```

The action that carries the payload is the anonymous function in the middle `(_, x)` of `withPayload`.


We could (and probably should) export that from **@hyperapp/events**, as I also want to include higher level event utilities. e.g:

```js
const targetValue = (action) =>
  withPayload(({ target: { value } }) => [action, value])
```

**Comment by zaceno** [comment]
This has been adressed in #994 We can close here I think

**Comment by Seanmcdon** [comment]
This should be in the docs somewhere? This is a high use-case. Payloads that can stopPropagation and send ids, etc.
