### ISSUE TITLE
Application running with v2.0.4 stopped working when upgraded to v2.0.5

### ISSUE THREAD

**Issue by hlibco** [jorgebucaran/hyperapp#966]
Hi @jorgebucaran, thanks for the great work on Hyperapp. The latest release (2.0.5) doesn't seem compatible with the previous version (2.0.4). 

This repository [https://github.com/anticrisis/hyperapp-starter](https://github.com/anticrisis/hyperapp-starter) uses Hyperapp "latest" (2.0.5) and running `yarn start` you can see a blank page (nothing being rendered). However, if you change the Hyperapp version to 2.0.4, the application is rendered correctly in the browser.

Any thoughts?

@anticrisis I'm tagging you here for visibility and in case you have any insights to share.

**Comment by britt** [comment]
I just encountered a similar problem. While trying to run the add/subtract example from the site it wouldn't render and threw `Uncaught TypeError: Cannot read property 'is' of undefined`. I was using v2.0.5. I rolled back to v2.0.4 and it worked. It looks like a recurrence of #887

**Comment by hlibco** [comment]
Hey @britt the fix that worked for me was to wrap the strings in the "components" by the new "text()" function exported by the hyperapp module.

Apparently, the issue is caused by the way the new implementation of the `h` that is not backwards compatible.

You might find helpful to join us on Slack and follow the thread opened yesterday in the general channel to know more details.
