### ISSUE TITLE
Support more SVG elements

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/hyperapp#967]
[@hyperapp/html](https://github.com/jorgebucaran/hyperapp/tree/master/pkg/html) provides functions for HTML elements like `a`, `input`, and `form`, but there are none for SVG elements like `circle`, `path`, or `polygon` which Hyperapp supports.

**Comment by jaeh** [comment]
https://github.com/magic/tags/blob/master/src/index.mjs#L237

the link above shows all svg tags in an array, extracted from
https://developer.mozilla.org/en-US/docs/Web/SVG/Element

**Comment by okwolf** [comment]
Is this resolved by the [`@hyperapp/svg` package](https://github.com/jorgebucaran/hyperapp/blob/main/packages/svg/index.js)?

**Comment by jorgebucaran** [comment]
Yes! 🙌
