### ISSUE TITLE
The `payload filter` feature in tutorial does not work anymore.

### ISSUE THREAD

**Issue by xieyuheng** [jorgebucaran/hyperapp#972]
when changing `const SetFilter = (state, event) => ({ ...state, filter: event.target.value })` ,

to `const SetFilter = (state, word) => ({ ...state, filter: word })`.

The `oninput: [SetFilter, (event) => event.target.value]` in the tutorial seems do not work anymore, 

Maybe use `oninput: (state, event) => SetFilter(state, event.target.value)`.

**Comment by jorgebucaran** [comment]
@xieyuheng Just like #973, this is also a bug in the documentation. We're tracking this here: https://github.com/jorgebucaran/hyperapp/issues/965. Thanks.
