### ISSUE TITLE
Navigation possibly not removing event listeners

### ISSUE THREAD

**Issue by hlibco** [jorgebucaran/hyperapp#976]
https://github.com/jorgebucaran/hyperapp/blob/3b606b514b1d86fbd1c8ba522e7685fa2aef5ebf/pkg/navigation/index.js#L42

@jorgebucaran Isn't it suppose to be `removeEventListener()` instead?

**Comment by jorgebucaran** [comment]
@hlibco LOL. Yes, you're absolutely right. That's a bug. This package is not published yet, but if you could send me a patch that would be great! Thanks.
