### ISSUE TITLE
Change root of app

### ISSUE THREAD

**Issue by Spankyed** [jorgebucaran/hyperapp#979]
Making a chrome extension with hyperapp similar to Grammarly. I want to mount and unmount the app, while maintaining state. Something like so..

```
var editor = document.querySelector('note-edit')
const mountedApp = app(state, actions, view, editor )

onNoteEdit((newEditor)=>{
    mountedApp.root(newEditor)
})
```

**Comment by jorgebucaran** [comment]
That would be a mix of Hyperapp and vanilla JavaScript kind of app and Hyperapp is not optimized for that. I'd just show my UI while the user is typing, or hide it otherwise. That would be the Hyperapp way. 

Perhaps you have a more involved use case than you were able to describe, but that wasn't obvious from the question. Based on the information presented here, it looks to me like you just want to toggle all or a section of your UI based on a state prop.

**Comment by Spankyed** [comment]
Two apps, hyperapp and angular. The root of the hyperapp application gets removed by the angular app. Therefore I have to recreate hyperapp everytime angular changes the UI and removes the root element. If I could just change the root element of the hyperapp, I wouldn't have to recreate the hyperapp everytime.

**Comment by jorgebucaran** [comment]
@Spankyed Hmm, I see. Then the easiest way is to recreate the app every time. There's no built-in way to resurrect your app after you've destroyed it. What's the disadvantage of that?

And I wouldn't recommend setting the root to `document.body` either. I know some people like to do that, but that's probably never a good idea.

**Comment by Spankyed** [comment]
Having to recreate every time isn't a show stopper, although there is some overhead to doing this. I'm just wary as to whether or not the application is being destroyed properly. Ostensibly, it is there one second and gone the next. Hate to find out down the road that not only do we have to recreate every time, but previous instances are lingering around in the bg somewhere leaking memory.

**Comment by jorgebucaran** [comment]
I'm with you there, but I suggest you modify your angular app to stop removing Hyperpp's app if you can. Ideally, it would just be a single Hyperapp app, but I realize that's no possible in this situation. By the way, it's possible to control Hyperapp from the outside (from the angular app) using effects and subscriptions, but you'd need to write those yourself. They could act as a declarative wrapper of the browser's remove/addEventListener and dispatchEvent APIs.

Also watch for #863, as that may become the official way to kill apps in the future. 👋

**Comment by Spankyed** [comment]
I wish, the angular app cannot interact with hyperapp.  The chrome extension needs to be independent of whatever website it might be on. Will keep an eye on issue #863.

**Comment by jorgebucaran** [comment]
@Spankyed V1 was far from simpler, perhaps just easier to get started with. Here's the thing, though it's deprecated, and I can't invest any time to support it. This all reminds me of Hickey's [Simplicity Matters talk](https://www.youtube.com/watch?v=rI8tNMsozo0)—you should definitely watch it.

**Comment by jorgebucaran** [comment]
@Spankyed V1 was far from simpler, perhaps just easier to get started with. Here's the thing though, it's deprecated, and I can't invest any time to support it. All my comments so far assumed you were using V2. This all reminds me of Hickey's [Simplicity Matters talk](https://www.youtube.com/watch?v=rI8tNMsozo0)—you should definitely watch it.
