### ISSUE TITLE
hyperapp h won't work for buble jsx

### ISSUE THREAD

**Issue by apla** [jorgebucaran/hyperapp#980]
I'm using [buble](https://buble.surge.sh/) to convert `jsx` to `h` calls. Somewhere between 2.0.4 and 2.0.8 it stopped working. At least I see two problems:

1. when `h` second parameter is `null`, `null.key` gives exception
2. `h` rest arguments ignored

My example (you can change 2.0.4 to 2.0.8 to reproduce the problem):

```javascript
<!DOCTYPE html>
<html lang="en">

<head>
	<script src="https://unpkg.com/buble@0.20.0/dist/buble-browser-deps.umd.js"></script>
	
	<script type="text/babel" real-type="module">

		import { h, app } from "https://unpkg.com/hyperapp@2.0.4";

		const AddTodo = (state) => ({
			...state,
			todos: state.todos.concat(state.value),
		});

		const NewValue = (state, event) => ({
			...state,
			value: event.target.value,
		});

		function MainView (state) {
			const { todos, value } = state;
			return <main>
				<input type="text" oninput={NewValue} value={value}/>
				<button onclick={AddTodo}>Add</button>
				<ul>
					{todos.map((todo) => <li>{todo}</li>)}
				</ul>
			</main>
		}

		app({
			init: { todos: [], value: "" },
			view: MainView,
			node: document.getElementById("app"),
		});

	</script>

	<!--script src="buble-convert-jsx.js"></script-->
	<script type="text/javascript">
	// prevent variable leaks to window
(function () {
    var scripts = document.querySelectorAll ("[type='text/babel']");
    scripts.forEach(el => {
        const script = buble.transform (el.innerHTML, {
            jsx: 'h',
            objectAssign: "Object.assign",
            transforms: {moduleImport: false}
        }).code,
            node = document.createElement ("script");
        for(const attr of [].slice.call (el.attributes))
            node.setAttribute(attr.name, el.attributes[attr.name].textContent);
        node.type = el.attributes["real-type"] ? el.attributes["real-type"].textContent : "text/javascript";
        node.innerHTML = script;
        el.parentElement.replaceChild (node,el);
    });
})();
	</script>

</head>

<body>
	<main id="app"></main>
</body>

</html>
```

**Comment by jorgebucaran** [comment]
Hey! You're absolutely right.  Hyperapp will longer support JSX out of the box, but adding it to your project is easy! All you need to do is handle function types and nested arrays through our `h` and `text` functions.

```js 
import { h, text } from "hyperapp"

export default (type, props, ...children) =>
  typeof type === "function"
    ? type(props, children)
    : h(
        type,
        props || {},
        []
          .concat(...children)
          .map((any) =>
            typeof any === "string" || typeof any === "number" ? text(any) : any
          )
      )
```

Import that everywhere you're using JSX and you'll be good to go. 

I realize you know what you're doing, but just for the record, to compile JSX to JavaScript with Babel (I bet is no more difficult with Bublé), install the JSX transform plugin, and create a `.babelrc` file in the root of your project like this one.

```json
{
  "plugins": [
    [
      "transform-react-jsx",
      {
        "pragma": "h"
      }
    ]
  ]
}
```

That's it.

Now, just trying to better the world here. Did you know there's also [Hyperlit](https://github.com/zaceno/hyperlit). A JSX-like ttl for Hyperapp. A pure JavaScript alternative and not a proprietary language extension married to React.

Of course, there's also the official [@hyperapp/html](https://github.com/jorgebucaran/hyperapp/tree/master/pkg/html) module. It's just plain functions. No hidden complexity. Think SwiftUI for JavaScript.
