### ISSUE TITLE
Some questions of microtask.

### ISSUE THREAD

**Issue by yisar** [jorgebucaran/hyperapp#981]
https://github.com/jorgebucaran/hyperapp/commit/c7ae927d4fefb4f125a27ce61aec9894445c74be

I don't quite understand what the bug are like here. Can you give me a simple demo

I think RAF and microtask clear a queue before redrawing

An example is needed here, thank you very much!

**Comment by jorgebucaran** [comment]
Hey, @yisar. Unfortunately, it would take me a while to create demo that show the pros and cons for each method, time I don't have right now. I appreciate the interest, but this is neither urgent, blocking or a bug we must to fix, so I don't feel like keeping this open. I can't promise I'll create a demo any time soon, but you may stay subscribed to this issue or check back again in the future as I may get to it eventually.

Thank you!
