### ISSUE TITLE
Redraw a view with an Async action

### ISSUE THREAD

**Issue by miladhashemi** [jorgebucaran/hyperapp#995]
Hi,
At one action I need fetching data from server and then after some computation , the result must be placed in state.
I read the `hyperapp v1.2.10` doc. accorfing to it, i called second action at end of async action. but i never had redrawing.

**Comment by zaceno** [comment]
It’s been forever since I used v1.x.x of Hyperapp, so I’m not sure how much I can help. But if you could post a stripped down basic example of what you are trying to do (ideally with an online tool like codepen) that would make it easier.

**Comment by jorgebucaran** [comment]
@miladhashemi Hey! I'm curious about why you are using V1. What's the background here?

**Comment by miladhashemi** [comment]
I use [OS.js](https://github.com/os-js/OS.js), that uses `hyperapp v1.2.10`.
my issue resolved with the help of OS.js contributor. 
#https://github.com/os-js/OS.js/issues/756
